// Code generated by scripts/configgen from config_aws_lambda_microvm.go; DO NOT EDIT.

package cli

import (
	"flag"
	"strings"
)

type fileAWSLambdaMicroVMConfig struct {
	Image             string    `yaml:"image,omitempty"`
	ImageVersion      string    `yaml:"imageVersion,omitempty"`
	ExecutionRoleARN  string    `yaml:"executionRoleArn,omitempty"`
	Workdir           string    `yaml:"workdir,omitempty"`
	IngressConnectors *[]string `yaml:"ingressConnectors,omitempty"`
	EgressConnectors  *[]string `yaml:"egressConnectors,omitempty"`
	ForgetMissing     *bool     `yaml:"forgetMissing,omitempty"`
}

const AWSLambdaMicroVMConfigDefaultWorkdir string = "/workspace/crabbox"

func defaultAWSLambdaMicroVMConfig() AWSLambdaMicroVMConfig {
	return AWSLambdaMicroVMConfig{
		Workdir: AWSLambdaMicroVMConfigDefaultWorkdir,
	}
}

// AWSLambdaMicroVMConfigApplied records accepted assignments during one application.
type AWSLambdaMicroVMConfigApplied struct {
	InputAccepted    bool
	Image            bool
	ImageVersion     bool
	ExecutionRoleARN bool
	Workdir          bool
}

func (cfg *AWSLambdaMicroVMConfig) applyFile(file *fileAWSLambdaMicroVMConfig) (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "awsLambdaMicroVM")
	return applied, err
}

func (cfg *AWSLambdaMicroVMConfig) applyEnv() (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// AWSLambdaMicroVMConfigFlagValues holds parsed values; only visited flags are applied.
type AWSLambdaMicroVMConfigFlagValues struct {
	Image             *string
	ImageVersion      *string
	ExecutionRoleARN  *string
	Workdir           *string
	IngressConnectors *string
	EgressConnectors  *string
	ForgetMissing     *bool
}

// RegisterAWSLambdaMicroVMConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAWSLambdaMicroVMConfigFlags(fs *flag.FlagSet, defaults AWSLambdaMicroVMConfig) AWSLambdaMicroVMConfigFlagValues {
	return AWSLambdaMicroVMConfigFlagValues{
		Image:             fs.String("aws-lambda-microvm-image", defaults.Image, "Lambda MicroVM image ARN"),
		ImageVersion:      fs.String("aws-lambda-microvm-image-version", defaults.ImageVersion, "Lambda MicroVM image version (default latest active)"),
		ExecutionRoleARN:  fs.String("aws-lambda-microvm-execution-role-arn", defaults.ExecutionRoleARN, "optional IAM execution role ARN"),
		Workdir:           fs.String("aws-lambda-microvm-workdir", defaults.Workdir, "absolute runner workdir"),
		IngressConnectors: fs.String("aws-lambda-microvm-ingress-connectors", strings.Join(defaults.IngressConnectors, ","), "comma-separated ingress connector ARNs"),
		EgressConnectors:  fs.String("aws-lambda-microvm-egress-connectors", strings.Join(defaults.EgressConnectors, ","), "comma-separated egress connector ARNs"),
		ForgetMissing:     fs.Bool("aws-lambda-microvm-forget-missing", defaults.ForgetMissing, "remove local claim when the MicroVM is already missing"),
	}
}

// AWSLambdaMicroVMConfigVisitedFlags records raw flag visits, independently of application.
type AWSLambdaMicroVMConfigVisitedFlags struct {
	Image            bool
	ImageVersion     bool
	ExecutionRoleARN bool
	Workdir          bool
}

// AWSLambdaMicroVMConfigFlagPresence reports visits for tracked flag bindings.
func AWSLambdaMicroVMConfigFlagPresence(fs *flag.FlagSet) AWSLambdaMicroVMConfigVisitedFlags {
	var visited AWSLambdaMicroVMConfigVisitedFlags
	recordConfigFlagVisits[AWSLambdaMicroVMConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AWSLambdaMicroVMConfigFlagValues) Apply(cfg *AWSLambdaMicroVMConfig, fs *flag.FlagSet) (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
