// Code generated by scripts/configgen from config_namespace.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
	"strconv"
	"strings"
	"time"
)

type fileNamespaceConfig struct {
	Image               string `yaml:"image,omitempty"`
	Size                string `yaml:"size,omitempty"`
	Repository          string `yaml:"repository,omitempty"`
	Site                string `yaml:"site,omitempty"`
	VolumeSizeGB        int    `yaml:"volumeSizeGB,omitempty"`
	AutoStopIdleTimeout string `yaml:"autoStopIdleTimeout,omitempty"`
	WorkRoot            string `yaml:"workRoot,omitempty"`
	DeleteOnRelease     *bool  `yaml:"deleteOnRelease,omitempty"`
}

const NamespaceConfigDefaultImage string = "builtin:base"
const NamespaceConfigDefaultAutoStopIdleTimeout time.Duration = 1800 * time.Second
const NamespaceConfigDefaultWorkRoot string = "/workspaces/crabbox"

func defaultNamespaceConfig() NamespaceConfig {
	return NamespaceConfig{
		Image:               NamespaceConfigDefaultImage,
		AutoStopIdleTimeout: NamespaceConfigDefaultAutoStopIdleTimeout,
		WorkRoot:            NamespaceConfigDefaultWorkRoot,
	}
}

// NamespaceConfigApplied records accepted assignments during one application.
type NamespaceConfigApplied struct {
	InputAccepted   bool
	Size            bool
	WorkRoot        bool
	DeleteOnRelease bool
}

func (cfg *NamespaceConfig) applyFile(file *fileNamespaceConfig) (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
	}
	if file.Size != "" {
		cfg.Size = file.Size
		applied.InputAccepted = true
		applied.Size = true
	}
	if file.Repository != "" {
		cfg.Repository = file.Repository
		applied.InputAccepted = true
	}
	if file.Site != "" {
		cfg.Site = file.Site
		applied.InputAccepted = true
	}
	if file.VolumeSizeGB > 0 {
		cfg.VolumeSizeGB = file.VolumeSizeGB
		applied.InputAccepted = true
	}
	if file.AutoStopIdleTimeout != "" {
		if applyLeaseDuration(&cfg.AutoStopIdleTimeout, file.AutoStopIdleTimeout) {
			applied.InputAccepted = true
		}
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if file.DeleteOnRelease != nil {
		cfg.DeleteOnRelease = *file.DeleteOnRelease
		applied.InputAccepted = true
		applied.DeleteOnRelease = true
	}
	return applied, nil
}

func (cfg *NamespaceConfig) applyEnv() (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_IMAGE"); ok {
		cfg.Image = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_SIZE"); ok {
		cfg.Size = value
		applied.InputAccepted = true
		applied.Size = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_REPOSITORY"); ok {
		cfg.Repository = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_SITE"); ok {
		cfg.Site = value
		applied.InputAccepted = true
	}
	if value, ok := lookupEnvInteger("CRABBOX_NAMESPACE_VOLUME_SIZE_GB", strconv.IntSize); ok {
		cfg.VolumeSizeGB = int(value)
		applied.InputAccepted = true
	}
	if value := os.Getenv("CRABBOX_NAMESPACE_AUTO_STOP_IDLE_TIMEOUT"); value != "" {
		if applyLeaseDuration(&cfg.AutoStopIdleTimeout, value) {
			applied.InputAccepted = true
		}
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_WORK_ROOT"); ok {
		cfg.WorkRoot = value
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if value, ok := getenvBool("CRABBOX_NAMESPACE_DELETE_ON_RELEASE"); ok {
		cfg.DeleteOnRelease = value
		applied.InputAccepted = true
		applied.DeleteOnRelease = true
	}
	return applied, nil
}

// NamespaceConfigFlagValues holds parsed values; only visited flags are applied.
type NamespaceConfigFlagValues struct {
	Image               *string
	Size                *string
	Repository          *string
	Site                *string
	VolumeSizeGB        *int
	AutoStopIdleTimeout *string
	WorkRoot            *string
	DeleteOnRelease     *bool
}

// RegisterNamespaceConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNamespaceConfigFlags(fs *flag.FlagSet, defaults NamespaceConfig) NamespaceConfigFlagValues {
	return NamespaceConfigFlagValues{
		Image:               fs.String("namespace-image", defaults.Image, "Namespace Devbox image"),
		Size:                fs.String("namespace-size", defaults.Size, "Namespace Devbox size: S, M, L, or XL"),
		Repository:          fs.String("namespace-repository", defaults.Repository, "Namespace Devbox repository checkout"),
		Site:                fs.String("namespace-site", defaults.Site, "Namespace Devbox site"),
		VolumeSizeGB:        fs.Int("namespace-volume-size-gb", defaults.VolumeSizeGB, "Namespace Devbox persistent volume size in GiB"),
		AutoStopIdleTimeout: fs.String("namespace-auto-stop-idle-timeout", defaults.AutoStopIdleTimeout.String(), "Namespace Devbox idle auto-stop timeout"),
		WorkRoot:            fs.String("namespace-work-root", defaults.WorkRoot, "Namespace Devbox Crabbox work root"),
		DeleteOnRelease:     fs.Bool("namespace-delete-on-release", defaults.DeleteOnRelease, "delete Namespace Devbox on release instead of shutting it down"),
	}
}

// NamespaceConfigVisitedFlags records raw flag visits, independently of application.
type NamespaceConfigVisitedFlags struct {
	Size            bool
	WorkRoot        bool
	DeleteOnRelease bool
}

// NamespaceConfigFlagPresence reports visits for tracked flag bindings.
func NamespaceConfigFlagPresence(fs *flag.FlagSet) NamespaceConfigVisitedFlags {
	return NamespaceConfigVisitedFlags{
		Size:            flagWasSet(fs, "namespace-size"),
		WorkRoot:        flagWasSet(fs, "namespace-work-root"),
		DeleteOnRelease: flagWasSet(fs, "namespace-delete-on-release"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NamespaceConfigFlagValues) Apply(cfg *NamespaceConfig, fs *flag.FlagSet) (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	visited := NamespaceConfigFlagPresence(fs)
	if flagWasSet(fs, "namespace-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if visited.Size {
		cfg.Size = *values.Size
		applied.InputAccepted = true
		applied.Size = true
	}
	if flagWasSet(fs, "namespace-repository") {
		cfg.Repository = *values.Repository
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "namespace-site") {
		cfg.Site = *values.Site
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "namespace-volume-size-gb") {
		cfg.VolumeSizeGB = *values.VolumeSizeGB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "namespace-auto-stop-idle-timeout") {
		parsed, err := time.ParseDuration(strings.TrimSpace(*values.AutoStopIdleTimeout))
		if err != nil || parsed <= 0 {
			return applied, exit(2, "%s", "namespace auto-stop idle timeout must be a positive duration")
		}
		cfg.AutoStopIdleTimeout = parsed
		applied.InputAccepted = true
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if visited.DeleteOnRelease {
		cfg.DeleteOnRelease = *values.DeleteOnRelease
		applied.InputAccepted = true
		applied.DeleteOnRelease = true
	}
	return applied, nil
}
