// Code generated by scripts/configgen from config_nebius.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileNebiusConfig struct {
	CLI              string   `yaml:"cli,omitempty"`
	Profile          string   `yaml:"profile,omitempty"`
	ParentID         string   `yaml:"parentId,omitempty"`
	SubnetID         string   `yaml:"subnetId,omitempty"`
	Platform         string   `yaml:"platform,omitempty"`
	Preset           string   `yaml:"preset,omitempty"`
	ImageFamily      string   `yaml:"imageFamily,omitempty"`
	DiskType         string   `yaml:"diskType,omitempty"`
	DiskSizeGiB      int      `yaml:"diskSizeGiB,omitempty"`
	User             string   `yaml:"user,omitempty"`
	PublicIP         string   `yaml:"publicIP,omitempty"`
	SecurityGroupIDs []string `yaml:"securityGroupIds,omitempty"`
	ServiceAccountID string   `yaml:"serviceAccountId,omitempty"`
	RecoveryPolicy   string   `yaml:"recoveryPolicy,omitempty"`
}

const NebiusConfigDefaultCLI string = "nebius"
const NebiusConfigDefaultPlatform string = "cpu-d3"
const NebiusConfigDefaultPreset string = "4vcpu-16gb"
const NebiusConfigDefaultImageFamily string = "ubuntu24.04-driverless"
const NebiusConfigDefaultDiskType string = "network_ssd"
const NebiusConfigDefaultDiskSizeGiB int = 50
const NebiusConfigDefaultUser string = "crabbox"
const NebiusConfigDefaultPublicIP string = "dynamic"
const NebiusConfigDefaultRecoveryPolicy string = "fail"

func defaultNebiusConfig() NebiusConfig {
	return NebiusConfig{
		CLI:            NebiusConfigDefaultCLI,
		Platform:       NebiusConfigDefaultPlatform,
		Preset:         NebiusConfigDefaultPreset,
		ImageFamily:    NebiusConfigDefaultImageFamily,
		DiskType:       NebiusConfigDefaultDiskType,
		DiskSizeGiB:    NebiusConfigDefaultDiskSizeGiB,
		User:           NebiusConfigDefaultUser,
		PublicIP:       NebiusConfigDefaultPublicIP,
		RecoveryPolicy: NebiusConfigDefaultRecoveryPolicy,
	}
}

// NebiusConfigApplied records accepted assignments during one application.
type NebiusConfigApplied struct {
	InputAccepted bool
}

func (cfg *NebiusConfig) applyFile(file *fileNebiusConfig, trusted bool) (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "nebius")
	return applied, err
}

func (cfg *NebiusConfig) applyEnv() (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 14)
	return applied, err
}

// NebiusConfigFlagValues holds parsed values; only visited flags are applied.
type NebiusConfigFlagValues struct {
	CLI              *string
	Profile          *string
	ParentID         *string
	SubnetID         *string
	Platform         *string
	Preset           *string
	ImageFamily      *string
	DiskType         *string
	DiskSizeGiB      *int
	User             *string
	PublicIP         *string
	SecurityGroupIDs *string
	ServiceAccountID *string
	RecoveryPolicy   *string
}

// RegisterNebiusConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNebiusConfigFlags(fs *flag.FlagSet, defaults NebiusConfig) NebiusConfigFlagValues {
	return NebiusConfigFlagValues{
		CLI:              fs.String("nebius-cli", defaults.CLI, "Nebius CLI path"),
		Profile:          fs.String("nebius-profile", defaults.Profile, "Nebius CLI profile name"),
		ParentID:         fs.String("nebius-parent-id", defaults.ParentID, "Nebius parent/project ID"),
		SubnetID:         fs.String("nebius-subnet-id", defaults.SubnetID, "Nebius subnet ID"),
		Platform:         fs.String("nebius-platform", defaults.Platform, "Nebius compute platform"),
		Preset:           fs.String("nebius-preset", defaults.Preset, "Nebius compute preset"),
		ImageFamily:      fs.String("nebius-image-family", defaults.ImageFamily, "Nebius boot image family"),
		DiskType:         fs.String("nebius-disk-type", defaults.DiskType, "Nebius boot disk type"),
		DiskSizeGiB:      fs.Int("nebius-disk-size-gib", defaults.DiskSizeGiB, "Nebius boot disk size in GiB"),
		User:             fs.String("nebius-user", defaults.User, "SSH user for Nebius VMs"),
		PublicIP:         fs.String("nebius-public-ip", defaults.PublicIP, "Nebius public IP mode: dynamic or none"),
		SecurityGroupIDs: fs.String("nebius-security-group-ids", "", "comma-separated Nebius security group IDs"),
		ServiceAccountID: fs.String("nebius-service-account-id", defaults.ServiceAccountID, "Nebius service account ID for VMs"),
		RecoveryPolicy:   fs.String("nebius-recovery-policy", defaults.RecoveryPolicy, "Nebius create recovery policy: fail"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NebiusConfigFlagValues) Apply(cfg *NebiusConfig, fs *flag.FlagSet) (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	if flagWasSet(fs, "nebius-cli") {
		cfg.CLI = *values.CLI
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-profile") {
		cfg.Profile = *values.Profile
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-parent-id") {
		cfg.ParentID = *values.ParentID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-subnet-id") {
		cfg.SubnetID = *values.SubnetID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-platform") {
		cfg.Platform = *values.Platform
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-preset") {
		cfg.Preset = *values.Preset
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-image-family") {
		cfg.ImageFamily = *values.ImageFamily
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-disk-type") {
		cfg.DiskType = *values.DiskType
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-disk-size-gib") {
		cfg.DiskSizeGiB = *values.DiskSizeGiB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-user") {
		cfg.User = *values.User
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-public-ip") {
		cfg.PublicIP = *values.PublicIP
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-security-group-ids") {
		cfg.SecurityGroupIDs = splitCommaList(*values.SecurityGroupIDs)
		if len(cfg.SecurityGroupIDs) == 0 {
			cfg.SecurityGroupIDs = nil
		}
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-service-account-id") {
		cfg.ServiceAccountID = *values.ServiceAccountID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "nebius-recovery-policy") {
		cfg.RecoveryPolicy = *values.RecoveryPolicy
		applied.InputAccepted = true
	}
	return applied, nil
}
