// Code generated by scripts/configgen from config_tencentcloud.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTencentCloudConfig struct {
	Region                  string   `yaml:"region,omitempty"`
	Zone                    string   `yaml:"zone,omitempty"`
	Image                   string   `yaml:"image,omitempty"`
	Type                    string   `yaml:"type,omitempty"`
	VPCID                   string   `yaml:"vpcId,omitempty"`
	SubnetID                string   `yaml:"subnetId,omitempty"`
	SecurityGroupID         string   `yaml:"securityGroupId,omitempty"`
	SSHCIDRs                []string `yaml:"sshCIDRs,omitempty"`
	RootGB                  int64    `yaml:"rootGB,omitempty"`
	InternetChargeType      string   `yaml:"internetChargeType,omitempty"`
	InternetMaxBandwidthOut int64    `yaml:"internetMaxBandwidthOut,omitempty"`
	APIEndpoint             string   `yaml:"apiEndpoint,omitempty"`
}

func defaultTencentCloudConfig() TencentCloudConfig {
	return TencentCloudConfig{}
}

// TencentCloudConfigApplied records accepted assignments during one application.
type TencentCloudConfigApplied struct {
	InputAccepted bool
	Region        bool
	Zone          bool
	Image         bool
	Type          bool
}

func (cfg *TencentCloudConfig) applyFile(file *fileTencentCloudConfig, trusted bool) (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "tencentcloud")
	return applied, err
}

func (cfg *TencentCloudConfig) applyEnv() (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// TencentCloudConfigFlagValues holds parsed values; only visited flags are applied.
type TencentCloudConfigFlagValues struct {
	Region                  *string
	Zone                    *string
	Image                   *string
	Type                    *string
	VPCID                   *string
	SubnetID                *string
	SecurityGroupID         *string
	SSHCIDRs                *string
	RootGB                  *int64
	InternetChargeType      *string
	InternetMaxBandwidthOut *int64
	APIEndpoint             *string
}

// RegisterTencentCloudConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTencentCloudConfigFlags(fs *flag.FlagSet, defaults TencentCloudConfig) TencentCloudConfigFlagValues {
	return TencentCloudConfigFlagValues{
		Region:                  fs.String("tencentcloud-region", defaults.Region, "Tencent Cloud CVM region"),
		Zone:                    fs.String("tencentcloud-zone", defaults.Zone, "Tencent Cloud CVM availability zone"),
		Image:                   fs.String("tencentcloud-image", defaults.Image, "Tencent Cloud CVM image ID"),
		Type:                    fs.String("tencentcloud-type", defaults.Type, "Tencent Cloud CVM instance type"),
		VPCID:                   fs.String("tencentcloud-vpc-id", defaults.VPCID, "Tencent Cloud VPC ID"),
		SubnetID:                fs.String("tencentcloud-subnet-id", defaults.SubnetID, "Tencent Cloud subnet ID"),
		SecurityGroupID:         fs.String("tencentcloud-security-group-id", defaults.SecurityGroupID, "Tencent Cloud security group ID"),
		SSHCIDRs:                fs.String("tencentcloud-ssh-cidrs", "", "comma-separated Tencent Cloud SSH source CIDRs; reserved for managed security-group support"),
		RootGB:                  fs.Int64("tencentcloud-root-gb", defaults.RootGB, "Tencent Cloud CVM system disk size in GiB"),
		InternetChargeType:      fs.String("tencentcloud-internet-charge-type", defaults.InternetChargeType, "Tencent Cloud public bandwidth charge type"),
		InternetMaxBandwidthOut: fs.Int64("tencentcloud-internet-max-bandwidth-out", defaults.InternetMaxBandwidthOut, "Tencent Cloud public outbound bandwidth in Mbps"),
		APIEndpoint:             fs.String("tencentcloud-api-endpoint", defaults.APIEndpoint, "Tencent Cloud CVM API endpoint"),
	}
}

// TencentCloudConfigVisitedFlags records raw flag visits, independently of application.
type TencentCloudConfigVisitedFlags struct {
	Region bool
	Zone   bool
	Image  bool
	Type   bool
}

// TencentCloudConfigFlagPresence reports visits for tracked flag bindings.
func TencentCloudConfigFlagPresence(fs *flag.FlagSet) TencentCloudConfigVisitedFlags {
	var visited TencentCloudConfigVisitedFlags
	recordConfigFlagVisits[TencentCloudConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TencentCloudConfigFlagValues) Apply(cfg *TencentCloudConfig, fs *flag.FlagSet) (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
