// Code generated by scripts/configgen from config_namespace_instance.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
	"strings"
)

type fileNamespaceInstanceConfig struct {
	CLIPath     string   `yaml:"cli,omitempty"`
	MachineType string   `yaml:"machineType,omitempty"`
	Duration    string   `yaml:"duration,omitempty"`
	Region      string   `yaml:"region,omitempty"`
	Endpoint    string   `yaml:"endpoint,omitempty"`
	Keychain    string   `yaml:"keychain,omitempty"`
	Volumes     []string `yaml:"volumes,omitempty"`
	WorkRoot    string   `yaml:"workRoot,omitempty"`
	Bare        *bool    `yaml:"bare,omitempty"`
}

const NamespaceInstanceConfigDefaultCLIPath string = "nsc"
const NamespaceInstanceConfigDefaultWorkRoot string = "/work/crabbox"
const NamespaceInstanceConfigDefaultBare bool = true

func defaultNamespaceInstanceConfig() NamespaceInstanceConfig {
	return NamespaceInstanceConfig{
		CLIPath:  NamespaceInstanceConfigDefaultCLIPath,
		WorkRoot: NamespaceInstanceConfigDefaultWorkRoot,
		Bare:     NamespaceInstanceConfigDefaultBare,
	}
}

// NamespaceInstanceConfigApplied records accepted assignments during one application.
type NamespaceInstanceConfigApplied struct {
	CLIPath bool
}

func (cfg *NamespaceInstanceConfig) applyFile(file *fileNamespaceInstanceConfig, trusted bool) (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	if file == nil {
		return applied, nil
	}
	if trusted && file.CLIPath != "" {
		cfg.CLIPath = file.CLIPath
		applied.CLIPath = true
	}
	if file.MachineType != "" {
		cfg.MachineType = file.MachineType
	}
	if file.Duration != "" {
		applyLeaseDuration(&cfg.Duration, file.Duration)
	}
	if trusted && file.Region != "" {
		cfg.Region = file.Region
	}
	if trusted && file.Endpoint != "" {
		cfg.Endpoint = file.Endpoint
	}
	if trusted && file.Keychain != "" {
		cfg.Keychain = file.Keychain
	}
	if trusted && file.Volumes != nil {
		cfg.Volumes = append([]string(nil), (file.Volumes)...)
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
	}
	if file.Bare != nil {
		cfg.Bare = *file.Bare
	}
	return applied, nil
}

func (cfg *NamespaceInstanceConfig) applyEnv() (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_NAMESPACE_INSTANCE_CLI"); ok {
		cfg.CLIPath = value
		applied.CLIPath = true
	}
	cfg.MachineType = getenv("CRABBOX_NAMESPACE_INSTANCE_MACHINE_TYPE", cfg.MachineType)
	if value := os.Getenv("CRABBOX_NAMESPACE_INSTANCE_DURATION"); value != "" {
		applyLeaseDuration(&cfg.Duration, value)
	}
	cfg.Region = getenv("CRABBOX_NAMESPACE_INSTANCE_REGION", cfg.Region)
	cfg.Endpoint = getenv("CRABBOX_NAMESPACE_INSTANCE_ENDPOINT", cfg.Endpoint)
	cfg.Keychain = getenv("CRABBOX_NAMESPACE_INSTANCE_KEYCHAIN", cfg.Keychain)
	if value, ok := getenvList("CRABBOX_NAMESPACE_INSTANCE_VOLUMES"); ok {
		cfg.Volumes = value
	}
	cfg.WorkRoot = getenv("CRABBOX_NAMESPACE_INSTANCE_WORK_ROOT", cfg.WorkRoot)
	if value, ok := getenvBool("CRABBOX_NAMESPACE_INSTANCE_BARE"); ok {
		cfg.Bare = value
	}
	return applied, nil
}

// NamespaceInstanceConfigFlagValues holds parsed values; only visited flags are applied.
type NamespaceInstanceConfigFlagValues struct {
	CLIPath     *string
	MachineType *string
	Duration    *string
	Region      *string
	Endpoint    *string
	Keychain    *string
	Volumes     *appendTrimmedListFlag
	WorkRoot    *string
	Bare        *bool
}

// RegisterNamespaceInstanceConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNamespaceInstanceConfigFlags(fs *flag.FlagSet, defaults NamespaceInstanceConfig) NamespaceInstanceConfigFlagValues {
	listVolumes := newAppendTrimmedListFlag(defaults.Volumes)
	values := NamespaceInstanceConfigFlagValues{
		CLIPath:     fs.String("namespace-instance-cli", defaults.CLIPath, "Namespace nsc CLI path"),
		MachineType: fs.String("namespace-instance-machine-type", defaults.MachineType, "Namespace instance CPUxMemoryGB shape, for example 4x8"),
		Duration:    fs.String("namespace-instance-duration", defaults.Duration.String(), "Namespace instance duration; defaults to --ttl"),
		Region:      fs.String("namespace-instance-region", defaults.Region, "Namespace region"),
		Endpoint:    fs.String("namespace-instance-endpoint", defaults.Endpoint, "Namespace API endpoint"),
		Keychain:    fs.String("namespace-instance-keychain", defaults.Keychain, "Namespace token keychain"),
		Volumes:     listVolumes,
		WorkRoot:    fs.String("namespace-instance-work-root", defaults.WorkRoot, "remote Crabbox work root"),
		Bare:        fs.Bool("namespace-instance-bare", defaults.Bare, "disable Kubernetes for a smaller instance"),
	}
	fs.Var(listVolumes, "namespace-instance-volume", "Namespace volume kind:tag:mountpoint:size; repeatable")
	return values
}

// NamespaceInstanceConfigVisitedFlags records raw flag visits, independently of application.
type NamespaceInstanceConfigVisitedFlags struct {
	CLIPath bool
}

// NamespaceInstanceConfigFlagPresence reports visits for tracked flag bindings.
func NamespaceInstanceConfigFlagPresence(fs *flag.FlagSet) NamespaceInstanceConfigVisitedFlags {
	return NamespaceInstanceConfigVisitedFlags{
		CLIPath: flagWasSet(fs, "namespace-instance-cli"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NamespaceInstanceConfigFlagValues) Apply(cfg *NamespaceInstanceConfig, fs *flag.FlagSet) (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	visited := NamespaceInstanceConfigFlagPresence(fs)
	if visited.CLIPath {
		cfg.CLIPath = *values.CLIPath
		applied.CLIPath = true
	}
	if flagWasSet(fs, "namespace-instance-machine-type") {
		cfg.MachineType = *values.MachineType
	}
	if flagWasSet(fs, "namespace-instance-duration") {
		if strings.TrimSpace(*values.Duration) == "0s" {
			cfg.Duration = 0
		} else if err := ApplyLeaseDuration(&cfg.Duration, *values.Duration); err != nil {
			return applied, err
		}
	}
	if flagWasSet(fs, "namespace-instance-region") {
		cfg.Region = *values.Region
	}
	if flagWasSet(fs, "namespace-instance-endpoint") {
		cfg.Endpoint = *values.Endpoint
	}
	if flagWasSet(fs, "namespace-instance-keychain") {
		cfg.Keychain = *values.Keychain
	}
	if flagWasSet(fs, "namespace-instance-volume") {
		cfg.Volumes = append([]string(nil), values.Volumes.stringListFlag...)
	}
	if flagWasSet(fs, "namespace-instance-work-root") {
		cfg.WorkRoot = *values.WorkRoot
	}
	if flagWasSet(fs, "namespace-instance-bare") {
		cfg.Bare = *values.Bare
	}
	return applied, nil
}
