// Code generated by scripts/configgen from config_kubevirt.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileKubeVirtConfig struct {
	Kubectl         string `yaml:"kubectl,omitempty"`
	Virtctl         string `yaml:"virtctl,omitempty"`
	Kubeconfig      string `yaml:"kubeconfig,omitempty"`
	Context         string `yaml:"context,omitempty"`
	Namespace       string `yaml:"namespace,omitempty"`
	Template        string `yaml:"template,omitempty"`
	SSHUser         string `yaml:"sshUser,omitempty"`
	SSHKey          string `yaml:"sshKey,omitempty"`
	SSHPublicKey    string `yaml:"sshPublicKey,omitempty"`
	SSHPort         string `yaml:"sshPort,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
}

const KubeVirtConfigDefaultKubectl string = "kubectl"
const KubeVirtConfigDefaultVirtctl string = "virtctl"
const KubeVirtConfigDefaultNamespace string = "default"
const KubeVirtConfigDefaultSSHUser string = "crabbox"
const KubeVirtConfigDefaultSSHPort string = "22"
const KubeVirtConfigDefaultWorkRoot string = "/home/crabbox/crabbox"
const KubeVirtConfigDefaultDeleteOnRelease bool = true

func defaultKubeVirtConfig() KubeVirtConfig {
	return KubeVirtConfig{
		Kubectl:         KubeVirtConfigDefaultKubectl,
		Virtctl:         KubeVirtConfigDefaultVirtctl,
		Namespace:       KubeVirtConfigDefaultNamespace,
		SSHUser:         KubeVirtConfigDefaultSSHUser,
		SSHPort:         KubeVirtConfigDefaultSSHPort,
		WorkRoot:        KubeVirtConfigDefaultWorkRoot,
		DeleteOnRelease: KubeVirtConfigDefaultDeleteOnRelease,
	}
}

// KubeVirtConfigApplied records accepted assignments during one application.
type KubeVirtConfigApplied struct {
	InputAccepted   bool
	Kubectl         bool
	Virtctl         bool
	Kubeconfig      bool
	Template        bool
	SSHKey          bool
	SSHPublicKey    bool
	WorkRoot        bool
	DeleteOnRelease bool
}

func (cfg *KubeVirtConfig) applyFile(file *fileKubeVirtConfig, trusted bool) (KubeVirtConfigApplied, error) {
	var applied KubeVirtConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "kubevirt")
	return applied, err
}

func (cfg *KubeVirtConfig) applyEnv() (KubeVirtConfigApplied, error) {
	var applied KubeVirtConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// KubeVirtConfigFlagValues holds parsed values; only visited flags are applied.
type KubeVirtConfigFlagValues struct {
	Kubectl         *string
	Virtctl         *string
	Kubeconfig      *string
	Context         *string
	Namespace       *string
	Template        *string
	SSHUser         *string
	SSHKey          *string
	SSHPublicKey    *string
	SSHPort         *string
	WorkRoot        *string
	DeleteOnRelease *bool
}

// RegisterKubeVirtConfigFlags registers mechanical bindings without selecting a provider.
func RegisterKubeVirtConfigFlags(fs *flag.FlagSet, defaults KubeVirtConfig) KubeVirtConfigFlagValues {
	return KubeVirtConfigFlagValues{
		Kubectl:         fs.String("kubevirt-kubectl", defaults.Kubectl, "kubectl executable"),
		Virtctl:         fs.String("kubevirt-virtctl", defaults.Virtctl, "virtctl executable"),
		Kubeconfig:      fs.String("kubevirt-kubeconfig", defaults.Kubeconfig, "Kubernetes kubeconfig path"),
		Context:         fs.String("kubevirt-context", defaults.Context, "Kubernetes context"),
		Namespace:       fs.String("kubevirt-namespace", defaults.Namespace, "Kubernetes namespace"),
		Template:        fs.String("kubevirt-template", defaults.Template, "KubeVirt VirtualMachine manifest template"),
		SSHUser:         fs.String("kubevirt-ssh-user", defaults.SSHUser, "guest SSH user"),
		SSHKey:          fs.String("kubevirt-ssh-key", defaults.SSHKey, "guest SSH private key"),
		SSHPublicKey:    fs.String("kubevirt-ssh-public-key", defaults.SSHPublicKey, "guest SSH public key inserted into the template"),
		SSHPort:         fs.String("kubevirt-ssh-port", defaults.SSHPort, "guest SSH port"),
		WorkRoot:        fs.String("kubevirt-work-root", defaults.WorkRoot, "guest Crabbox work root"),
		DeleteOnRelease: fs.Bool("kubevirt-delete-on-release", defaults.DeleteOnRelease, "delete the VM on release instead of stopping it"),
	}
}

// KubeVirtConfigVisitedFlags records raw flag visits, independently of application.
type KubeVirtConfigVisitedFlags struct {
	Kubectl         bool
	Virtctl         bool
	Kubeconfig      bool
	Template        bool
	SSHKey          bool
	SSHPublicKey    bool
	WorkRoot        bool
	DeleteOnRelease bool
}

// KubeVirtConfigFlagPresence reports visits for tracked flag bindings.
func KubeVirtConfigFlagPresence(fs *flag.FlagSet) KubeVirtConfigVisitedFlags {
	var visited KubeVirtConfigVisitedFlags
	recordConfigFlagVisits[KubeVirtConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values KubeVirtConfigFlagValues) Apply(cfg *KubeVirtConfig, fs *flag.FlagSet) (KubeVirtConfigApplied, error) {
	var applied KubeVirtConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
