// Code generated by scripts/configgen from config_vercel_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
	"strings"
)

type fileVercelSandboxConfig struct {
	Runtime         *string   `yaml:"runtime,omitempty"`
	Workdir         *string   `yaml:"workdir,omitempty"`
	ProjectID       *string   `yaml:"projectId,omitempty"`
	TeamID          *string   `yaml:"teamId,omitempty"`
	Scope           *string   `yaml:"scope,omitempty"`
	VCPUs           *float64  `yaml:"vcpus,omitempty"`
	TimeoutSecs     *int      `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int      `yaml:"execTimeoutSecs,omitempty"`
	Persistent      *bool     `yaml:"persistent,omitempty"`
	Snapshot        *string   `yaml:"snapshot,omitempty"`
	SnapshotMode    *string   `yaml:"snapshotMode,omitempty"`
	NetworkPolicy   *string   `yaml:"networkPolicy,omitempty"`
	NetworkAllow    *[]string `yaml:"networkAllow,omitempty"`
	NetworkDeny     *[]string `yaml:"networkDeny,omitempty"`
	Ports           *[]string `yaml:"ports,omitempty"`
	ForgetMissing   *bool     `yaml:"forgetMissing,omitempty"`
}

const VercelSandboxConfigDefaultRuntime string = "node24"
const VercelSandboxConfigDefaultWorkdir string = "/vercel/sandbox/crabbox"
const VercelSandboxConfigDefaultExecTimeoutSecs int = 600
const VercelSandboxConfigDefaultNetworkPolicy string = "default"

func defaultVercelSandboxConfig() VercelSandboxConfig {
	return VercelSandboxConfig{
		Runtime:         VercelSandboxConfigDefaultRuntime,
		Workdir:         VercelSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: VercelSandboxConfigDefaultExecTimeoutSecs,
		NetworkPolicy:   VercelSandboxConfigDefaultNetworkPolicy,
	}
}

// VercelSandboxConfigApplied records accepted assignments during one application.
type VercelSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *VercelSandboxConfig) applyFile(file *fileVercelSandboxConfig) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Runtime != nil {
		cfg.Runtime = *file.Runtime
		applied.InputAccepted = true
	}
	if file.Workdir != nil {
		cfg.Workdir = *file.Workdir
		applied.InputAccepted = true
	}
	if file.ProjectID != nil {
		cfg.ProjectID = *file.ProjectID
		applied.InputAccepted = true
	}
	if file.TeamID != nil {
		cfg.TeamID = *file.TeamID
		applied.InputAccepted = true
	}
	if file.Scope != nil {
		cfg.Scope = *file.Scope
		applied.InputAccepted = true
	}
	if file.VCPUs != nil {
		cfg.VCPUs = *file.VCPUs
		applied.InputAccepted = true
	}
	if file.TimeoutSecs != nil {
		if *file.TimeoutSecs < 0 {
			return applied, exit(2, "vercel-sandbox timeoutSecs must be non-negative")
		}
		cfg.TimeoutSecs = *file.TimeoutSecs
		applied.InputAccepted = true
	}
	if file.ExecTimeoutSecs != nil {
		if *file.ExecTimeoutSecs < 0 {
			return applied, exit(2, "vercel-sandbox execTimeoutSecs must be non-negative")
		}
		cfg.ExecTimeoutSecs = *file.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if file.Persistent != nil {
		cfg.Persistent = *file.Persistent
		applied.InputAccepted = true
	}
	if file.Snapshot != nil {
		cfg.Snapshot = *file.Snapshot
		applied.InputAccepted = true
	}
	if file.SnapshotMode != nil {
		cfg.SnapshotMode = *file.SnapshotMode
		applied.InputAccepted = true
	}
	if file.NetworkPolicy != nil {
		cfg.NetworkPolicy = *file.NetworkPolicy
		applied.InputAccepted = true
	}
	if file.NetworkAllow != nil {
		cfg.NetworkAllow = normalizeList(*file.NetworkAllow)
		applied.InputAccepted = true
	}
	if file.NetworkDeny != nil {
		cfg.NetworkDeny = normalizeList(*file.NetworkDeny)
		applied.InputAccepted = true
	}
	if file.Ports != nil {
		cfg.Ports = normalizeList(*file.Ports)
		applied.InputAccepted = true
	}
	if file.ForgetMissing != nil {
		cfg.ForgetMissing = *file.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *VercelSandboxConfig) applyEnv() (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_RUNTIME"); ok {
		cfg.Runtime = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_WORKDIR"); ok {
		cfg.Workdir = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_PROJECT_ID"); ok {
		cfg.ProjectID = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_TEAM_ID"); ok {
		cfg.TeamID = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_SCOPE"); ok {
		cfg.Scope = value
		applied.InputAccepted = true
	}
	if value, ok := lookupEnvFloat("CRABBOX_VERCEL_SANDBOX_VCPUS"); ok {
		cfg.VCPUs = value
		applied.InputAccepted = true
	}
	{
		var accepted bool
		var err error
		cfg.TimeoutSecs, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_VERCEL_SANDBOX_TIMEOUT_SECS", cfg.TimeoutSecs)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	{
		var accepted bool
		var err error
		cfg.ExecTimeoutSecs, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_VERCEL_SANDBOX_EXEC_TIMEOUT_SECS", cfg.ExecTimeoutSecs)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	if value, ok := getenvBool("CRABBOX_VERCEL_SANDBOX_PERSISTENT"); ok {
		cfg.Persistent = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_SNAPSHOT"); ok {
		cfg.Snapshot = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_SNAPSHOT_MODE"); ok {
		cfg.SnapshotMode = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VERCEL_SANDBOX_NETWORK_POLICY"); ok {
		cfg.NetworkPolicy = value
		applied.InputAccepted = true
	}
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_NETWORK_ALLOW"); value != "" {
		cfg.NetworkAllow = splitCommaList(value)
		applied.InputAccepted = true
	}
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_NETWORK_DENY"); value != "" {
		cfg.NetworkDeny = splitCommaList(value)
		applied.InputAccepted = true
	}
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_PORTS"); value != "" {
		cfg.Ports = splitCommaList(value)
		applied.InputAccepted = true
	}
	if value, ok := getenvBool("CRABBOX_VERCEL_SANDBOX_FORGET_MISSING"); ok {
		cfg.ForgetMissing = value
		applied.InputAccepted = true
	}
	return applied, nil
}

// VercelSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type VercelSandboxConfigFlagValues struct {
	Runtime         *string
	Workdir         *string
	ProjectID       *string
	TeamID          *string
	Scope           *string
	VCPUs           *float64
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Persistent      *bool
	Snapshot        *string
	SnapshotMode    *string
	NetworkPolicy   *string
	NetworkAllow    *string
	NetworkDeny     *string
	Ports           *string
	ForgetMissing   *bool
}

// RegisterVercelSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVercelSandboxConfigFlags(fs *flag.FlagSet, defaults VercelSandboxConfig) VercelSandboxConfigFlagValues {
	return VercelSandboxConfigFlagValues{
		Runtime:         fs.String("vercel-sandbox-runtime", defaults.Runtime, "Vercel Sandbox runtime (node26, node24, node22, python3.13)"),
		Workdir:         fs.String("vercel-sandbox-workdir", defaults.Workdir, "Absolute working directory inside the sandbox"),
		ProjectID:       fs.String("vercel-sandbox-project-id", defaults.ProjectID, "Vercel project ID used for sandbox scoping"),
		TeamID:          fs.String("vercel-sandbox-team-id", defaults.TeamID, "Vercel team ID used for sandbox scoping"),
		Scope:           fs.String("vercel-sandbox-scope", defaults.Scope, "Vercel account or team slug used for sandbox scoping"),
		VCPUs:           fs.Float64("vercel-sandbox-vcpus", defaults.VCPUs, "requested Vercel Sandbox vCPU count (0 = service default)"),
		TimeoutSecs:     fs.Int("vercel-sandbox-timeout-secs", defaults.TimeoutSecs, "sandbox lifetime cap in seconds (0 = service default)"),
		ExecTimeoutSecs: fs.Int("vercel-sandbox-exec-timeout-secs", defaults.ExecTimeoutSecs, "command timeout in seconds (0 = service default)"),
		Persistent:      fs.Bool("vercel-sandbox-persistent", defaults.Persistent, "request a persistent sandbox when lifecycle support lands"),
		Snapshot:        fs.String("vercel-sandbox-snapshot", defaults.Snapshot, "snapshot/checkpoint name or ID for future lifecycle use"),
		SnapshotMode:    fs.String("vercel-sandbox-snapshot-mode", defaults.SnapshotMode, "snapshot/checkpoint mode for future lifecycle use"),
		NetworkPolicy:   fs.String("vercel-sandbox-network-policy", defaults.NetworkPolicy, "sandbox network policy: default, public, private, restricted, or none"),
		NetworkAllow:    fs.String("vercel-sandbox-network-allow", strings.Join(defaults.NetworkAllow, ","), "comma-separated outbound CIDR/domain allow list"),
		NetworkDeny:     fs.String("vercel-sandbox-network-deny", strings.Join(defaults.NetworkDeny, ","), "comma-separated outbound IP/CIDR deny list"),
		Ports:           fs.String("vercel-sandbox-ports", strings.Join(defaults.Ports, ","), "comma-separated ports or ranges to expose later"),
		ForgetMissing:   fs.Bool("vercel-sandbox-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VercelSandboxConfigFlagValues) Apply(cfg *VercelSandboxConfig, fs *flag.FlagSet) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	if flagWasSet(fs, "vercel-sandbox-runtime") {
		cfg.Runtime = *values.Runtime
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-project-id") {
		cfg.ProjectID = *values.ProjectID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-team-id") {
		cfg.TeamID = *values.TeamID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-scope") {
		cfg.Scope = *values.Scope
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-vcpus") {
		cfg.VCPUs = *values.VCPUs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-persistent") {
		cfg.Persistent = *values.Persistent
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot") {
		cfg.Snapshot = *values.Snapshot
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot-mode") {
		cfg.SnapshotMode = *values.SnapshotMode
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-policy") {
		cfg.NetworkPolicy = *values.NetworkPolicy
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-allow") {
		cfg.NetworkAllow = splitCommaList(*values.NetworkAllow)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-deny") {
		cfg.NetworkDeny = splitCommaList(*values.NetworkDeny)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-ports") {
		cfg.Ports = splitCommaList(*values.Ports)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-forget-missing") {
		cfg.ForgetMissing = *values.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}
