// Code generated by scripts/configgen from config_phala.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type filePhalaConfig struct {
	CLIPath      string `yaml:"cli,omitempty"`
	InstanceType string `yaml:"instanceType,omitempty"`
	WorkRoot     string `yaml:"workRoot,omitempty"`
	NodeID       string `yaml:"nodeId,omitempty"`
	Compose      string `yaml:"compose,omitempty"`
	Attest       *bool  `yaml:"attest,omitempty"`
}

const PhalaConfigDefaultCLIPath string = "phala"
const PhalaConfigDefaultInstanceType string = "tdx.small"
const PhalaConfigDefaultWorkRoot string = "/var/volatile/crabbox"

func defaultPhalaConfig() PhalaConfig {
	return PhalaConfig{
		CLIPath:      PhalaConfigDefaultCLIPath,
		InstanceType: PhalaConfigDefaultInstanceType,
		WorkRoot:     PhalaConfigDefaultWorkRoot,
	}
}

// PhalaConfigApplied records accepted assignments during one application.
type PhalaConfigApplied struct {
	InputAccepted bool
	CLIPath       bool
	InstanceType  bool
	Compose       bool
}

func (cfg *PhalaConfig) applyFile(file *filePhalaConfig, trusted bool) (PhalaConfigApplied, error) {
	var applied PhalaConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "phala")
	return applied, err
}

func (cfg *PhalaConfig) applyEnv() (PhalaConfigApplied, error) {
	var applied PhalaConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// PhalaConfigFlagValues holds parsed values; only visited flags are applied.
type PhalaConfigFlagValues struct {
	CLIPath      *string
	InstanceType *string
	WorkRoot     *string
	NodeID       *string
	Compose      *string
	Attest       *bool
}

// RegisterPhalaConfigFlags registers mechanical bindings without selecting a provider.
func RegisterPhalaConfigFlags(fs *flag.FlagSet, defaults PhalaConfig) PhalaConfigFlagValues {
	return PhalaConfigFlagValues{
		CLIPath:      fs.String("phala-cli", defaults.CLIPath, "Phala CLI path"),
		InstanceType: fs.String("phala-instance-type", defaults.InstanceType, "Phala confidential TDX instance type, for example tdx.small"),
		WorkRoot:     fs.String("phala-work-root", defaults.WorkRoot, "remote Crabbox work root"),
		NodeID:       fs.String("phala-node-id", defaults.NodeID, "Phala node id to pin deployments to"),
		Compose:      fs.String("phala-compose", defaults.Compose, "optional Docker Compose file deployed alongside the dev OS"),
		Attest:       fs.Bool("phala-attest", defaults.Attest != nil && *defaults.Attest, "verify the leased CVM's Intel TDX remote attestation before trusting it (default true)"),
	}
}

// PhalaConfigVisitedFlags records raw flag visits, independently of application.
type PhalaConfigVisitedFlags struct {
	CLIPath      bool
	InstanceType bool
	WorkRoot     bool
	NodeID       bool
	Compose      bool
	Attest       bool
}

// PhalaConfigFlagPresence reports visits for tracked flag bindings.
func PhalaConfigFlagPresence(fs *flag.FlagSet) PhalaConfigVisitedFlags {
	return PhalaConfigVisitedFlags{
		CLIPath:      flagWasSet(fs, "phala-cli"),
		InstanceType: flagWasSet(fs, "phala-instance-type"),
		WorkRoot:     flagWasSet(fs, "phala-work-root"),
		NodeID:       flagWasSet(fs, "phala-node-id"),
		Compose:      flagWasSet(fs, "phala-compose"),
		Attest:       flagWasSet(fs, "phala-attest"),
	}
}
