// Code generated by scripts/configgen from config_vercel_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
	"strings"
)

type fileVercelSandboxConfig struct {
	Runtime         *string   `yaml:"runtime,omitempty"`
	Workdir         *string   `yaml:"workdir,omitempty"`
	ProjectID       *string   `yaml:"projectId,omitempty"`
	TeamID          *string   `yaml:"teamId,omitempty"`
	Scope           *string   `yaml:"scope,omitempty"`
	VCPUs           *float64  `yaml:"vcpus,omitempty"`
	TimeoutSecs     *int      `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int      `yaml:"execTimeoutSecs,omitempty"`
	Persistent      *bool     `yaml:"persistent,omitempty"`
	Snapshot        *string   `yaml:"snapshot,omitempty"`
	SnapshotMode    *string   `yaml:"snapshotMode,omitempty"`
	NetworkPolicy   *string   `yaml:"networkPolicy,omitempty"`
	NetworkAllow    *[]string `yaml:"networkAllow,omitempty"`
	NetworkDeny     *[]string `yaml:"networkDeny,omitempty"`
	Ports           *[]string `yaml:"ports,omitempty"`
	ForgetMissing   *bool     `yaml:"forgetMissing,omitempty"`
}

const VercelSandboxConfigDefaultRuntime string = "node24"
const VercelSandboxConfigDefaultWorkdir string = "/vercel/sandbox/crabbox"
const VercelSandboxConfigDefaultExecTimeoutSecs int = 600
const VercelSandboxConfigDefaultNetworkPolicy string = "default"

func defaultVercelSandboxConfig() VercelSandboxConfig {
	return VercelSandboxConfig{
		Runtime:         VercelSandboxConfigDefaultRuntime,
		Workdir:         VercelSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: VercelSandboxConfigDefaultExecTimeoutSecs,
		NetworkPolicy:   VercelSandboxConfigDefaultNetworkPolicy,
	}
}

// VercelSandboxConfigApplied records accepted assignments during one application.
type VercelSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *VercelSandboxConfig) applyFile(file *fileVercelSandboxConfig) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "vercel-sandbox")
	return applied, err
}

func (cfg *VercelSandboxConfig) applyEnv() (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 16)
	return applied, err
}

// VercelSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type VercelSandboxConfigFlagValues struct {
	Runtime         *string
	Workdir         *string
	ProjectID       *string
	TeamID          *string
	Scope           *string
	VCPUs           *float64
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Persistent      *bool
	Snapshot        *string
	SnapshotMode    *string
	NetworkPolicy   *string
	NetworkAllow    *string
	NetworkDeny     *string
	Ports           *string
	ForgetMissing   *bool
}

// RegisterVercelSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVercelSandboxConfigFlags(fs *flag.FlagSet, defaults VercelSandboxConfig) VercelSandboxConfigFlagValues {
	return VercelSandboxConfigFlagValues{
		Runtime:         fs.String("vercel-sandbox-runtime", defaults.Runtime, "Vercel Sandbox runtime (node26, node24, node22, python3.13)"),
		Workdir:         fs.String("vercel-sandbox-workdir", defaults.Workdir, "Absolute working directory inside the sandbox"),
		ProjectID:       fs.String("vercel-sandbox-project-id", defaults.ProjectID, "Vercel project ID used for sandbox scoping"),
		TeamID:          fs.String("vercel-sandbox-team-id", defaults.TeamID, "Vercel team ID used for sandbox scoping"),
		Scope:           fs.String("vercel-sandbox-scope", defaults.Scope, "Vercel account or team slug used for sandbox scoping"),
		VCPUs:           fs.Float64("vercel-sandbox-vcpus", defaults.VCPUs, "requested Vercel Sandbox vCPU count (0 = service default)"),
		TimeoutSecs:     fs.Int("vercel-sandbox-timeout-secs", defaults.TimeoutSecs, "sandbox lifetime cap in seconds (0 = service default)"),
		ExecTimeoutSecs: fs.Int("vercel-sandbox-exec-timeout-secs", defaults.ExecTimeoutSecs, "command timeout in seconds (0 = service default)"),
		Persistent:      fs.Bool("vercel-sandbox-persistent", defaults.Persistent, "request a persistent sandbox when lifecycle support lands"),
		Snapshot:        fs.String("vercel-sandbox-snapshot", defaults.Snapshot, "snapshot/checkpoint name or ID for future lifecycle use"),
		SnapshotMode:    fs.String("vercel-sandbox-snapshot-mode", defaults.SnapshotMode, "snapshot/checkpoint mode for future lifecycle use"),
		NetworkPolicy:   fs.String("vercel-sandbox-network-policy", defaults.NetworkPolicy, "sandbox network policy: default, public, private, restricted, or none"),
		NetworkAllow:    fs.String("vercel-sandbox-network-allow", strings.Join(defaults.NetworkAllow, ","), "comma-separated outbound CIDR/domain allow list"),
		NetworkDeny:     fs.String("vercel-sandbox-network-deny", strings.Join(defaults.NetworkDeny, ","), "comma-separated outbound IP/CIDR deny list"),
		Ports:           fs.String("vercel-sandbox-ports", strings.Join(defaults.Ports, ","), "comma-separated ports or ranges to expose later"),
		ForgetMissing:   fs.Bool("vercel-sandbox-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VercelSandboxConfigFlagValues) Apply(cfg *VercelSandboxConfig, fs *flag.FlagSet) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	if flagWasSet(fs, "vercel-sandbox-runtime") {
		cfg.Runtime = *values.Runtime
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-project-id") {
		cfg.ProjectID = *values.ProjectID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-team-id") {
		cfg.TeamID = *values.TeamID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-scope") {
		cfg.Scope = *values.Scope
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-vcpus") {
		cfg.VCPUs = *values.VCPUs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-persistent") {
		cfg.Persistent = *values.Persistent
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot") {
		cfg.Snapshot = *values.Snapshot
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot-mode") {
		cfg.SnapshotMode = *values.SnapshotMode
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-policy") {
		cfg.NetworkPolicy = *values.NetworkPolicy
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-allow") {
		cfg.NetworkAllow = splitCommaList(*values.NetworkAllow)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-network-deny") {
		cfg.NetworkDeny = splitCommaList(*values.NetworkDeny)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-ports") {
		cfg.Ports = splitCommaList(*values.Ports)
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vercel-sandbox-forget-missing") {
		cfg.ForgetMissing = *values.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}
