// Code generated by scripts/configgen from config_multipass.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileMultipassConfig struct {
	CLIPath       string `yaml:"cliPath,omitempty"`
	Image         string `yaml:"image,omitempty"`
	User          string `yaml:"user,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
	CPUs          int    `yaml:"cpus,omitempty"`
	Memory        string `yaml:"memory,omitempty"`
	Disk          string `yaml:"disk,omitempty"`
	LaunchTimeout string `yaml:"launchTimeout,omitempty"`
}

const MultipassConfigDefaultCLIPath string = "multipass"
const MultipassConfigDefaultUser string = "crabbox"
const MultipassConfigDefaultCPUs int = 4
const MultipassConfigDefaultMemory string = "8G"
const MultipassConfigDefaultDisk string = "30G"
const MultipassConfigDefaultLaunchTimeout time.Duration = 1200 * time.Second

func defaultMultipassConfig() MultipassConfig {
	return MultipassConfig{
		CLIPath:       MultipassConfigDefaultCLIPath,
		User:          MultipassConfigDefaultUser,
		CPUs:          MultipassConfigDefaultCPUs,
		Memory:        MultipassConfigDefaultMemory,
		Disk:          MultipassConfigDefaultDisk,
		LaunchTimeout: MultipassConfigDefaultLaunchTimeout,
	}
}

// MultipassConfigApplied records accepted assignments during one application.
type MultipassConfigApplied struct {
	InputAccepted bool
	Image         bool
	User          bool
	WorkRoot      bool
}

func (cfg *MultipassConfig) applyFile(file *fileMultipassConfig) (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "multipass")
	return applied, err
}

func (cfg *MultipassConfig) applyEnv() (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// MultipassConfigFlagValues holds parsed values; only visited flags are applied.
type MultipassConfigFlagValues struct {
	CLIPath       *string
	Image         *string
	User          *string
	WorkRoot      *string
	CPUs          *int
	Memory        *string
	Disk          *string
	LaunchTimeout *string
}

// RegisterMultipassConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMultipassConfigFlags(fs *flag.FlagSet, defaults MultipassConfig) MultipassConfigFlagValues {
	return MultipassConfigFlagValues{
		CLIPath:       fs.String("multipass-cli", defaults.CLIPath, "Multipass CLI path"),
		Image:         fs.String("multipass-image", defaults.Image, "Multipass Ubuntu image selector"),
		User:          fs.String("multipass-user", defaults.User, "SSH user created inside Multipass leases"),
		WorkRoot:      fs.String("multipass-work-root", defaults.WorkRoot, "remote Crabbox work root inside Multipass leases"),
		CPUs:          fs.Int("multipass-cpus", defaults.CPUs, "CPU count for Multipass leases; 0 leaves Multipass default"),
		Memory:        fs.String("multipass-memory", defaults.Memory, "memory size for Multipass leases, for example 8G"),
		Disk:          fs.String("multipass-disk", defaults.Disk, "disk size for Multipass leases, for example 30G"),
		LaunchTimeout: fs.String("multipass-launch-timeout", defaults.LaunchTimeout.String(), "Multipass launch timeout"),
	}
}

// MultipassConfigVisitedFlags records raw flag visits, independently of application.
type MultipassConfigVisitedFlags struct {
	Image    bool
	User     bool
	WorkRoot bool
}

// MultipassConfigFlagPresence reports visits for tracked flag bindings.
func MultipassConfigFlagPresence(fs *flag.FlagSet) MultipassConfigVisitedFlags {
	return MultipassConfigVisitedFlags{
		Image:    flagWasSet(fs, "multipass-image"),
		User:     flagWasSet(fs, "multipass-user"),
		WorkRoot: flagWasSet(fs, "multipass-work-root"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values MultipassConfigFlagValues) Apply(cfg *MultipassConfig, fs *flag.FlagSet) (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	visited := MultipassConfigFlagPresence(fs)
	if flagWasSet(fs, "multipass-cli") {
		cfg.CLIPath = *values.CLIPath
		applied.InputAccepted = true
	}
	if visited.Image {
		cfg.Image = *values.Image
		applied.InputAccepted = true
		applied.Image = true
	}
	if visited.User {
		cfg.User = *values.User
		applied.InputAccepted = true
		applied.User = true
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if flagWasSet(fs, "multipass-cpus") {
		cfg.CPUs = *values.CPUs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "multipass-memory") {
		cfg.Memory = *values.Memory
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "multipass-disk") {
		cfg.Disk = *values.Disk
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "multipass-launch-timeout") {
		if err := ApplyLeaseDuration(&cfg.LaunchTimeout, *values.LaunchTimeout); err != nil {
			return applied, err
		} else if *values.LaunchTimeout != "" {
			applied.InputAccepted = true
		}
	}
	return applied, nil
}
