// Code generated by scripts/configgen from config_cua.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCuaConfig struct {
	Image              *string `yaml:"image,omitempty"`
	Kind               *string `yaml:"kind,omitempty"`
	Region             *string `yaml:"region,omitempty"`
	Workdir            *string `yaml:"workdir,omitempty"`
	VCPUs              *int    `yaml:"vcpus,omitempty"`
	MemoryMB           *int    `yaml:"memoryMB,omitempty"`
	DiskGB             *int    `yaml:"diskGB,omitempty"`
	StartupTimeoutSecs *int    `yaml:"startupTimeoutSecs,omitempty"`
	ExecTimeoutSecs    *int    `yaml:"execTimeoutSecs,omitempty"`
	BridgeCommand      *string `yaml:"bridgeCommand,omitempty"`
	SDKPackage         *string `yaml:"sdkPackage,omitempty"`
	SDKImport          *string `yaml:"sdkImport,omitempty"`
	SDKFallbackImport  *string `yaml:"sdkFallbackImport,omitempty"`
}

const CuaConfigDefaultImage string = "ubuntu:24.04"
const CuaConfigDefaultKind string = "container"
const CuaConfigDefaultWorkdir string = "/workspace/crabbox"
const CuaConfigDefaultExecTimeoutSecs int = 600
const CuaConfigDefaultBridgeCommand string = "python3"
const CuaConfigDefaultSDKPackage string = "cua"
const CuaConfigDefaultSDKImport string = "cua"
const CuaConfigDefaultSDKFallbackImport string = "cua_sandbox"

func defaultCuaConfig() CuaConfig {
	return CuaConfig{
		Image:             CuaConfigDefaultImage,
		Kind:              CuaConfigDefaultKind,
		Workdir:           CuaConfigDefaultWorkdir,
		ExecTimeoutSecs:   CuaConfigDefaultExecTimeoutSecs,
		BridgeCommand:     CuaConfigDefaultBridgeCommand,
		SDKPackage:        CuaConfigDefaultSDKPackage,
		SDKImport:         CuaConfigDefaultSDKImport,
		SDKFallbackImport: CuaConfigDefaultSDKFallbackImport,
	}
}

// CuaConfigApplied records accepted assignments during one application.
type CuaConfigApplied struct {
	InputAccepted bool
}

func (cfg *CuaConfig) applyFile(file *fileCuaConfig, trusted bool) (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Image != nil {
		cfg.Image = *file.Image
		applied.InputAccepted = true
	}
	if file.Kind != nil {
		cfg.Kind = *file.Kind
		applied.InputAccepted = true
	}
	if file.Region != nil {
		cfg.Region = *file.Region
		applied.InputAccepted = true
	}
	if file.Workdir != nil {
		cfg.Workdir = *file.Workdir
		applied.InputAccepted = true
	}
	if file.VCPUs != nil {
		if *file.VCPUs < 0 {
			return applied, exit(2, "cua vcpus must be non-negative")
		}
		cfg.VCPUs = *file.VCPUs
		applied.InputAccepted = true
	}
	if file.MemoryMB != nil {
		if *file.MemoryMB < 0 {
			return applied, exit(2, "cua memoryMB must be non-negative")
		}
		cfg.MemoryMB = *file.MemoryMB
		applied.InputAccepted = true
	}
	if file.DiskGB != nil {
		if *file.DiskGB < 0 {
			return applied, exit(2, "cua diskGB must be non-negative")
		}
		cfg.DiskGB = *file.DiskGB
		applied.InputAccepted = true
	}
	if file.StartupTimeoutSecs != nil {
		if *file.StartupTimeoutSecs < 0 {
			return applied, exit(2, "cua startupTimeoutSecs must be non-negative")
		}
		cfg.StartupTimeoutSecs = *file.StartupTimeoutSecs
		applied.InputAccepted = true
	}
	if file.ExecTimeoutSecs != nil {
		if *file.ExecTimeoutSecs < 0 {
			return applied, exit(2, "cua execTimeoutSecs must be non-negative")
		}
		cfg.ExecTimeoutSecs = *file.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if trusted && file.BridgeCommand != nil {
		cfg.BridgeCommand = *file.BridgeCommand
		applied.InputAccepted = true
	}
	if trusted && file.SDKPackage != nil {
		cfg.SDKPackage = *file.SDKPackage
		applied.InputAccepted = true
	}
	if trusted && file.SDKImport != nil {
		cfg.SDKImport = *file.SDKImport
		applied.InputAccepted = true
	}
	if trusted && file.SDKFallbackImport != nil {
		cfg.SDKFallbackImport = *file.SDKFallbackImport
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *CuaConfig) applyEnv() (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_API_URL", "CUA_BASE_URL"); ok {
		cfg.APIURL = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_IMAGE"); ok {
		cfg.Image = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_KIND"); ok {
		cfg.Kind = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_REGION"); ok {
		cfg.Region = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_WORKDIR"); ok {
		cfg.Workdir = value
		applied.InputAccepted = true
	}
	{
		var accepted bool
		var err error
		cfg.VCPUs, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_CUA_VCPUS", cfg.VCPUs)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	{
		var accepted bool
		var err error
		cfg.MemoryMB, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_CUA_MEMORY_MB", cfg.MemoryMB)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	{
		var accepted bool
		var err error
		cfg.DiskGB, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_CUA_DISK_GB", cfg.DiskGB)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	{
		var accepted bool
		var err error
		cfg.StartupTimeoutSecs, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_CUA_STARTUP_TIMEOUT_SECS", cfg.StartupTimeoutSecs)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	{
		var accepted bool
		var err error
		cfg.ExecTimeoutSecs, accepted, err = getenvNonNegativeIntAccepted("CRABBOX_CUA_EXEC_TIMEOUT_SECS", cfg.ExecTimeoutSecs)
		if err != nil {
			return applied, err
		}
		if accepted {
			applied.InputAccepted = true
		}
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_BRIDGE_COMMAND"); ok {
		cfg.BridgeCommand = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_SDK_PACKAGE"); ok {
		cfg.SDKPackage = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_SDK_IMPORT"); ok {
		cfg.SDKImport = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CUA_SDK_FALLBACK_IMPORT"); ok {
		cfg.SDKFallbackImport = value
		applied.InputAccepted = true
	}
	return applied, nil
}

// CuaConfigFlagValues holds parsed values; only visited flags are applied.
type CuaConfigFlagValues struct {
	APIURL             *string
	Image              *string
	Kind               *string
	Region             *string
	Workdir            *string
	VCPUs              *int
	MemoryMB           *int
	DiskGB             *int
	StartupTimeoutSecs *int
	ExecTimeoutSecs    *int
	BridgeCommand      *string
	SDKPackage         *string
	SDKImport          *string
	SDKFallbackImport  *string
}

// RegisterCuaConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCuaConfigFlags(fs *flag.FlagSet, defaults CuaConfig) CuaConfigFlagValues {
	return CuaConfigFlagValues{
		APIURL:             fs.String("cua-api-url", defaults.APIURL, "Trusted CUA API base URL; not accepted from repository config"),
		Image:              fs.String("cua-image", defaults.Image, "CUA Linux sandbox image"),
		Kind:               fs.String("cua-kind", defaults.Kind, "CUA sandbox kind: container or vm"),
		Region:             fs.String("cua-region", defaults.Region, "CUA deployment region (empty = service default/policy)"),
		Workdir:            fs.String("cua-workdir", defaults.Workdir, "Absolute working directory inside the sandbox"),
		VCPUs:              fs.Int("cua-vcpus", defaults.VCPUs, "CUA sandbox vCPU count (0 = service default)"),
		MemoryMB:           fs.Int("cua-memory-mb", defaults.MemoryMB, "CUA sandbox memory in MB (0 = service default)"),
		DiskGB:             fs.Int("cua-disk-gb", defaults.DiskGB, "CUA sandbox disk in GB (0 = service default)"),
		StartupTimeoutSecs: fs.Int("cua-startup-timeout-secs", defaults.StartupTimeoutSecs, "CUA sandbox startup timeout in seconds (0 = Crabbox default)"),
		ExecTimeoutSecs:    fs.Int("cua-exec-timeout-secs", defaults.ExecTimeoutSecs, "CUA command timeout in seconds (0 = Crabbox default 600)"),
		BridgeCommand:      fs.String("cua-bridge-command", defaults.BridgeCommand, "trusted local Python command for the future CUA SDK bridge"),
		SDKPackage:         fs.String("cua-sdk-package", defaults.SDKPackage, "trusted local Python package name for CUA SDK diagnostics"),
		SDKImport:          fs.String("cua-sdk-import", defaults.SDKImport, "trusted local Python import path for CUA SDK diagnostics"),
		SDKFallbackImport:  fs.String("cua-sdk-fallback-import", defaults.SDKFallbackImport, "trusted local fallback import path for CUA SDK diagnostics"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CuaConfigFlagValues) Apply(cfg *CuaConfig, fs *flag.FlagSet) (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	if flagWasSet(fs, "cua-api-url") {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-kind") {
		cfg.Kind = *values.Kind
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-region") {
		cfg.Region = *values.Region
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-vcpus") {
		cfg.VCPUs = *values.VCPUs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-memory-mb") {
		cfg.MemoryMB = *values.MemoryMB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-disk-gb") {
		cfg.DiskGB = *values.DiskGB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-startup-timeout-secs") {
		cfg.StartupTimeoutSecs = *values.StartupTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-bridge-command") {
		cfg.BridgeCommand = *values.BridgeCommand
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-sdk-package") {
		cfg.SDKPackage = *values.SDKPackage
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-sdk-import") {
		cfg.SDKImport = *values.SDKImport
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cua-sdk-fallback-import") {
		cfg.SDKFallbackImport = *values.SDKFallbackImport
		applied.InputAccepted = true
	}
	return applied, nil
}
