// Code generated by scripts/configgen from config_digitalocean.go; DO NOT EDIT.

package cli

type fileDigitalOceanConfig struct {
	Region   string   `yaml:"region,omitempty"`
	Image    string   `yaml:"image,omitempty"`
	VPCUUID  string   `yaml:"vpc,omitempty"`
	SSHCIDRs []string `yaml:"sshCIDRs,omitempty"`
}

func defaultDigitalOceanConfig() DigitalOceanConfig {
	return DigitalOceanConfig{}
}

// DigitalOceanConfigApplied records accepted assignments during one application.
type DigitalOceanConfigApplied struct {
	InputAccepted bool
	Image         bool
}

func (cfg *DigitalOceanConfig) applyFile(file *fileDigitalOceanConfig) (DigitalOceanConfigApplied, error) {
	var applied DigitalOceanConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Region != "" {
		cfg.Region = file.Region
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
		applied.Image = true
	}
	if file.VPCUUID != "" {
		cfg.VPCUUID = file.VPCUUID
		applied.InputAccepted = true
	}
	if len(file.SSHCIDRs) > 0 {
		cfg.SSHCIDRs = file.SSHCIDRs
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *DigitalOceanConfig) applyEnv() (DigitalOceanConfigApplied, error) {
	var applied DigitalOceanConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 4)
	return applied, err
}
