// Code generated by scripts/configgen from config_tencentcloud.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTencentCloudConfig struct {
	Region                  string   `yaml:"region,omitempty"`
	Zone                    string   `yaml:"zone,omitempty"`
	Image                   string   `yaml:"image,omitempty"`
	Type                    string   `yaml:"type,omitempty"`
	VPCID                   string   `yaml:"vpcId,omitempty"`
	SubnetID                string   `yaml:"subnetId,omitempty"`
	SecurityGroupID         string   `yaml:"securityGroupId,omitempty"`
	SSHCIDRs                []string `yaml:"sshCIDRs,omitempty"`
	RootGB                  int64    `yaml:"rootGB,omitempty"`
	InternetChargeType      string   `yaml:"internetChargeType,omitempty"`
	InternetMaxBandwidthOut int64    `yaml:"internetMaxBandwidthOut,omitempty"`
	APIEndpoint             string   `yaml:"apiEndpoint,omitempty"`
}

func defaultTencentCloudConfig() TencentCloudConfig {
	return TencentCloudConfig{}
}

// TencentCloudConfigApplied records accepted assignments during one application.
type TencentCloudConfigApplied struct {
	InputAccepted bool
	Region        bool
	Zone          bool
	Image         bool
	Type          bool
}

func (cfg *TencentCloudConfig) applyFile(file *fileTencentCloudConfig, trusted bool) (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "tencentcloud")
	return applied, err
}

func (cfg *TencentCloudConfig) applyEnv() (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// TencentCloudConfigFlagValues holds parsed values; only visited flags are applied.
type TencentCloudConfigFlagValues struct {
	Region                  *string
	Zone                    *string
	Image                   *string
	Type                    *string
	VPCID                   *string
	SubnetID                *string
	SecurityGroupID         *string
	SSHCIDRs                *string
	RootGB                  *int64
	InternetChargeType      *string
	InternetMaxBandwidthOut *int64
	APIEndpoint             *string
}

// RegisterTencentCloudConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTencentCloudConfigFlags(fs *flag.FlagSet, defaults TencentCloudConfig) TencentCloudConfigFlagValues {
	return TencentCloudConfigFlagValues{
		Region:                  fs.String("tencentcloud-region", defaults.Region, "Tencent Cloud CVM region"),
		Zone:                    fs.String("tencentcloud-zone", defaults.Zone, "Tencent Cloud CVM availability zone"),
		Image:                   fs.String("tencentcloud-image", defaults.Image, "Tencent Cloud CVM image ID"),
		Type:                    fs.String("tencentcloud-type", defaults.Type, "Tencent Cloud CVM instance type"),
		VPCID:                   fs.String("tencentcloud-vpc-id", defaults.VPCID, "Tencent Cloud VPC ID"),
		SubnetID:                fs.String("tencentcloud-subnet-id", defaults.SubnetID, "Tencent Cloud subnet ID"),
		SecurityGroupID:         fs.String("tencentcloud-security-group-id", defaults.SecurityGroupID, "Tencent Cloud security group ID"),
		SSHCIDRs:                fs.String("tencentcloud-ssh-cidrs", "", "comma-separated Tencent Cloud SSH source CIDRs; reserved for managed security-group support"),
		RootGB:                  fs.Int64("tencentcloud-root-gb", defaults.RootGB, "Tencent Cloud CVM system disk size in GiB"),
		InternetChargeType:      fs.String("tencentcloud-internet-charge-type", defaults.InternetChargeType, "Tencent Cloud public bandwidth charge type"),
		InternetMaxBandwidthOut: fs.Int64("tencentcloud-internet-max-bandwidth-out", defaults.InternetMaxBandwidthOut, "Tencent Cloud public outbound bandwidth in Mbps"),
		APIEndpoint:             fs.String("tencentcloud-api-endpoint", defaults.APIEndpoint, "Tencent Cloud CVM API endpoint"),
	}
}

// TencentCloudConfigVisitedFlags records raw flag visits, independently of application.
type TencentCloudConfigVisitedFlags struct {
	Region bool
	Zone   bool
	Image  bool
	Type   bool
}

// TencentCloudConfigFlagPresence reports visits for tracked flag bindings.
func TencentCloudConfigFlagPresence(fs *flag.FlagSet) TencentCloudConfigVisitedFlags {
	return TencentCloudConfigVisitedFlags{
		Region: flagWasSet(fs, "tencentcloud-region"),
		Zone:   flagWasSet(fs, "tencentcloud-zone"),
		Image:  flagWasSet(fs, "tencentcloud-image"),
		Type:   flagWasSet(fs, "tencentcloud-type"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TencentCloudConfigFlagValues) Apply(cfg *TencentCloudConfig, fs *flag.FlagSet) (TencentCloudConfigApplied, error) {
	var applied TencentCloudConfigApplied
	visited := TencentCloudConfigFlagPresence(fs)
	if visited.Region {
		cfg.Region = *values.Region
		applied.InputAccepted = true
		applied.Region = true
	}
	if visited.Zone {
		cfg.Zone = *values.Zone
		applied.InputAccepted = true
		applied.Zone = true
	}
	if visited.Image {
		cfg.Image = *values.Image
		applied.InputAccepted = true
		applied.Image = true
	}
	if visited.Type {
		cfg.Type = *values.Type
		applied.InputAccepted = true
		applied.Type = true
	}
	if flagWasSet(fs, "tencentcloud-vpc-id") {
		cfg.VPCID = *values.VPCID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-subnet-id") {
		cfg.SubnetID = *values.SubnetID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-security-group-id") {
		cfg.SecurityGroupID = *values.SecurityGroupID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-ssh-cidrs") {
		cfg.SSHCIDRs = splitCommaList(*values.SSHCIDRs)
		if len(cfg.SSHCIDRs) == 0 {
			cfg.SSHCIDRs = nil
		}
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-root-gb") {
		cfg.RootGB = *values.RootGB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-internet-charge-type") {
		cfg.InternetChargeType = *values.InternetChargeType
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-internet-max-bandwidth-out") {
		cfg.InternetMaxBandwidthOut = *values.InternetMaxBandwidthOut
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tencentcloud-api-endpoint") {
		cfg.APIEndpoint = *values.APIEndpoint
		applied.InputAccepted = true
	}
	return applied, nil
}
