// Code generated by scripts/configgen from config_crownest.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCrownestConfig struct {
	APIURL        string  `yaml:"apiUrl,omitempty"`
	ProjectID     *string `yaml:"projectId,omitempty"`
	Template      *string `yaml:"template,omitempty"`
	TimeoutSecs   *int    `yaml:"timeoutSecs,omitempty"`
	ForgetMissing *bool   `yaml:"forgetMissing,omitempty"`
}

const CrownestConfigDefaultAPIURL string = "https://api.crownest.dev"
const CrownestConfigDefaultTemplate string = "python-node"
const CrownestConfigDefaultTimeoutSecs int = 600

func defaultCrownestConfig() CrownestConfig {
	return CrownestConfig{
		APIURL:      CrownestConfigDefaultAPIURL,
		Template:    CrownestConfigDefaultTemplate,
		TimeoutSecs: CrownestConfigDefaultTimeoutSecs,
	}
}

// CrownestConfigApplied records accepted assignments during one application.
type CrownestConfigApplied struct {
	InputAccepted bool
}

func (cfg *CrownestConfig) applyFile(file *fileCrownestConfig, trusted bool) (CrownestConfigApplied, error) {
	var applied CrownestConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "crownest")
	return applied, err
}

func (cfg *CrownestConfig) applyEnv() (CrownestConfigApplied, error) {
	var applied CrownestConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// CrownestConfigFlagValues holds parsed values; only visited flags are applied.
type CrownestConfigFlagValues struct {
	APIURL        *string
	ProjectID     *string
	Template      *string
	TimeoutSecs   *int
	ForgetMissing *bool
}

// RegisterCrownestConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCrownestConfigFlags(fs *flag.FlagSet, defaults CrownestConfig) CrownestConfigFlagValues {
	return CrownestConfigFlagValues{
		APIURL:        fs.String("crownest-url", defaults.APIURL, "Trusted CrowNest API base URL"),
		ProjectID:     fs.String("crownest-project-id", defaults.ProjectID, "CrowNest project ID"),
		Template:      fs.String("crownest-template", defaults.Template, "CrowNest Workspace Run template"),
		TimeoutSecs:   fs.Int("crownest-timeout-secs", defaults.TimeoutSecs, "CrowNest Workspace Run timeout in seconds"),
		ForgetMissing: fs.Bool("crownest-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CrownestConfigFlagValues) Apply(cfg *CrownestConfig, fs *flag.FlagSet) (CrownestConfigApplied, error) {
	var applied CrownestConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
