// Code generated by scripts/configgen from config_modal.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileModalConfig struct {
	App         string    `yaml:"app,omitempty"`
	Image       string    `yaml:"image,omitempty"`
	Workdir     string    `yaml:"workdir,omitempty"`
	Python      string    `yaml:"python,omitempty"`
	Environment string    `yaml:"environment,omitempty"`
	Secrets     *[]string `yaml:"secrets,omitempty"`
}

const ModalConfigDefaultApp string = "crabbox"
const ModalConfigDefaultImage string = "python:3.13-slim"
const ModalConfigDefaultWorkdir string = "/workspace/crabbox"
const ModalConfigDefaultPython string = "python3"

func defaultModalConfig() ModalConfig {
	return ModalConfig{
		App:     ModalConfigDefaultApp,
		Image:   ModalConfigDefaultImage,
		Workdir: ModalConfigDefaultWorkdir,
		Python:  ModalConfigDefaultPython,
	}
}

// ModalConfigApplied records accepted assignments during one application.
type ModalConfigApplied struct {
	InputAccepted bool
}

func (cfg *ModalConfig) applyFile(file *fileModalConfig, trusted bool) (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.App != "" {
		cfg.App = file.App
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
		applied.InputAccepted = true
	}
	if file.Python != "" {
		cfg.Python = file.Python
		applied.InputAccepted = true
	}
	if trusted && file.Environment != "" {
		cfg.Environment = file.Environment
		applied.InputAccepted = true
	}
	if trusted && file.Secrets != nil {
		cfg.Secrets = append([]string(nil), (*file.Secrets)...)
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *ModalConfig) applyEnv() (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// ModalConfigFlagValues holds parsed values; only visited flags are applied.
type ModalConfigFlagValues struct {
	App         *string
	Image       *string
	Workdir     *string
	Python      *string
	Environment *string
	Secrets     *replaceAppendListFlag
}

// RegisterModalConfigFlags registers mechanical bindings without selecting a provider.
func RegisterModalConfigFlags(fs *flag.FlagSet, defaults ModalConfig) ModalConfigFlagValues {
	listSecrets := newReplaceAppendListFlag(defaults.Secrets)
	fs.Var(listSecrets, "modal-secret", "named Modal Secret to inject into the sandbox; repeatable or comma-separated")
	return ModalConfigFlagValues{
		App:         fs.String("modal-app", defaults.App, "Modal app name for Crabbox sandboxes"),
		Image:       fs.String("modal-image", defaults.Image, "Modal sandbox image, as a registry reference"),
		Workdir:     fs.String("modal-workdir", defaults.Workdir, "Absolute working directory inside the Modal sandbox"),
		Python:      fs.String("modal-python", defaults.Python, "Python binary used to run the local Modal client"),
		Environment: fs.String("modal-environment", defaults.Environment, "Modal environment for the sandbox and named Secrets"),
		Secrets:     listSecrets,
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ModalConfigFlagValues) Apply(cfg *ModalConfig, fs *flag.FlagSet) (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	if flagWasSet(fs, "modal-app") {
		cfg.App = *values.App
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "modal-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "modal-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "modal-python") {
		cfg.Python = *values.Python
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "modal-environment") {
		cfg.Environment = *values.Environment
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "modal-secret") {
		cfg.Secrets = append([]string(nil), values.Secrets.values...)
		applied.InputAccepted = true
	}
	return applied, nil
}
