// Code generated by scripts/configgen from config_cloud_run_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudRunSandboxConfig struct {
	CLIPath     string `yaml:"cliPath,omitempty"`
	Workdir     string `yaml:"workdir,omitempty"`
	AllowEgress *bool  `yaml:"allowEgress,omitempty"`
	Write       *bool  `yaml:"write,omitempty"`
	Rootfs      string `yaml:"rootfs,omitempty"`
}

const CloudRunSandboxConfigDefaultCLIPath string = "/usr/local/gcp/bin/sandbox"
const CloudRunSandboxConfigDefaultWorkdir string = "/tmp/crabbox"
const CloudRunSandboxConfigDefaultWrite bool = true
const CloudRunSandboxConfigDefaultRootfs string = "/"

func defaultCloudRunSandboxConfig() CloudRunSandboxConfig {
	return CloudRunSandboxConfig{
		CLIPath: CloudRunSandboxConfigDefaultCLIPath,
		Workdir: CloudRunSandboxConfigDefaultWorkdir,
		Write:   CloudRunSandboxConfigDefaultWrite,
		Rootfs:  CloudRunSandboxConfigDefaultRootfs,
	}
}

// CloudRunSandboxConfigApplied records accepted assignments during one application.
type CloudRunSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *CloudRunSandboxConfig) applyFile(file *fileCloudRunSandboxConfig) (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "cloud-run-sandbox")
	return applied, err
}

func (cfg *CloudRunSandboxConfig) applyEnv() (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// CloudRunSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type CloudRunSandboxConfigFlagValues struct {
	GatewayURL  *string
	CLIPath     *string
	Workdir     *string
	AllowEgress *bool
	Write       *bool
	Rootfs      *string
}

// RegisterCloudRunSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudRunSandboxConfigFlags(fs *flag.FlagSet, defaults CloudRunSandboxConfig) CloudRunSandboxConfigFlagValues {
	return CloudRunSandboxConfigFlagValues{
		GatewayURL:  fs.String("cloud-run-sandbox-gateway-url", defaults.GatewayURL, "durable-routing Cloud Run sandbox gateway URL (HTTPS)"),
		CLIPath:     fs.String("cloud-run-sandbox-cli", defaults.CLIPath, "path to the Cloud Run sandbox CLI binary (direct mode)"),
		Workdir:     fs.String("cloud-run-sandbox-workdir", defaults.Workdir, "absolute working directory inside the sandbox (sync target)"),
		AllowEgress: fs.Bool("cloud-run-sandbox-allow-egress", defaults.AllowEgress, "allow outbound network access from the sandbox (default deny)"),
		Write:       fs.Bool("cloud-run-sandbox-write", defaults.Write, "allow writable mounted filesystems inside the sandbox"),
		Rootfs:      fs.String("cloud-run-sandbox-rootfs", defaults.Rootfs, "root filesystem exposed to the sandbox (default /)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudRunSandboxConfigFlagValues) Apply(cfg *CloudRunSandboxConfig, fs *flag.FlagSet) (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
