// Code generated by scripts/configgen from config_incus.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
	"time"
)

type fileIncusConfig struct {
	Remote            string `yaml:"remote,omitempty"`
	Project           string `yaml:"project,omitempty"`
	Address           string `yaml:"address,omitempty"`
	Socket            string `yaml:"socket,omitempty"`
	InstanceType      string `yaml:"instanceType,omitempty"`
	Image             string `yaml:"image,omitempty"`
	Profile           string `yaml:"profile,omitempty"`
	User              string `yaml:"user,omitempty"`
	WorkRoot          string `yaml:"workRoot,omitempty"`
	DeleteOnRelease   *bool  `yaml:"deleteOnRelease,omitempty"`
	StartTimeout      string `yaml:"startTimeout,omitempty"`
	LaunchPort        string `yaml:"launchPort,omitempty"`
	ProxyListenHost   string `yaml:"proxyListenHost,omitempty"`
	ProxyListenPort   string `yaml:"proxyListenPort,omitempty"`
	ProxyDevice       string `yaml:"proxyDevice,omitempty"`
	TLSServerCert     string `yaml:"tlsServerCert,omitempty"`
	InsecureTLS       *bool  `yaml:"insecureTLS,omitempty"`
	RemoteImageServer string `yaml:"remoteImageServer,omitempty"`
}

const IncusConfigDefaultRemote string = "local"
const IncusConfigDefaultInstanceType string = "container"
const IncusConfigDefaultImage string = "images:ubuntu/24.04/cloud"
const IncusConfigDefaultUser string = "crabbox"
const IncusConfigDefaultDeleteOnRelease bool = true
const IncusConfigDefaultStartTimeout time.Duration = 600 * time.Second
const IncusConfigDefaultLaunchPort string = "22"
const IncusConfigDefaultProxyListenHost string = "127.0.0.1"
const IncusConfigDefaultProxyDevice string = "crabbox-ssh"

func defaultIncusConfig() IncusConfig {
	return IncusConfig{
		Remote:          IncusConfigDefaultRemote,
		InstanceType:    IncusConfigDefaultInstanceType,
		Image:           IncusConfigDefaultImage,
		User:            IncusConfigDefaultUser,
		DeleteOnRelease: IncusConfigDefaultDeleteOnRelease,
		StartTimeout:    IncusConfigDefaultStartTimeout,
		LaunchPort:      IncusConfigDefaultLaunchPort,
		ProxyListenHost: IncusConfigDefaultProxyListenHost,
		ProxyDevice:     IncusConfigDefaultProxyDevice,
	}
}

// IncusConfigApplied records accepted assignments during one application.
type IncusConfigApplied struct {
	InputAccepted   bool
	Socket          bool
	DeleteOnRelease bool
	TLSServerCert   bool
}

func (cfg *IncusConfig) applyFile(file *fileIncusConfig) (IncusConfigApplied, error) {
	var applied IncusConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Remote != "" {
		cfg.Remote = file.Remote
		applied.InputAccepted = true
	}
	if file.Project != "" {
		cfg.Project = file.Project
		applied.InputAccepted = true
	}
	if file.Address != "" {
		cfg.Address = file.Address
		applied.InputAccepted = true
	}
	if file.Socket != "" {
		cfg.Socket = file.Socket
		applied.InputAccepted = true
		applied.Socket = true
	}
	if file.InstanceType != "" {
		cfg.InstanceType = file.InstanceType
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
	}
	if file.Profile != "" {
		cfg.Profile = file.Profile
		applied.InputAccepted = true
	}
	if file.User != "" {
		cfg.User = file.User
		applied.InputAccepted = true
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.InputAccepted = true
	}
	if file.DeleteOnRelease != nil {
		cfg.DeleteOnRelease = *file.DeleteOnRelease
		applied.InputAccepted = true
		applied.DeleteOnRelease = true
	}
	if file.StartTimeout != "" {
		if applyLeaseDuration(&cfg.StartTimeout, file.StartTimeout) {
			applied.InputAccepted = true
		}
	}
	if file.LaunchPort != "" {
		cfg.LaunchPort = file.LaunchPort
		applied.InputAccepted = true
	}
	if file.ProxyListenHost != "" {
		cfg.ProxyListenHost = file.ProxyListenHost
		applied.InputAccepted = true
	}
	if file.ProxyListenPort != "" {
		cfg.ProxyListenPort = file.ProxyListenPort
		applied.InputAccepted = true
	}
	if file.ProxyDevice != "" {
		cfg.ProxyDevice = file.ProxyDevice
		applied.InputAccepted = true
	}
	if file.TLSServerCert != "" {
		cfg.TLSServerCert = file.TLSServerCert
		applied.InputAccepted = true
		applied.TLSServerCert = true
	}
	if file.InsecureTLS != nil {
		cfg.InsecureTLS = *file.InsecureTLS
		applied.InputAccepted = true
	}
	if file.RemoteImageServer != "" {
		cfg.RemoteImageServer = file.RemoteImageServer
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *IncusConfig) applyEnv() (IncusConfigApplied, error) {
	var applied IncusConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_REMOTE"); ok {
		cfg.Remote = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_PROJECT"); ok {
		cfg.Project = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_ADDRESS"); ok {
		cfg.Address = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_SOCKET"); ok {
		cfg.Socket = value
		applied.InputAccepted = true
		applied.Socket = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_INSTANCE_TYPE"); ok {
		cfg.InstanceType = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_IMAGE"); ok {
		cfg.Image = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_PROFILE"); ok {
		cfg.Profile = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_USER"); ok {
		cfg.User = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_WORK_ROOT"); ok {
		cfg.WorkRoot = value
		applied.InputAccepted = true
	}
	if value, ok := getenvBool("CRABBOX_INCUS_DELETE_ON_RELEASE"); ok {
		cfg.DeleteOnRelease = value
		applied.InputAccepted = true
		applied.DeleteOnRelease = true
	}
	if value := os.Getenv("CRABBOX_INCUS_START_TIMEOUT"); value != "" {
		if applyLeaseDuration(&cfg.StartTimeout, value) {
			applied.InputAccepted = true
		}
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_LAUNCH_PORT"); ok {
		cfg.LaunchPort = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_PROXY_LISTEN_HOST"); ok {
		cfg.ProxyListenHost = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_PROXY_LISTEN_PORT"); ok {
		cfg.ProxyListenPort = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_PROXY_DEVICE"); ok {
		cfg.ProxyDevice = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_TLS_SERVER_CERT"); ok {
		cfg.TLSServerCert = value
		applied.InputAccepted = true
		applied.TLSServerCert = true
	}
	if value, ok := getenvBool("CRABBOX_INCUS_INSECURE_TLS"); ok {
		cfg.InsecureTLS = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_INCUS_REMOTE_IMAGE_SERVER"); ok {
		cfg.RemoteImageServer = value
		applied.InputAccepted = true
	}
	return applied, nil
}

// IncusConfigFlagValues holds parsed values; only visited flags are applied.
type IncusConfigFlagValues struct {
	Remote            *string
	Project           *string
	Address           *string
	Socket            *string
	InstanceType      *string
	Image             *string
	Profile           *string
	User              *string
	WorkRoot          *string
	DeleteOnRelease   *bool
	StartTimeout      *string
	LaunchPort        *string
	ProxyListenHost   *string
	ProxyListenPort   *string
	ProxyDevice       *string
	TLSServerCert     *string
	InsecureTLS       *bool
	RemoteImageServer *string
}

// RegisterIncusConfigFlags registers mechanical bindings without selecting a provider.
func RegisterIncusConfigFlags(fs *flag.FlagSet, defaults IncusConfig) IncusConfigFlagValues {
	return IncusConfigFlagValues{
		Remote:            fs.String("incus-remote", defaults.Remote, "Incus remote name from the local Incus client config"),
		Project:           fs.String("incus-project", defaults.Project, "Incus project name"),
		Address:           fs.String("incus-address", defaults.Address, "Incus API address override, for example https://host:8443"),
		Socket:            fs.String("incus-socket", defaults.Socket, "Incus Unix socket path override"),
		InstanceType:      fs.String("incus-instance-type", defaults.InstanceType, "Incus instance type: container or vm"),
		Image:             fs.String("incus-image", defaults.Image, "Incus image alias or fingerprint"),
		Profile:           fs.String("incus-profile", defaults.Profile, "optional Incus profile applied to Crabbox leases"),
		User:              fs.String("incus-user", defaults.User, "SSH user inside Incus leases"),
		WorkRoot:          fs.String("incus-work-root", defaults.WorkRoot, "remote Crabbox work root inside Incus leases"),
		DeleteOnRelease:   fs.Bool("incus-delete-on-release", defaults.DeleteOnRelease, "delete the Incus instance on release"),
		StartTimeout:      fs.String("incus-start-timeout", defaults.StartTimeout.String(), "Incus start timeout"),
		LaunchPort:        fs.String("incus-launch-port", defaults.LaunchPort, "guest SSH port exposed by Incus cloud-init/bootstrap"),
		ProxyListenHost:   fs.String("incus-proxy-listen-host", defaults.ProxyListenHost, "host address for optional Incus proxy device"),
		ProxyListenPort:   fs.String("incus-proxy-listen-port", defaults.ProxyListenPort, "host TCP port for optional Incus proxy device"),
		ProxyDevice:       fs.String("incus-proxy-device", defaults.ProxyDevice, "Incus proxy device name"),
		TLSServerCert:     fs.String("incus-tls-server-cert", defaults.TLSServerCert, "trusted Incus server certificate path"),
		InsecureTLS:       fs.Bool("incus-insecure-tls", defaults.InsecureTLS, "allow self-signed or untrusted Incus TLS certificates"),
		RemoteImageServer: fs.String("incus-remote-image-server", defaults.RemoteImageServer, "remote image server for alias-based image resolution"),
	}
}

// IncusConfigVisitedFlags records raw flag visits, independently of application.
type IncusConfigVisitedFlags struct {
	Remote            bool
	Project           bool
	Address           bool
	Socket            bool
	InstanceType      bool
	Image             bool
	Profile           bool
	User              bool
	WorkRoot          bool
	DeleteOnRelease   bool
	StartTimeout      bool
	LaunchPort        bool
	ProxyListenHost   bool
	ProxyListenPort   bool
	ProxyDevice       bool
	TLSServerCert     bool
	InsecureTLS       bool
	RemoteImageServer bool
}

// IncusConfigFlagPresence reports visits for tracked flag bindings.
func IncusConfigFlagPresence(fs *flag.FlagSet) IncusConfigVisitedFlags {
	return IncusConfigVisitedFlags{
		Remote:            flagWasSet(fs, "incus-remote"),
		Project:           flagWasSet(fs, "incus-project"),
		Address:           flagWasSet(fs, "incus-address"),
		Socket:            flagWasSet(fs, "incus-socket"),
		InstanceType:      flagWasSet(fs, "incus-instance-type"),
		Image:             flagWasSet(fs, "incus-image"),
		Profile:           flagWasSet(fs, "incus-profile"),
		User:              flagWasSet(fs, "incus-user"),
		WorkRoot:          flagWasSet(fs, "incus-work-root"),
		DeleteOnRelease:   flagWasSet(fs, "incus-delete-on-release"),
		StartTimeout:      flagWasSet(fs, "incus-start-timeout"),
		LaunchPort:        flagWasSet(fs, "incus-launch-port"),
		ProxyListenHost:   flagWasSet(fs, "incus-proxy-listen-host"),
		ProxyListenPort:   flagWasSet(fs, "incus-proxy-listen-port"),
		ProxyDevice:       flagWasSet(fs, "incus-proxy-device"),
		TLSServerCert:     flagWasSet(fs, "incus-tls-server-cert"),
		InsecureTLS:       flagWasSet(fs, "incus-insecure-tls"),
		RemoteImageServer: flagWasSet(fs, "incus-remote-image-server"),
	}
}
