// Code generated by scripts/configgen from config_lume.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileLumeConfig struct {
	CLIPath  string `yaml:"cliPath,omitempty"`
	Base     string `yaml:"base,omitempty"`
	Storage  string `yaml:"storage,omitempty"`
	User     string `yaml:"user,omitempty"`
	WorkRoot string `yaml:"workRoot,omitempty"`
}

const LumeConfigDefaultCLIPath string = "lume"
const LumeConfigDefaultBase string = "crabbox-macos-golden"
const LumeConfigDefaultUser string = "lume"
const LumeConfigDefaultWorkRoot string = "/Users/lume/crabbox"

func defaultLumeConfig() LumeConfig {
	return LumeConfig{
		CLIPath:  LumeConfigDefaultCLIPath,
		Base:     LumeConfigDefaultBase,
		User:     LumeConfigDefaultUser,
		WorkRoot: LumeConfigDefaultWorkRoot,
	}
}

// LumeConfigApplied records accepted assignments during one application.
type LumeConfigApplied struct {
	InputAccepted bool
}

func (cfg *LumeConfig) applyFile(file *fileLumeConfig, trusted bool) (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	if file == nil {
		return applied, nil
	}
	if trusted && file.CLIPath != "" {
		cfg.CLIPath = file.CLIPath
		applied.InputAccepted = true
	}
	if trusted && file.Base != "" {
		cfg.Base = file.Base
		applied.InputAccepted = true
	}
	if trusted && file.Storage != "" {
		cfg.Storage = file.Storage
		applied.InputAccepted = true
	}
	if trusted && file.User != "" {
		cfg.User = file.User
		applied.InputAccepted = true
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *LumeConfig) applyEnv() (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// LumeConfigFlagValues holds parsed values; only visited flags are applied.
type LumeConfigFlagValues struct {
	CLIPath  *string
	Base     *string
	Storage  *string
	User     *string
	WorkRoot *string
}

// RegisterLumeConfigFlags registers mechanical bindings without selecting a provider.
func RegisterLumeConfigFlags(fs *flag.FlagSet, defaults LumeConfig) LumeConfigFlagValues {
	return LumeConfigFlagValues{
		CLIPath:  fs.String("lume-cli", defaults.CLIPath, "path to the Lume CLI"),
		Base:     fs.String("lume-base", defaults.Base, "stopped Lume VM to clone for each lease"),
		Storage:  fs.String("lume-storage", defaults.Storage, "optional Lume storage location"),
		User:     fs.String("lume-user", defaults.User, "guest account prepared for SSH"),
		WorkRoot: fs.String("lume-work-root", defaults.WorkRoot, "guest work root"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values LumeConfigFlagValues) Apply(cfg *LumeConfig, fs *flag.FlagSet) (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	if flagWasSet(fs, "lume-cli") {
		cfg.CLIPath = *values.CLIPath
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "lume-base") {
		cfg.Base = *values.Base
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "lume-storage") {
		cfg.Storage = *values.Storage
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "lume-user") {
		cfg.User = *values.User
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "lume-work-root") {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
	}
	return applied, nil
}
