// Code generated by scripts/configgen from config_railway.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileRailwayConfig struct {
	APIURL        string `yaml:"apiUrl,omitempty"`
	ProjectID     string `yaml:"projectId,omitempty"`
	EnvironmentID string `yaml:"environmentId,omitempty"`
}

const RailwayConfigDefaultAPIURL string = "https://backboard.railway.com/graphql/v2"

func defaultRailwayConfig() RailwayConfig {
	return RailwayConfig{
		APIURL: RailwayConfigDefaultAPIURL,
	}
}

// RailwayConfigApplied records accepted assignments during one application.
type RailwayConfigApplied struct {
	InputAccepted bool
	APIToken      bool
	APIURL        bool
}

func (cfg *RailwayConfig) applyFile(file *fileRailwayConfig) (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if file.ProjectID != "" {
		cfg.ProjectID = file.ProjectID
		applied.InputAccepted = true
	}
	if file.EnvironmentID != "" {
		cfg.EnvironmentID = file.EnvironmentID
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *RailwayConfig) applyEnv() (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_RAILWAY_API_TOKEN", "RAILWAY_API_TOKEN"); ok {
		cfg.APIToken = value
		applied.InputAccepted = true
		applied.APIToken = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_RAILWAY_API_URL", "RAILWAY_API_URL"); ok {
		cfg.APIURL = value
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_RAILWAY_PROJECT_ID", "RAILWAY_PROJECT_ID"); ok {
		cfg.ProjectID = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_RAILWAY_ENVIRONMENT_ID", "RAILWAY_ENVIRONMENT_ID"); ok {
		cfg.EnvironmentID = value
		applied.InputAccepted = true
	}
	return applied, nil
}

// RailwayConfigFlagValues holds parsed values; only visited flags are applied.
type RailwayConfigFlagValues struct {
	APIURL        *string
	ProjectID     *string
	EnvironmentID *string
}

// RegisterRailwayConfigFlags registers mechanical bindings without selecting a provider.
func RegisterRailwayConfigFlags(fs *flag.FlagSet, defaults RailwayConfig) RailwayConfigFlagValues {
	return RailwayConfigFlagValues{
		APIURL:        fs.String("railway-url", defaults.APIURL, "Railway GraphQL API URL"),
		ProjectID:     fs.String("railway-project", defaults.ProjectID, "Railway project ID containing the target service"),
		EnvironmentID: fs.String("railway-environment", defaults.EnvironmentID, "Railway environment ID to deploy into"),
	}
}

// RailwayConfigVisitedFlags records raw flag visits, independently of application.
type RailwayConfigVisitedFlags struct {
	APIURL bool
}

// RailwayConfigFlagPresence reports visits for tracked flag bindings.
func RailwayConfigFlagPresence(fs *flag.FlagSet) RailwayConfigVisitedFlags {
	return RailwayConfigVisitedFlags{
		APIURL: flagWasSet(fs, "railway-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values RailwayConfigFlagValues) Apply(cfg *RailwayConfig, fs *flag.FlagSet) (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	visited := RailwayConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if flagWasSet(fs, "railway-project") {
		cfg.ProjectID = *values.ProjectID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "railway-environment") {
		cfg.EnvironmentID = *values.EnvironmentID
		applied.InputAccepted = true
	}
	return applied, nil
}
