// Code generated by scripts/configgen from config_opensandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOpenSandboxConfig struct {
	Image           *string `yaml:"image,omitempty"`
	Workdir         *string `yaml:"workdir,omitempty"`
	CPU             *string `yaml:"cpu,omitempty"`
	Memory          *string `yaml:"memory,omitempty"`
	TimeoutSecs     *int    `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int    `yaml:"execTimeoutSecs,omitempty"`
	PlatformOS      *string `yaml:"platformOS,omitempty"`
	PlatformArch    *string `yaml:"platformArch,omitempty"`
	SecureAccess    *bool   `yaml:"secureAccess,omitempty"`
	UseServerProxy  *bool   `yaml:"useServerProxy,omitempty"`
}

const OpenSandboxConfigDefaultImage string = "ubuntu:24.04"
const OpenSandboxConfigDefaultWorkdir string = "/workspace/crabbox"
const OpenSandboxConfigDefaultCPU string = "1"
const OpenSandboxConfigDefaultMemory string = "2Gi"
const OpenSandboxConfigDefaultExecTimeoutSecs int = 600
const OpenSandboxConfigDefaultPlatformOS string = "linux"
const OpenSandboxConfigDefaultPlatformArch string = "amd64"

func defaultOpenSandboxConfig() OpenSandboxConfig {
	return OpenSandboxConfig{
		Image:           OpenSandboxConfigDefaultImage,
		Workdir:         OpenSandboxConfigDefaultWorkdir,
		CPU:             OpenSandboxConfigDefaultCPU,
		Memory:          OpenSandboxConfigDefaultMemory,
		ExecTimeoutSecs: OpenSandboxConfigDefaultExecTimeoutSecs,
		PlatformOS:      OpenSandboxConfigDefaultPlatformOS,
		PlatformArch:    OpenSandboxConfigDefaultPlatformArch,
	}
}

// OpenSandboxConfigApplied records accepted assignments during one application.
type OpenSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *OpenSandboxConfig) applyFile(file *fileOpenSandboxConfig) (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "opensandbox")
	return applied, err
}

func (cfg *OpenSandboxConfig) applyEnv() (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// OpenSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type OpenSandboxConfigFlagValues struct {
	APIURL          *string
	Image           *string
	Workdir         *string
	CPU             *string
	Memory          *string
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	PlatformOS      *string
	PlatformArch    *string
	SecureAccess    *bool
	UseServerProxy  *bool
	ForgetMissing   *bool
}

// RegisterOpenSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOpenSandboxConfigFlags(fs *flag.FlagSet, defaults OpenSandboxConfig) OpenSandboxConfigFlagValues {
	return OpenSandboxConfigFlagValues{
		APIURL:          fs.String("opensandbox-api-url", defaults.APIURL, "Trusted OpenSandbox API base URL; not accepted from repository config"),
		Image:           fs.String("opensandbox-image", defaults.Image, "OpenSandbox container image URI"),
		Workdir:         fs.String("opensandbox-workdir", defaults.Workdir, "Absolute working directory inside the sandbox (also used as sync target)"),
		CPU:             fs.String("opensandbox-cpu", defaults.CPU, "OpenSandbox CPU resource limit string (empty = service default)"),
		Memory:          fs.String("opensandbox-memory", defaults.Memory, "OpenSandbox memory resource limit string (empty = service default)"),
		TimeoutSecs:     fs.Int("opensandbox-timeout-secs", defaults.TimeoutSecs, "OpenSandbox sandbox lifetime cap and readiness budget in seconds (0 = Crabbox TTL)"),
		ExecTimeoutSecs: fs.Int("opensandbox-exec-timeout-secs", defaults.ExecTimeoutSecs, "OpenSandbox command timeout in seconds (0 = Crabbox default 600)"),
		PlatformOS:      fs.String("opensandbox-platform-os", defaults.PlatformOS, "OpenSandbox platform OS constraint (set with --opensandbox-platform-arch; both empty = service default)"),
		PlatformArch:    fs.String("opensandbox-platform-arch", defaults.PlatformArch, "OpenSandbox platform architecture constraint (set with --opensandbox-platform-os; both empty = service default)"),
		SecureAccess:    fs.Bool("opensandbox-secure-access", defaults.SecureAccess, "request secured sandbox endpoints"),
		UseServerProxy:  fs.Bool("opensandbox-use-server-proxy", defaults.UseServerProxy, "route execd requests through the OpenSandbox server proxy"),
		ForgetMissing:   fs.Bool("opensandbox-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OpenSandboxConfigFlagValues) Apply(cfg *OpenSandboxConfig, fs *flag.FlagSet) (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
