// Code generated by scripts/configgen from config_blacksmith.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
)

type fileBlacksmithConfig struct {
	Org         string `yaml:"org,omitempty"`
	Workflow    string `yaml:"workflow,omitempty"`
	Job         string `yaml:"job,omitempty"`
	Ref         string `yaml:"ref,omitempty"`
	IdleTimeout string `yaml:"idleTimeout,omitempty"`
	Debug       *bool  `yaml:"debug,omitempty"`
}

func defaultBlacksmithConfig() BlacksmithConfig {
	return BlacksmithConfig{}
}

// BlacksmithConfigApplied records accepted assignments during one application.
type BlacksmithConfigApplied struct {
	InputAccepted bool
}

func (cfg *BlacksmithConfig) applyFile(file *fileBlacksmithConfig) (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Org != "" {
		cfg.Org = file.Org
		applied.InputAccepted = true
	}
	if file.Workflow != "" {
		cfg.Workflow = file.Workflow
		applied.InputAccepted = true
	}
	if file.Job != "" {
		cfg.Job = file.Job
		applied.InputAccepted = true
	}
	if file.Ref != "" {
		cfg.Ref = file.Ref
		applied.InputAccepted = true
	}
	if file.IdleTimeout != "" {
		if applyLeaseDuration(&cfg.IdleTimeout, file.IdleTimeout) {
			applied.InputAccepted = true
		}
	}
	if file.Debug != nil {
		cfg.Debug = *file.Debug
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *BlacksmithConfig) applyEnvPrefix() (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_BLACKSMITH_ORG"); ok {
		cfg.Org = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_BLACKSMITH_WORKFLOW"); ok {
		cfg.Workflow = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_BLACKSMITH_JOB"); ok {
		cfg.Job = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_BLACKSMITH_REF"); ok {
		cfg.Ref = value
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *BlacksmithConfig) applyEnvSuffix() (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	if value := os.Getenv("CRABBOX_BLACKSMITH_IDLE_TIMEOUT"); value != "" {
		if applyLeaseDuration(&cfg.IdleTimeout, value) {
			applied.InputAccepted = true
		}
	}
	if value, ok := getenvBool("CRABBOX_BLACKSMITH_DEBUG"); ok {
		cfg.Debug = value
		applied.InputAccepted = true
	}
	return applied, nil
}

// BlacksmithConfigFlagValues holds parsed values; only visited flags are applied.
type BlacksmithConfigFlagValues struct {
	Org      *string
	Workflow *string
	Job      *string
	Ref      *string
}

// RegisterBlacksmithConfigFlags registers mechanical bindings without selecting a provider.
func RegisterBlacksmithConfigFlags(fs *flag.FlagSet, defaults BlacksmithConfig) BlacksmithConfigFlagValues {
	return BlacksmithConfigFlagValues{
		Org:      fs.String("blacksmith-org", defaults.Org, "Blacksmith organization"),
		Workflow: fs.String("blacksmith-workflow", defaults.Workflow, "Blacksmith Testbox workflow file, name, or id"),
		Job:      fs.String("blacksmith-job", defaults.Job, "Blacksmith Testbox workflow job"),
		Ref:      fs.String("blacksmith-ref", defaults.Ref, "Blacksmith Testbox git ref"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values BlacksmithConfigFlagValues) Apply(cfg *BlacksmithConfig, fs *flag.FlagSet) (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	if flagWasSet(fs, "blacksmith-org") {
		cfg.Org = *values.Org
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "blacksmith-workflow") {
		cfg.Workflow = *values.Workflow
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "blacksmith-job") {
		cfg.Job = *values.Job
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "blacksmith-ref") {
		cfg.Ref = *values.Ref
		applied.InputAccepted = true
	}
	return applied, nil
}
