// Code generated by scripts/configgen from config_vast.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileVastConfig struct {
	APIURL         string   `yaml:"apiUrl,omitempty"`
	InstanceType   string   `yaml:"instanceType,omitempty"`
	GPUName        string   `yaml:"gpuName,omitempty"`
	GPUCount       int      `yaml:"gpuCount,omitempty"`
	Image          string   `yaml:"image,omitempty"`
	TemplateID     string   `yaml:"templateId,omitempty"`
	Runtype        string   `yaml:"runtype,omitempty"`
	DiskGB         int      `yaml:"diskGB,omitempty"`
	MaxDphTotal    *float64 `yaml:"maxDphTotal,omitempty"`
	MinReliability *float64 `yaml:"minReliability,omitempty"`
	Order          string   `yaml:"order,omitempty"`
	User           string   `yaml:"user,omitempty"`
	WorkRoot       string   `yaml:"workRoot,omitempty"`
	ReleaseAction  string   `yaml:"releaseAction,omitempty"`
}

const VastConfigDefaultAPIURL string = "https://console.vast.ai/api/v0"
const VastConfigDefaultInstanceType string = "ondemand"
const VastConfigDefaultImage string = "nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04"
const VastConfigDefaultRuntype string = "ssh_direct"
const VastConfigDefaultDiskGB int = 20
const VastConfigDefaultOrder string = "dlperf_per_dphtotal desc"
const VastConfigDefaultUser string = "root"
const VastConfigDefaultWorkRoot string = "/work/crabbox"
const VastConfigDefaultReleaseAction string = "destroy"

func defaultVastConfig() VastConfig {
	return VastConfig{
		APIURL:        VastConfigDefaultAPIURL,
		InstanceType:  VastConfigDefaultInstanceType,
		Image:         VastConfigDefaultImage,
		Runtype:       VastConfigDefaultRuntype,
		DiskGB:        VastConfigDefaultDiskGB,
		Order:         VastConfigDefaultOrder,
		User:          VastConfigDefaultUser,
		WorkRoot:      VastConfigDefaultWorkRoot,
		ReleaseAction: VastConfigDefaultReleaseAction,
	}
}

// VastConfigApplied records accepted assignments during one application.
type VastConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

func (cfg *VastConfig) applyFile(file *fileVastConfig) (VastConfigApplied, error) {
	var applied VastConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "vast")
	return applied, err
}

func (cfg *VastConfig) applyEnv() (VastConfigApplied, error) {
	var applied VastConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 15)
	return applied, err
}

// VastConfigFlagValues holds parsed values; only visited flags are applied.
type VastConfigFlagValues struct {
	APIURL         *string
	InstanceType   *string
	GPUName        *string
	GPUCount       *int
	Image          *string
	TemplateID     *string
	Runtype        *string
	DiskGB         *int
	MaxDphTotal    *float64
	MinReliability *float64
	Order          *string
	User           *string
	WorkRoot       *string
	ReleaseAction  *string
}

// RegisterVastConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVastConfigFlags(fs *flag.FlagSet, defaults VastConfig) VastConfigFlagValues {
	return VastConfigFlagValues{
		APIURL:         fs.String("vast-api-url", defaults.APIURL, "Vast.ai REST API URL"),
		InstanceType:   fs.String("vast-instance-type", defaults.InstanceType, "Vast.ai offer type: ondemand or interruptible"),
		GPUName:        fs.String("vast-gpu-name", defaults.GPUName, "Vast.ai GPU name selector"),
		GPUCount:       fs.Int("vast-gpu-count", defaults.GPUCount, "Vast.ai minimum GPU count"),
		Image:          fs.String("vast-image", defaults.Image, "Docker image to deploy on the instance"),
		TemplateID:     fs.String("vast-template-id", defaults.TemplateID, "Optional Vast.ai template ID"),
		Runtype:        fs.String("vast-runtype", defaults.Runtype, "Vast.ai runtime type: ssh_direct"),
		DiskGB:         fs.Int("vast-disk-gb", defaults.DiskGB, "Instance disk size in GB"),
		MaxDphTotal:    fs.Float64("vast-max-dph-total", defaults.MaxDphTotal, "Maximum total dollars per hour"),
		MinReliability: fs.Float64("vast-min-reliability", defaults.MinReliability, "Minimum reliability score from 0 to 1"),
		Order:          fs.String("vast-order", defaults.Order, "Vast.ai offer ordering expression"),
		User:           fs.String("vast-user", defaults.User, "SSH user for Vast.ai instances"),
		WorkRoot:       fs.String("vast-work-root", defaults.WorkRoot, "remote Crabbox work root on Vast.ai instances"),
		ReleaseAction:  fs.String("vast-release-action", defaults.ReleaseAction, "Vast.ai release action: destroy, stop, or keep"),
	}
}

// VastConfigVisitedFlags records raw flag visits, independently of application.
type VastConfigVisitedFlags struct {
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

// VastConfigFlagPresence reports visits for tracked flag bindings.
func VastConfigFlagPresence(fs *flag.FlagSet) VastConfigVisitedFlags {
	return VastConfigVisitedFlags{
		APIURL:        flagWasSet(fs, "vast-api-url"),
		InstanceType:  flagWasSet(fs, "vast-instance-type"),
		WorkRoot:      flagWasSet(fs, "vast-work-root"),
		ReleaseAction: flagWasSet(fs, "vast-release-action"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VastConfigFlagValues) Apply(cfg *VastConfig, fs *flag.FlagSet) (VastConfigApplied, error) {
	var applied VastConfigApplied
	visited := VastConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if visited.InstanceType {
		cfg.InstanceType = *values.InstanceType
		applied.InputAccepted = true
		applied.InstanceType = true
	}
	if flagWasSet(fs, "vast-gpu-name") {
		cfg.GPUName = *values.GPUName
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-gpu-count") {
		cfg.GPUCount = *values.GPUCount
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-template-id") {
		cfg.TemplateID = *values.TemplateID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-runtype") {
		cfg.Runtype = *values.Runtype
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-disk-gb") {
		cfg.DiskGB = *values.DiskGB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-max-dph-total") {
		cfg.MaxDphTotal = *values.MaxDphTotal
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-min-reliability") {
		cfg.MinReliability = *values.MinReliability
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-order") {
		cfg.Order = *values.Order
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "vast-user") {
		cfg.User = *values.User
		applied.InputAccepted = true
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if visited.ReleaseAction {
		cfg.ReleaseAction = *values.ReleaseAction
		applied.InputAccepted = true
		applied.ReleaseAction = true
	}
	return applied, nil
}
