// Code generated by scripts/configgen from config_opencomputer.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOpenComputerConfig struct {
	Workdir         string `yaml:"workdir,omitempty"`
	CPU             *int   `yaml:"cpu,omitempty"`
	MemoryMB        *int   `yaml:"memoryMB,omitempty"`
	TimeoutSecs     *int   `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int   `yaml:"execTimeoutSecs,omitempty"`
	Burst           *bool  `yaml:"burst,omitempty"`
}

const OpenComputerConfigDefaultWorkdir string = "/workspace/crabbox"
const OpenComputerConfigDefaultExecTimeoutSecs int = 3600

func defaultOpenComputerConfig() OpenComputerConfig {
	return OpenComputerConfig{
		Workdir:         OpenComputerConfigDefaultWorkdir,
		ExecTimeoutSecs: OpenComputerConfigDefaultExecTimeoutSecs,
	}
}

// OpenComputerConfigApplied records accepted assignments during one application.
type OpenComputerConfigApplied struct {
	InputAccepted bool
}

func (cfg *OpenComputerConfig) applyFile(file *fileOpenComputerConfig) (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
		applied.InputAccepted = true
	}
	if file.CPU != nil {
		cfg.CPU = *file.CPU
		applied.InputAccepted = true
	}
	if file.MemoryMB != nil {
		cfg.MemoryMB = *file.MemoryMB
		applied.InputAccepted = true
	}
	if file.TimeoutSecs != nil {
		cfg.TimeoutSecs = *file.TimeoutSecs
		applied.InputAccepted = true
	}
	if file.ExecTimeoutSecs != nil {
		cfg.ExecTimeoutSecs = *file.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if file.Burst != nil {
		cfg.Burst = *file.Burst
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *OpenComputerConfig) applyEnv() (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// OpenComputerConfigFlagValues holds parsed values; only visited flags are applied.
type OpenComputerConfigFlagValues struct {
	APIURL          *string
	Workdir         *string
	CPU             *int
	MemoryMB        *int
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Burst           *bool
	ForgetMissing   *bool
}

// RegisterOpenComputerConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOpenComputerConfigFlags(fs *flag.FlagSet, defaults OpenComputerConfig) OpenComputerConfigFlagValues {
	return OpenComputerConfigFlagValues{
		APIURL:          fs.String("opencomputer-api-url", defaults.APIURL, "Trusted OpenComputer API base URL; not accepted from repository config"),
		Workdir:         fs.String("opencomputer-workdir", defaults.Workdir, "Absolute working directory inside the sandbox (also used as sync target)"),
		CPU:             fs.Int("opencomputer-cpu", defaults.CPU, "OpenComputer sandbox vCPU count (0 = service default; the service infers memory when omitted)"),
		MemoryMB:        fs.Int("opencomputer-memory-mb", defaults.MemoryMB, "OpenComputer sandbox memory in MB (0 = service default; the service infers CPU when omitted)"),
		TimeoutSecs:     fs.Int("opencomputer-timeout-secs", defaults.TimeoutSecs, "OpenComputer sandbox idle timeout in seconds (0 = service default)"),
		ExecTimeoutSecs: fs.Int("opencomputer-exec-timeout-secs", defaults.ExecTimeoutSecs, "OpenComputer command timeout in seconds (0 = Crabbox default 3600)"),
		Burst:           fs.Bool("opencomputer-burst", defaults.Burst, "use alpha best-effort burst capacity; filesystem persists but processes may restart"),
		ForgetMissing:   fs.Bool("opencomputer-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OpenComputerConfigFlagValues) Apply(cfg *OpenComputerConfig, fs *flag.FlagSet) (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	if flagWasSet(fs, "opencomputer-api-url") {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-cpu") {
		cfg.CPU = *values.CPU
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-memory-mb") {
		cfg.MemoryMB = *values.MemoryMB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-burst") {
		cfg.Burst = *values.Burst
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "opencomputer-forget-missing") {
		cfg.ForgetMissing = *values.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}
