// Code generated by scripts/configgen from config_upstash_box.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileUpstashBoxConfig struct {
	BaseURL   string `yaml:"baseUrl,omitempty"`
	Runtime   string `yaml:"runtime,omitempty"`
	Size      string `yaml:"size,omitempty"`
	Workdir   string `yaml:"workdir,omitempty"`
	KeepAlive *bool  `yaml:"keepAlive,omitempty"`
}

const UpstashBoxConfigDefaultBaseURL string = "https://us-east-1.box.upstash.com"
const UpstashBoxConfigDefaultRuntime string = "node"
const UpstashBoxConfigDefaultSize string = "small"
const UpstashBoxConfigDefaultWorkdir string = "/workspace/home/crabbox"

func defaultUpstashBoxConfig() UpstashBoxConfig {
	return UpstashBoxConfig{
		BaseURL: UpstashBoxConfigDefaultBaseURL,
		Runtime: UpstashBoxConfigDefaultRuntime,
		Size:    UpstashBoxConfigDefaultSize,
		Workdir: UpstashBoxConfigDefaultWorkdir,
	}
}

// UpstashBoxConfigApplied records accepted assignments during one application.
type UpstashBoxConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	BaseURL       bool
}

func (cfg *UpstashBoxConfig) applyFile(file *fileUpstashBoxConfig) (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.BaseURL != "" {
		cfg.BaseURL = file.BaseURL
		applied.InputAccepted = true
		applied.BaseURL = true
	}
	if file.Runtime != "" {
		cfg.Runtime = file.Runtime
		applied.InputAccepted = true
	}
	if file.Size != "" {
		cfg.Size = file.Size
		applied.InputAccepted = true
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
		applied.InputAccepted = true
	}
	if file.KeepAlive != nil {
		cfg.KeepAlive = *file.KeepAlive
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *UpstashBoxConfig) applyEnv() (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// UpstashBoxConfigFlagValues holds parsed values; only visited flags are applied.
type UpstashBoxConfigFlagValues struct {
	BaseURL   *string
	Runtime   *string
	Size      *string
	Workdir   *string
	KeepAlive *bool
}

// RegisterUpstashBoxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterUpstashBoxConfigFlags(fs *flag.FlagSet, defaults UpstashBoxConfig) UpstashBoxConfigFlagValues {
	return UpstashBoxConfigFlagValues{
		BaseURL:   fs.String("upstash-box-base-url", defaults.BaseURL, "Upstash Box API base URL"),
		Runtime:   fs.String("upstash-box-runtime", defaults.Runtime, "Upstash Box runtime: node, python, golang, ruby, or rust"),
		Size:      fs.String("upstash-box-size", defaults.Size, "Upstash Box size: small, medium, or large"),
		Workdir:   fs.String("upstash-box-workdir", defaults.Workdir, "absolute working directory inside the Upstash Box"),
		KeepAlive: fs.Bool("upstash-box-keep-alive", defaults.KeepAlive, "create Upstash boxes with keepAlive enabled"),
	}
}

// UpstashBoxConfigVisitedFlags records raw flag visits, independently of application.
type UpstashBoxConfigVisitedFlags struct {
	BaseURL bool
}

// UpstashBoxConfigFlagPresence reports visits for tracked flag bindings.
func UpstashBoxConfigFlagPresence(fs *flag.FlagSet) UpstashBoxConfigVisitedFlags {
	return UpstashBoxConfigVisitedFlags{
		BaseURL: flagWasSet(fs, "upstash-box-base-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values UpstashBoxConfigFlagValues) Apply(cfg *UpstashBoxConfig, fs *flag.FlagSet) (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	visited := UpstashBoxConfigFlagPresence(fs)
	if visited.BaseURL {
		cfg.BaseURL = *values.BaseURL
		applied.InputAccepted = true
		applied.BaseURL = true
	}
	if flagWasSet(fs, "upstash-box-runtime") {
		cfg.Runtime = *values.Runtime
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "upstash-box-size") {
		cfg.Size = *values.Size
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "upstash-box-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "upstash-box-keep-alive") {
		cfg.KeepAlive = *values.KeepAlive
		applied.InputAccepted = true
	}
	return applied, nil
}
