// Code generated by scripts/configgen from config_azure_dynamic_sessions.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileAzureDynamicSessionsConfig struct {
	Endpoint    string `yaml:"endpoint,omitempty"`
	Pool        string `yaml:"pool,omitempty"`
	APIVersion  string `yaml:"apiVersion,omitempty"`
	Workdir     string `yaml:"workdir,omitempty"`
	TimeoutSecs int    `yaml:"timeoutSecs,omitempty"`
}

const AzureDynamicSessionsConfigDefaultAPIVersion string = "2025-02-02-preview"
const AzureDynamicSessionsConfigDefaultWorkdir string = "/workspace/crabbox"
const AzureDynamicSessionsConfigDefaultTimeoutSecs int = 1800

func defaultAzureDynamicSessionsConfig() AzureDynamicSessionsConfig {
	return AzureDynamicSessionsConfig{
		APIVersion:  AzureDynamicSessionsConfigDefaultAPIVersion,
		Workdir:     AzureDynamicSessionsConfigDefaultWorkdir,
		TimeoutSecs: AzureDynamicSessionsConfigDefaultTimeoutSecs,
	}
}

// AzureDynamicSessionsConfigApplied records accepted assignments during one application.
type AzureDynamicSessionsConfigApplied struct {
	InputAccepted bool
	Endpoint      bool
}

func (cfg *AzureDynamicSessionsConfig) applyFile(file *fileAzureDynamicSessionsConfig) (AzureDynamicSessionsConfigApplied, error) {
	var applied AzureDynamicSessionsConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "azure-dynamic-sessions")
	return applied, err
}

func (cfg *AzureDynamicSessionsConfig) applyEnv() (AzureDynamicSessionsConfigApplied, error) {
	var applied AzureDynamicSessionsConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// AzureDynamicSessionsConfigFlagValues holds parsed values; only visited flags are applied.
type AzureDynamicSessionsConfigFlagValues struct {
	Endpoint    *string
	APIVersion  *string
	Workdir     *string
	TimeoutSecs *int
}

// RegisterAzureDynamicSessionsConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAzureDynamicSessionsConfigFlags(fs *flag.FlagSet, defaults AzureDynamicSessionsConfig) AzureDynamicSessionsConfigFlagValues {
	return AzureDynamicSessionsConfigFlagValues{
		Endpoint:    fs.String("azure-dynamic-sessions-endpoint", defaults.Endpoint, "Azure Container Apps Dynamic Sessions pool management endpoint"),
		APIVersion:  fs.String("azure-dynamic-sessions-api-version", defaults.APIVersion, "Azure Dynamic Sessions management API version"),
		Workdir:     fs.String("azure-dynamic-sessions-workdir", defaults.Workdir, "Absolute working directory inside the Dynamic Sessions sandbox"),
		TimeoutSecs: fs.Int("azure-dynamic-sessions-timeout-secs", defaults.TimeoutSecs, "Command timeout in seconds"),
	}
}

// AzureDynamicSessionsConfigVisitedFlags records raw flag visits, independently of application.
type AzureDynamicSessionsConfigVisitedFlags struct {
	Endpoint bool
}

// AzureDynamicSessionsConfigFlagPresence reports visits for tracked flag bindings.
func AzureDynamicSessionsConfigFlagPresence(fs *flag.FlagSet) AzureDynamicSessionsConfigVisitedFlags {
	return AzureDynamicSessionsConfigVisitedFlags{
		Endpoint: flagWasSet(fs, "azure-dynamic-sessions-endpoint"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AzureDynamicSessionsConfigFlagValues) Apply(cfg *AzureDynamicSessionsConfig, fs *flag.FlagSet) (AzureDynamicSessionsConfigApplied, error) {
	var applied AzureDynamicSessionsConfigApplied
	visited := AzureDynamicSessionsConfigFlagPresence(fs)
	if visited.Endpoint {
		cfg.Endpoint = *values.Endpoint
		applied.InputAccepted = true
		applied.Endpoint = true
	}
	if flagWasSet(fs, "azure-dynamic-sessions-api-version") {
		cfg.APIVersion = *values.APIVersion
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "azure-dynamic-sessions-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "azure-dynamic-sessions-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
		applied.InputAccepted = true
	}
	return applied, nil
}
