// Code generated by scripts/configgen from config_cloudflare_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudflareSandboxConfig struct {
	BridgeURL            *string `yaml:"bridgeUrl,omitempty"`
	BridgeURLConfigAlias *string `yaml:"url,omitempty"`
	Token                *string `yaml:"token,omitempty"`
	Workdir              *string `yaml:"workdir,omitempty"`
	ExecTimeoutSecs      *int    `yaml:"execTimeoutSecs,omitempty"`
	ForgetMissing        *bool   `yaml:"forgetMissing,omitempty"`
}

const CloudflareSandboxConfigDefaultWorkdir string = "/workspace/crabbox"
const CloudflareSandboxConfigDefaultExecTimeoutSecs int = 600

func defaultCloudflareSandboxConfig() CloudflareSandboxConfig {
	return CloudflareSandboxConfig{
		Workdir:         CloudflareSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: CloudflareSandboxConfigDefaultExecTimeoutSecs,
	}
}

// CloudflareSandboxConfigApplied records accepted assignments during one application.
type CloudflareSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *CloudflareSandboxConfig) applyFile(file *fileCloudflareSandboxConfig, trusted bool) (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	if file == nil {
		return applied, nil
	}
	if trusted && file.BridgeURL != nil {
		cfg.BridgeURL = *file.BridgeURL
		applied.InputAccepted = true
	}
	if trusted && file.BridgeURLConfigAlias != nil {
		cfg.BridgeURL = *file.BridgeURLConfigAlias
		applied.InputAccepted = true
	}
	if trusted && file.Token != nil {
		cfg.Token = *file.Token
		applied.InputAccepted = true
	}
	if file.Workdir != nil {
		cfg.Workdir = *file.Workdir
		applied.InputAccepted = true
	}
	if file.ExecTimeoutSecs != nil {
		if *file.ExecTimeoutSecs < 0 {
			return applied, exit(2, "cloudflare-sandbox execTimeoutSecs must be non-negative")
		}
		cfg.ExecTimeoutSecs = *file.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if file.ForgetMissing != nil {
		cfg.ForgetMissing = *file.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *CloudflareSandboxConfig) applyEnv() (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// CloudflareSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type CloudflareSandboxConfigFlagValues struct {
	BridgeURL       *string
	Workdir         *string
	ExecTimeoutSecs *int
	ForgetMissing   *bool
}

// RegisterCloudflareSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudflareSandboxConfigFlags(fs *flag.FlagSet, defaults CloudflareSandboxConfig) CloudflareSandboxConfigFlagValues {
	return CloudflareSandboxConfigFlagValues{
		BridgeURL:       fs.String("cloudflare-sandbox-url", defaults.BridgeURL, "Cloudflare Sandbox bridge URL"),
		Workdir:         fs.String("cloudflare-sandbox-workdir", defaults.Workdir, "Absolute working directory inside the sandbox"),
		ExecTimeoutSecs: fs.Int("cloudflare-sandbox-exec-timeout-secs", defaults.ExecTimeoutSecs, "command timeout in seconds (0 = bridge default)"),
		ForgetMissing:   fs.Bool("cloudflare-sandbox-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudflareSandboxConfigFlagValues) Apply(cfg *CloudflareSandboxConfig, fs *flag.FlagSet) (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	if flagWasSet(fs, "cloudflare-sandbox-url") {
		cfg.BridgeURL = *values.BridgeURL
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cloudflare-sandbox-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cloudflare-sandbox-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "cloudflare-sandbox-forget-missing") {
		cfg.ForgetMissing = *values.ForgetMissing
		applied.InputAccepted = true
	}
	return applied, nil
}
