// Code generated by scripts/configgen from config_runpod.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileRunpodConfig struct {
	APIURL     string `yaml:"apiUrl,omitempty"`
	CloudType  string `yaml:"cloudType,omitempty"`
	InstanceID string `yaml:"instanceId,omitempty"`
	Image      string `yaml:"image,omitempty"`
	TemplateID string `yaml:"templateId,omitempty"`
	DiskGB     int    `yaml:"diskGB,omitempty"`
	User       string `yaml:"user,omitempty"`
	WorkRoot   string `yaml:"workRoot,omitempty"`
}

const RunpodConfigDefaultAPIURL string = "https://rest.runpod.io/v1"
const RunpodConfigDefaultCloudType string = "SECURE"
const RunpodConfigDefaultInstanceID string = "NVIDIA L4,NVIDIA RTX 4000 Ada Generation,NVIDIA RTX A4000,NVIDIA GeForce RTX 3090,NVIDIA GeForce RTX 4090,NVIDIA RTX A5000,NVIDIA RTX A4500"
const RunpodConfigDefaultImage string = "runpod/pytorch:2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04"
const RunpodConfigDefaultDiskGB int = 20

func defaultRunpodConfig() RunpodConfig {
	return RunpodConfig{
		APIURL:     RunpodConfigDefaultAPIURL,
		CloudType:  RunpodConfigDefaultCloudType,
		InstanceID: RunpodConfigDefaultInstanceID,
		Image:      RunpodConfigDefaultImage,
		DiskGB:     RunpodConfigDefaultDiskGB,
	}
}

// RunpodConfigApplied records accepted assignments during one application.
type RunpodConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
}

func (cfg *RunpodConfig) applyFile(file *fileRunpodConfig) (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if file.CloudType != "" {
		cfg.CloudType = file.CloudType
		applied.InputAccepted = true
	}
	if file.InstanceID != "" {
		cfg.InstanceID = file.InstanceID
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
	}
	if file.TemplateID != "" {
		cfg.TemplateID = file.TemplateID
		applied.InputAccepted = true
	}
	if file.DiskGB != 0 {
		cfg.DiskGB = file.DiskGB
		applied.InputAccepted = true
	}
	if file.User != "" {
		cfg.User = file.User
		applied.InputAccepted = true
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *RunpodConfig) applyEnv() (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// RunpodConfigFlagValues holds parsed values; only visited flags are applied.
type RunpodConfigFlagValues struct {
	APIURL     *string
	CloudType  *string
	InstanceID *string
	Image      *string
	TemplateID *string
	DiskGB     *int
	User       *string
	WorkRoot   *string
}

// RegisterRunpodConfigFlags registers mechanical bindings without selecting a provider.
func RegisterRunpodConfigFlags(fs *flag.FlagSet, defaults RunpodConfig) RunpodConfigFlagValues {
	return RunpodConfigFlagValues{
		APIURL:     fs.String("runpod-url", defaults.APIURL, "RunPod REST API URL"),
		CloudType:  fs.String("runpod-cloud-type", defaults.CloudType, "RunPod cloud type: SECURE or COMMUNITY"),
		InstanceID: fs.String("runpod-instance-id", defaults.InstanceID, "RunPod GPU type ID or CPU flavor ID"),
		Image:      fs.String("runpod-image", defaults.Image, "Docker image to deploy on the pod"),
		TemplateID: fs.String("runpod-template-id", defaults.TemplateID, "Optional RunPod template ID"),
		DiskGB:     fs.Int("runpod-disk-gb", defaults.DiskGB, "Container disk size in GB"),
		User:       fs.String("runpod-user", defaults.User, "SSH user for runpod pods"),
		WorkRoot:   fs.String("runpod-work-root", defaults.WorkRoot, "remote Crabbox work root on runpod pods"),
	}
}

// RunpodConfigVisitedFlags records raw flag visits, independently of application.
type RunpodConfigVisitedFlags struct {
	APIURL bool
}

// RunpodConfigFlagPresence reports visits for tracked flag bindings.
func RunpodConfigFlagPresence(fs *flag.FlagSet) RunpodConfigVisitedFlags {
	return RunpodConfigVisitedFlags{
		APIURL: flagWasSet(fs, "runpod-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values RunpodConfigFlagValues) Apply(cfg *RunpodConfig, fs *flag.FlagSet) (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	visited := RunpodConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if flagWasSet(fs, "runpod-cloud-type") {
		cfg.CloudType = *values.CloudType
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-instance-id") {
		cfg.InstanceID = *values.InstanceID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-template-id") {
		cfg.TemplateID = *values.TemplateID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-disk-gb") {
		cfg.DiskGB = *values.DiskGB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-user") {
		cfg.User = *values.User
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "runpod-work-root") {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
	}
	return applied, nil
}
