// Code generated by scripts/configgen from config_tensorlake.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTensorlakeConfig struct {
	APIURL         string  `yaml:"apiUrl,omitempty"`
	CLIPath        string  `yaml:"cliPath,omitempty"`
	Image          string  `yaml:"image,omitempty"`
	Snapshot       string  `yaml:"snapshot,omitempty"`
	OrganizationID string  `yaml:"organizationId,omitempty"`
	ProjectID      string  `yaml:"projectId,omitempty"`
	Namespace      string  `yaml:"namespace,omitempty"`
	Workdir        string  `yaml:"workdir,omitempty"`
	CPUs           float64 `yaml:"cpus,omitempty"`
	MemoryMB       int     `yaml:"memoryMB,omitempty"`
	DiskMB         int     `yaml:"diskMB,omitempty"`
	TimeoutSecs    int     `yaml:"timeoutSecs,omitempty"`
	NoInternet     *bool   `yaml:"noInternet,omitempty"`
}

const TensorlakeConfigDefaultAPIURL string = "https://api.tensorlake.ai"
const TensorlakeConfigDefaultCLIPath string = "tensorlake"
const TensorlakeConfigDefaultWorkdir string = "/workspace/crabbox"
const TensorlakeConfigDefaultCPUs float64 = 1
const TensorlakeConfigDefaultMemoryMB int = 1024
const TensorlakeConfigDefaultDiskMB int = 10240

func defaultTensorlakeConfig() TensorlakeConfig {
	return TensorlakeConfig{
		APIURL:   TensorlakeConfigDefaultAPIURL,
		CLIPath:  TensorlakeConfigDefaultCLIPath,
		Workdir:  TensorlakeConfigDefaultWorkdir,
		CPUs:     TensorlakeConfigDefaultCPUs,
		MemoryMB: TensorlakeConfigDefaultMemoryMB,
		DiskMB:   TensorlakeConfigDefaultDiskMB,
	}
}

// TensorlakeConfigApplied records accepted assignments during one application.
type TensorlakeConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
}

func (cfg *TensorlakeConfig) applyFile(file *fileTensorlakeConfig) (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "tensorlake")
	return applied, err
}

func (cfg *TensorlakeConfig) applyEnv() (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 14)
	return applied, err
}

// TensorlakeConfigFlagValues holds parsed values; only visited flags are applied.
type TensorlakeConfigFlagValues struct {
	APIURL         *string
	CLIPath        *string
	Image          *string
	Snapshot       *string
	OrganizationID *string
	ProjectID      *string
	Namespace      *string
	Workdir        *string
	CPUs           *float64
	MemoryMB       *int
	DiskMB         *int
	TimeoutSecs    *int
	NoInternet     *bool
}

// RegisterTensorlakeConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTensorlakeConfigFlags(fs *flag.FlagSet, defaults TensorlakeConfig) TensorlakeConfigFlagValues {
	return TensorlakeConfigFlagValues{
		APIURL:         fs.String("tensorlake-api-url", defaults.APIURL, "Tensorlake API base URL"),
		CLIPath:        fs.String("tensorlake-cli", defaults.CLIPath, "Path to the tensorlake CLI binary"),
		Image:          fs.String("tensorlake-image", defaults.Image, "Tensorlake sandbox image name"),
		Snapshot:       fs.String("tensorlake-snapshot", defaults.Snapshot, "Tensorlake snapshot ID to restore from"),
		OrganizationID: fs.String("tensorlake-organization-id", defaults.OrganizationID, "Tensorlake organization ID"),
		ProjectID:      fs.String("tensorlake-project-id", defaults.ProjectID, "Tensorlake project ID"),
		Namespace:      fs.String("tensorlake-namespace", defaults.Namespace, "Tensorlake namespace"),
		Workdir:        fs.String("tensorlake-workdir", defaults.Workdir, "Absolute working directory inside the sandbox (also used as sync target)"),
		CPUs:           fs.Float64("tensorlake-cpus", defaults.CPUs, "Tensorlake sandbox CPU count"),
		MemoryMB:       fs.Int("tensorlake-memory-mb", defaults.MemoryMB, "Tensorlake sandbox memory in MB"),
		DiskMB:         fs.Int("tensorlake-disk-mb", defaults.DiskMB, "Tensorlake sandbox root disk in MB"),
		TimeoutSecs:    fs.Int("tensorlake-timeout-secs", defaults.TimeoutSecs, "Tensorlake sandbox lifetime timeout in seconds"),
		NoInternet:     fs.Bool("tensorlake-no-internet", defaults.NoInternet, "Block outbound internet from the sandbox"),
	}
}

// TensorlakeConfigVisitedFlags records raw flag visits, independently of application.
type TensorlakeConfigVisitedFlags struct {
	APIURL bool
}

// TensorlakeConfigFlagPresence reports visits for tracked flag bindings.
func TensorlakeConfigFlagPresence(fs *flag.FlagSet) TensorlakeConfigVisitedFlags {
	return TensorlakeConfigVisitedFlags{
		APIURL: flagWasSet(fs, "tensorlake-api-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TensorlakeConfigFlagValues) Apply(cfg *TensorlakeConfig, fs *flag.FlagSet) (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	visited := TensorlakeConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.InputAccepted = true
		applied.APIURL = true
	}
	if flagWasSet(fs, "tensorlake-cli") {
		cfg.CLIPath = *values.CLIPath
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-snapshot") {
		cfg.Snapshot = *values.Snapshot
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-organization-id") {
		cfg.OrganizationID = *values.OrganizationID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-project-id") {
		cfg.ProjectID = *values.ProjectID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-namespace") {
		cfg.Namespace = *values.Namespace
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-workdir") {
		cfg.Workdir = *values.Workdir
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-cpus") {
		cfg.CPUs = *values.CPUs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-memory-mb") {
		cfg.MemoryMB = *values.MemoryMB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-disk-mb") {
		cfg.DiskMB = *values.DiskMB
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "tensorlake-no-internet") {
		cfg.NoInternet = *values.NoInternet
		applied.InputAccepted = true
	}
	return applied, nil
}
