// Code generated by scripts/configgen from config_coder.go; DO NOT EDIT.

package cli

import (
	"flag"
	"strings"
)

type fileCoderConfig struct {
	CLIPath              string   `yaml:"cliPath,omitempty"`
	Template             string   `yaml:"template,omitempty"`
	Preset               string   `yaml:"preset,omitempty"`
	WorkspacePrefix      string   `yaml:"workspacePrefix,omitempty"`
	WorkRoot             string   `yaml:"workRoot,omitempty"`
	DeleteOnRelease      *bool    `yaml:"deleteOnRelease,omitempty"`
	Wait                 string   `yaml:"wait,omitempty"`
	UseParameterDefaults *bool    `yaml:"useParameterDefaults,omitempty"`
	Parameters           []string `yaml:"parameters,omitempty"`
	RichParameterFile    string   `yaml:"richParameterFile,omitempty"`
}

const CoderConfigDefaultCLIPath string = "coder"
const CoderConfigDefaultWorkspacePrefix string = "crabbox-"
const CoderConfigDefaultWorkRoot string = "/home/coder/crabbox"
const CoderConfigDefaultWait string = "yes"

func defaultCoderConfig() CoderConfig {
	return CoderConfig{
		CLIPath:         CoderConfigDefaultCLIPath,
		WorkspacePrefix: CoderConfigDefaultWorkspacePrefix,
		WorkRoot:        CoderConfigDefaultWorkRoot,
		Wait:            CoderConfigDefaultWait,
	}
}

// CoderConfigApplied records accepted assignments during one application.
type CoderConfigApplied struct {
	InputAccepted     bool
	CLIPath           bool
	WorkRoot          bool
	RichParameterFile bool
}

func (cfg *CoderConfig) applyFile(file *fileCoderConfig) (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "coder")
	return applied, err
}

func (cfg *CoderConfig) applyEnv() (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// CoderConfigFlagValues holds parsed values; only visited flags are applied.
type CoderConfigFlagValues struct {
	CLIPath              *string
	Template             *string
	Preset               *string
	WorkspacePrefix      *string
	WorkRoot             *string
	DeleteOnRelease      *bool
	Wait                 *string
	UseParameterDefaults *bool
	Parameters           *string
	RichParameterFile    *string
}

// RegisterCoderConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCoderConfigFlags(fs *flag.FlagSet, defaults CoderConfig) CoderConfigFlagValues {
	return CoderConfigFlagValues{
		CLIPath:              fs.String("coder-cli", defaults.CLIPath, "Coder CLI path"),
		Template:             fs.String("coder-template", defaults.Template, "Coder template for new workspaces"),
		Preset:               fs.String("coder-preset", defaults.Preset, "Coder template preset"),
		WorkspacePrefix:      fs.String("coder-workspace-prefix", defaults.WorkspacePrefix, "prefix for Crabbox-managed Coder workspace names"),
		WorkRoot:             fs.String("coder-work-root", defaults.WorkRoot, "Coder workspace Crabbox work root"),
		DeleteOnRelease:      fs.Bool("coder-delete-on-release", defaults.DeleteOnRelease, "delete Coder workspace on release instead of stopping it"),
		Wait:                 fs.String("coder-wait", defaults.Wait, "Coder SSH startup wait mode: yes, no, or auto"),
		UseParameterDefaults: fs.Bool("coder-use-parameter-defaults", defaults.UseParameterDefaults, "pass --use-parameter-defaults to coder create"),
		Parameters:           fs.String("coder-parameter", strings.Join(defaults.Parameters, ","), "comma-separated Coder parameter values name=value"),
		RichParameterFile:    fs.String("coder-rich-parameter-file", defaults.RichParameterFile, "Coder rich parameter file"),
	}
}

// CoderConfigVisitedFlags records raw flag visits, independently of application.
type CoderConfigVisitedFlags struct {
	CLIPath           bool
	WorkRoot          bool
	RichParameterFile bool
}

// CoderConfigFlagPresence reports visits for tracked flag bindings.
func CoderConfigFlagPresence(fs *flag.FlagSet) CoderConfigVisitedFlags {
	return CoderConfigVisitedFlags{
		CLIPath:           flagWasSet(fs, "coder-cli"),
		WorkRoot:          flagWasSet(fs, "coder-work-root"),
		RichParameterFile: flagWasSet(fs, "coder-rich-parameter-file"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CoderConfigFlagValues) Apply(cfg *CoderConfig, fs *flag.FlagSet) (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	visited := CoderConfigFlagPresence(fs)
	if visited.CLIPath {
		cfg.CLIPath = *values.CLIPath
		applied.InputAccepted = true
		applied.CLIPath = true
	}
	if flagWasSet(fs, "coder-template") {
		cfg.Template = *values.Template
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "coder-preset") {
		cfg.Preset = *values.Preset
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "coder-workspace-prefix") {
		cfg.WorkspacePrefix = *values.WorkspacePrefix
		applied.InputAccepted = true
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if flagWasSet(fs, "coder-delete-on-release") {
		cfg.DeleteOnRelease = *values.DeleteOnRelease
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "coder-wait") {
		cfg.Wait = *values.Wait
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "coder-use-parameter-defaults") {
		cfg.UseParameterDefaults = *values.UseParameterDefaults
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "coder-parameter") {
		cfg.Parameters = splitCSV(*values.Parameters)
		applied.InputAccepted = true
	}
	if visited.RichParameterFile {
		cfg.RichParameterFile = *values.RichParameterFile
		applied.InputAccepted = true
		applied.RichParameterFile = true
	}
	return applied, nil
}
