// Code generated by scripts/configgen from config_machine0.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileMachine0Config struct {
	CLIPath       string `yaml:"cliPath,omitempty"`
	Image         string `yaml:"image,omitempty"`
	ImageVersion  *int   `yaml:"imageVersion,omitempty"`
	DesktopImage  string `yaml:"desktopImage,omitempty"`
	Size          string `yaml:"size,omitempty"`
	Region        string `yaml:"region,omitempty"`
	Key           string `yaml:"key,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
	ReleasePolicy string `yaml:"releasePolicy,omitempty"`
	CreateTimeout string `yaml:"createTimeout,omitempty"`
	PollInterval  string `yaml:"pollInterval,omitempty"`
}

const Machine0ConfigDefaultCLIPath string = "machine0"
const Machine0ConfigDefaultImage string = "ubuntu-24-04-loaded"
const Machine0ConfigDefaultSize string = "large"
const Machine0ConfigDefaultRegion string = "eu"
const Machine0ConfigDefaultReleasePolicy string = "destroy"
const Machine0ConfigDefaultCreateTimeout time.Duration = 900 * time.Second
const Machine0ConfigDefaultPollInterval time.Duration = 60 * time.Second

func defaultMachine0Config() Machine0Config {
	return Machine0Config{
		CLIPath:       Machine0ConfigDefaultCLIPath,
		Image:         Machine0ConfigDefaultImage,
		Size:          Machine0ConfigDefaultSize,
		Region:        Machine0ConfigDefaultRegion,
		ReleasePolicy: Machine0ConfigDefaultReleasePolicy,
		CreateTimeout: Machine0ConfigDefaultCreateTimeout,
		PollInterval:  Machine0ConfigDefaultPollInterval,
	}
}

// Machine0ConfigApplied records accepted assignments during one application.
type Machine0ConfigApplied struct {
	InputAccepted bool
	Size          bool
	WorkRoot      bool
}

func (cfg *Machine0Config) applyFile(file *fileMachine0Config) (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.CLIPath != "" {
		cfg.CLIPath = file.CLIPath
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
	}
	if file.ImageVersion != nil {
		cfg.ImageVersion = *file.ImageVersion
		applied.InputAccepted = true
	}
	if file.DesktopImage != "" {
		cfg.DesktopImage = file.DesktopImage
		applied.InputAccepted = true
	}
	if file.Size != "" {
		cfg.Size = file.Size
		applied.InputAccepted = true
		applied.Size = true
	}
	if file.Region != "" {
		cfg.Region = file.Region
		applied.InputAccepted = true
	}
	if file.Key != "" {
		cfg.Key = file.Key
		applied.InputAccepted = true
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if file.ReleasePolicy != "" {
		cfg.ReleasePolicy = file.ReleasePolicy
		applied.InputAccepted = true
	}
	if file.CreateTimeout != "" {
		if applyLeaseDuration(&cfg.CreateTimeout, file.CreateTimeout) {
			applied.InputAccepted = true
		}
	}
	if file.PollInterval != "" {
		if applyLeaseDuration(&cfg.PollInterval, file.PollInterval) {
			applied.InputAccepted = true
		}
	}
	return applied, nil
}

func (cfg *Machine0Config) applyEnv() (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 11)
	return applied, err
}

// Machine0ConfigFlagValues holds parsed values; only visited flags are applied.
type Machine0ConfigFlagValues struct {
	CLIPath       *string
	Image         *string
	ImageVersion  *int
	DesktopImage  *string
	Size          *string
	Region        *string
	Key           *string
	WorkRoot      *string
	ReleasePolicy *string
	CreateTimeout *string
	PollInterval  *string
}

// RegisterMachine0ConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMachine0ConfigFlags(fs *flag.FlagSet, defaults Machine0Config) Machine0ConfigFlagValues {
	return Machine0ConfigFlagValues{
		CLIPath:       fs.String("machine0-cli", defaults.CLIPath, "Machine0 CLI path"),
		Image:         fs.String("machine0-image", defaults.Image, "Machine0 image name"),
		ImageVersion:  fs.Int("machine0-image-version", defaults.ImageVersion, "Machine0 image version; 0 uses the active version"),
		DesktopImage:  fs.String("machine0-desktop-image", defaults.DesktopImage, "optional prepared Machine0 image for --desktop leases"),
		Size:          fs.String("machine0-size", defaults.Size, "Machine0 live-catalog size slug"),
		Region:        fs.String("machine0-region", defaults.Region, "Machine0 region"),
		Key:           fs.String("machine0-key", defaults.Key, "Machine0 registered SSH key name; empty uses the Machine0 default"),
		WorkRoot:      fs.String("machine0-work-root", defaults.WorkRoot, "remote Crabbox work root"),
		ReleasePolicy: fs.String("machine0-release-policy", defaults.ReleasePolicy, "release policy: destroy or explicit suspend"),
		CreateTimeout: fs.String("machine0-create-timeout", defaults.CreateTimeout.String(), "Machine0 creation timeout"),
		PollInterval:  fs.String("machine0-poll-interval", defaults.PollInterval.String(), "Machine0 status polling interval"),
	}
}

// Machine0ConfigVisitedFlags records raw flag visits, independently of application.
type Machine0ConfigVisitedFlags struct {
	Size     bool
	WorkRoot bool
}

// Machine0ConfigFlagPresence reports visits for tracked flag bindings.
func Machine0ConfigFlagPresence(fs *flag.FlagSet) Machine0ConfigVisitedFlags {
	return Machine0ConfigVisitedFlags{
		Size:     flagWasSet(fs, "machine0-size"),
		WorkRoot: flagWasSet(fs, "machine0-work-root"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values Machine0ConfigFlagValues) Apply(cfg *Machine0Config, fs *flag.FlagSet) (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	visited := Machine0ConfigFlagPresence(fs)
	if flagWasSet(fs, "machine0-cli") {
		cfg.CLIPath = *values.CLIPath
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "machine0-image") {
		cfg.Image = *values.Image
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "machine0-image-version") {
		cfg.ImageVersion = *values.ImageVersion
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "machine0-desktop-image") {
		cfg.DesktopImage = *values.DesktopImage
		applied.InputAccepted = true
	}
	if visited.Size {
		cfg.Size = *values.Size
		applied.InputAccepted = true
		applied.Size = true
	}
	if flagWasSet(fs, "machine0-region") {
		cfg.Region = *values.Region
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "machine0-key") {
		cfg.Key = *values.Key
		applied.InputAccepted = true
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.InputAccepted = true
		applied.WorkRoot = true
	}
	if flagWasSet(fs, "machine0-release-policy") {
		cfg.ReleasePolicy = *values.ReleasePolicy
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "machine0-create-timeout") {
		if err := ApplyLeaseDuration(&cfg.CreateTimeout, *values.CreateTimeout); err != nil {
			return applied, err
		} else if *values.CreateTimeout != "" {
			applied.InputAccepted = true
		}
	}
	if flagWasSet(fs, "machine0-poll-interval") {
		if err := ApplyLeaseDuration(&cfg.PollInterval, *values.PollInterval); err != nil {
			return applied, err
		} else if *values.PollInterval != "" {
			applied.InputAccepted = true
		}
	}
	return applied, nil
}
