// Code generated by scripts/configgen from config_linode.go; DO NOT EDIT.

package cli

import (
	"os"
)

type fileLinodeConfig struct {
	Region     string   `yaml:"region,omitempty"`
	Image      string   `yaml:"image,omitempty"`
	Type       string   `yaml:"type,omitempty"`
	FirewallID string   `yaml:"firewall,omitempty"`
	SSHCIDRs   []string `yaml:"sshCIDRs,omitempty"`
}

func defaultLinodeConfig() LinodeConfig {
	return LinodeConfig{}
}

// LinodeConfigApplied records accepted assignments during one application.
type LinodeConfigApplied struct {
	InputAccepted bool
	Image         bool
	Type          bool
}

func (cfg *LinodeConfig) applyFile(file *fileLinodeConfig) (LinodeConfigApplied, error) {
	var applied LinodeConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Region != "" {
		cfg.Region = file.Region
		applied.InputAccepted = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.InputAccepted = true
		applied.Image = true
	}
	if file.Type != "" {
		cfg.Type = file.Type
		applied.InputAccepted = true
		applied.Type = true
	}
	if file.FirewallID != "" {
		cfg.FirewallID = file.FirewallID
		applied.InputAccepted = true
	}
	if len(file.SSHCIDRs) > 0 {
		cfg.SSHCIDRs = file.SSHCIDRs
		applied.InputAccepted = true
	}
	return applied, nil
}

func (cfg *LinodeConfig) applyEnv() (LinodeConfigApplied, error) {
	var applied LinodeConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_LINODE_REGION"); ok {
		cfg.Region = value
		applied.InputAccepted = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_LINODE_IMAGE"); ok {
		cfg.Image = value
		applied.InputAccepted = true
		applied.Image = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_LINODE_TYPE"); ok {
		cfg.Type = value
		applied.InputAccepted = true
		applied.Type = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_LINODE_FIREWALL"); ok {
		cfg.FirewallID = value
		applied.InputAccepted = true
	}
	if value := os.Getenv("CRABBOX_LINODE_SSH_CIDRS"); value != "" {
		cfg.SSHCIDRs = splitCommaList(value)
		applied.InputAccepted = true
	}
	return applied, nil
}
