// Code generated by scripts/configgen from config_ovh.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOVHConfig struct {
	Endpoint  string `yaml:"endpoint,omitempty"`
	ProjectID string `yaml:"projectId,omitempty"`
	Region    string `yaml:"region,omitempty"`
	Image     string `yaml:"image,omitempty"`
	Flavor    string `yaml:"flavor,omitempty"`
}

const OVHConfigDefaultEndpoint string = "https://api.us.ovhcloud.com/1.0"
const OVHConfigDefaultImage string = "Ubuntu 24.04"
const OVHConfigDefaultFlavor string = "b3-8"

func defaultOVHConfig() OVHConfig {
	return OVHConfig{
		Endpoint: OVHConfigDefaultEndpoint,
		Image:    OVHConfigDefaultImage,
		Flavor:   OVHConfigDefaultFlavor,
	}
}

// OVHConfigApplied records accepted assignments during one application.
type OVHConfigApplied struct {
	InputAccepted bool
	Image         bool
}

func (cfg *OVHConfig) applyFile(file *fileOVHConfig, trusted bool) (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "ovh")
	return applied, err
}

func (cfg *OVHConfig) applyEnv() (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// OVHConfigFlagValues holds parsed values; only visited flags are applied.
type OVHConfigFlagValues struct {
	Endpoint  *string
	ProjectID *string
	Region    *string
	Image     *string
	Flavor    *string
}

// RegisterOVHConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOVHConfigFlags(fs *flag.FlagSet, defaults OVHConfig) OVHConfigFlagValues {
	return OVHConfigFlagValues{
		Endpoint:  fs.String("ovh-endpoint", defaults.Endpoint, "OVHcloud API endpoint"),
		ProjectID: fs.String("ovh-project-id", defaults.ProjectID, "OVHcloud Public Cloud project ID"),
		Region:    fs.String("ovh-region", defaults.Region, "OVHcloud Public Cloud region"),
		Image:     fs.String("ovh-image", defaults.Image, "OVHcloud Public Cloud image name or ID"),
		Flavor:    fs.String("ovh-flavor", defaults.Flavor, "OVHcloud Public Cloud flavor name or ID"),
	}
}

// OVHConfigVisitedFlags records raw flag visits, independently of application.
type OVHConfigVisitedFlags struct {
	Image bool
}

// OVHConfigFlagPresence reports visits for tracked flag bindings.
func OVHConfigFlagPresence(fs *flag.FlagSet) OVHConfigVisitedFlags {
	return OVHConfigVisitedFlags{
		Image: flagWasSet(fs, "ovh-image"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OVHConfigFlagValues) Apply(cfg *OVHConfig, fs *flag.FlagSet) (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	visited := OVHConfigFlagPresence(fs)
	if flagWasSet(fs, "ovh-endpoint") {
		cfg.Endpoint = *values.Endpoint
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "ovh-project-id") {
		cfg.ProjectID = *values.ProjectID
		applied.InputAccepted = true
	}
	if flagWasSet(fs, "ovh-region") {
		cfg.Region = *values.Region
		applied.InputAccepted = true
	}
	if visited.Image {
		cfg.Image = *values.Image
		applied.InputAccepted = true
		applied.Image = true
	}
	if flagWasSet(fs, "ovh-flavor") {
		cfg.Flavor = *values.Flavor
		applied.InputAccepted = true
	}
	return applied, nil
}
