// Code generated by scripts/configgen from config_vercel_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
	"strings"
)

type fileVercelSandboxConfig struct {
	Runtime         *string   `yaml:"runtime,omitempty"`
	Workdir         *string   `yaml:"workdir,omitempty"`
	ProjectID       *string   `yaml:"projectId,omitempty"`
	TeamID          *string   `yaml:"teamId,omitempty"`
	Scope           *string   `yaml:"scope,omitempty"`
	VCPUs           *float64  `yaml:"vcpus,omitempty"`
	TimeoutSecs     *int      `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int      `yaml:"execTimeoutSecs,omitempty"`
	Persistent      *bool     `yaml:"persistent,omitempty"`
	Snapshot        *string   `yaml:"snapshot,omitempty"`
	SnapshotMode    *string   `yaml:"snapshotMode,omitempty"`
	NetworkPolicy   *string   `yaml:"networkPolicy,omitempty"`
	NetworkAllow    *[]string `yaml:"networkAllow,omitempty"`
	NetworkDeny     *[]string `yaml:"networkDeny,omitempty"`
	Ports           *[]string `yaml:"ports,omitempty"`
	ForgetMissing   *bool     `yaml:"forgetMissing,omitempty"`
}

const VercelSandboxConfigDefaultRuntime string = "node24"
const VercelSandboxConfigDefaultWorkdir string = "/vercel/sandbox/crabbox"
const VercelSandboxConfigDefaultExecTimeoutSecs int = 600
const VercelSandboxConfigDefaultNetworkPolicy string = "default"

func defaultVercelSandboxConfig() VercelSandboxConfig {
	return VercelSandboxConfig{
		Runtime:         VercelSandboxConfigDefaultRuntime,
		Workdir:         VercelSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: VercelSandboxConfigDefaultExecTimeoutSecs,
		NetworkPolicy:   VercelSandboxConfigDefaultNetworkPolicy,
	}
}

func (cfg *VercelSandboxConfig) applyFile(file *fileVercelSandboxConfig) error {
	if file == nil {
		return nil
	}
	if file.Runtime != nil {
		cfg.Runtime = *file.Runtime
	}
	if file.Workdir != nil {
		cfg.Workdir = *file.Workdir
	}
	if file.ProjectID != nil {
		cfg.ProjectID = *file.ProjectID
	}
	if file.TeamID != nil {
		cfg.TeamID = *file.TeamID
	}
	if file.Scope != nil {
		cfg.Scope = *file.Scope
	}
	if file.VCPUs != nil {
		cfg.VCPUs = *file.VCPUs
	}
	if file.TimeoutSecs != nil {
		if *file.TimeoutSecs < 0 {
			return exit(2, "vercel-sandbox timeoutSecs must be non-negative")
		}
		cfg.TimeoutSecs = *file.TimeoutSecs
	}
	if file.ExecTimeoutSecs != nil {
		if *file.ExecTimeoutSecs < 0 {
			return exit(2, "vercel-sandbox execTimeoutSecs must be non-negative")
		}
		cfg.ExecTimeoutSecs = *file.ExecTimeoutSecs
	}
	if file.Persistent != nil {
		cfg.Persistent = *file.Persistent
	}
	if file.Snapshot != nil {
		cfg.Snapshot = *file.Snapshot
	}
	if file.SnapshotMode != nil {
		cfg.SnapshotMode = *file.SnapshotMode
	}
	if file.NetworkPolicy != nil {
		cfg.NetworkPolicy = *file.NetworkPolicy
	}
	if file.NetworkAllow != nil {
		cfg.NetworkAllow = normalizeList(*file.NetworkAllow)
	}
	if file.NetworkDeny != nil {
		cfg.NetworkDeny = normalizeList(*file.NetworkDeny)
	}
	if file.Ports != nil {
		cfg.Ports = normalizeList(*file.Ports)
	}
	if file.ForgetMissing != nil {
		cfg.ForgetMissing = *file.ForgetMissing
	}
	return nil
}

func (cfg *VercelSandboxConfig) applyEnv() error {
	cfg.Runtime = getenv("CRABBOX_VERCEL_SANDBOX_RUNTIME", cfg.Runtime)
	cfg.Workdir = getenv("CRABBOX_VERCEL_SANDBOX_WORKDIR", cfg.Workdir)
	cfg.ProjectID = getenv("CRABBOX_VERCEL_SANDBOX_PROJECT_ID", cfg.ProjectID)
	cfg.TeamID = getenv("CRABBOX_VERCEL_SANDBOX_TEAM_ID", cfg.TeamID)
	cfg.Scope = getenv("CRABBOX_VERCEL_SANDBOX_SCOPE", cfg.Scope)
	cfg.VCPUs = getenvFloat("CRABBOX_VERCEL_SANDBOX_VCPUS", cfg.VCPUs)
	{
		var err error
		cfg.TimeoutSecs, err = getenvNonNegativeInt("CRABBOX_VERCEL_SANDBOX_TIMEOUT_SECS", cfg.TimeoutSecs)
		if err != nil {
			return err
		}
	}
	{
		var err error
		cfg.ExecTimeoutSecs, err = getenvNonNegativeInt("CRABBOX_VERCEL_SANDBOX_EXEC_TIMEOUT_SECS", cfg.ExecTimeoutSecs)
		if err != nil {
			return err
		}
	}
	if value, ok := getenvBool("CRABBOX_VERCEL_SANDBOX_PERSISTENT"); ok {
		cfg.Persistent = value
	}
	cfg.Snapshot = getenv("CRABBOX_VERCEL_SANDBOX_SNAPSHOT", cfg.Snapshot)
	cfg.SnapshotMode = getenv("CRABBOX_VERCEL_SANDBOX_SNAPSHOT_MODE", cfg.SnapshotMode)
	cfg.NetworkPolicy = getenv("CRABBOX_VERCEL_SANDBOX_NETWORK_POLICY", cfg.NetworkPolicy)
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_NETWORK_ALLOW"); value != "" {
		cfg.NetworkAllow = splitCommaList(value)
	}
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_NETWORK_DENY"); value != "" {
		cfg.NetworkDeny = splitCommaList(value)
	}
	if value := os.Getenv("CRABBOX_VERCEL_SANDBOX_PORTS"); value != "" {
		cfg.Ports = splitCommaList(value)
	}
	if value, ok := getenvBool("CRABBOX_VERCEL_SANDBOX_FORGET_MISSING"); ok {
		cfg.ForgetMissing = value
	}
	return nil
}

// VercelSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type VercelSandboxConfigFlagValues struct {
	Runtime         *string
	Workdir         *string
	ProjectID       *string
	TeamID          *string
	Scope           *string
	VCPUs           *float64
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Persistent      *bool
	Snapshot        *string
	SnapshotMode    *string
	NetworkPolicy   *string
	NetworkAllow    *string
	NetworkDeny     *string
	Ports           *string
	ForgetMissing   *bool
}

// RegisterVercelSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVercelSandboxConfigFlags(fs *flag.FlagSet, defaults VercelSandboxConfig) VercelSandboxConfigFlagValues {
	return VercelSandboxConfigFlagValues{
		Runtime:         fs.String("vercel-sandbox-runtime", defaults.Runtime, "Vercel Sandbox runtime (node26, node24, node22, python3.13)"),
		Workdir:         fs.String("vercel-sandbox-workdir", defaults.Workdir, "Absolute working directory inside the sandbox"),
		ProjectID:       fs.String("vercel-sandbox-project-id", defaults.ProjectID, "Vercel project ID used for sandbox scoping"),
		TeamID:          fs.String("vercel-sandbox-team-id", defaults.TeamID, "Vercel team ID used for sandbox scoping"),
		Scope:           fs.String("vercel-sandbox-scope", defaults.Scope, "Vercel account or team slug used for sandbox scoping"),
		VCPUs:           fs.Float64("vercel-sandbox-vcpus", defaults.VCPUs, "requested Vercel Sandbox vCPU count (0 = service default)"),
		TimeoutSecs:     fs.Int("vercel-sandbox-timeout-secs", defaults.TimeoutSecs, "sandbox lifetime cap in seconds (0 = service default)"),
		ExecTimeoutSecs: fs.Int("vercel-sandbox-exec-timeout-secs", defaults.ExecTimeoutSecs, "command timeout in seconds (0 = service default)"),
		Persistent:      fs.Bool("vercel-sandbox-persistent", defaults.Persistent, "request a persistent sandbox when lifecycle support lands"),
		Snapshot:        fs.String("vercel-sandbox-snapshot", defaults.Snapshot, "snapshot/checkpoint name or ID for future lifecycle use"),
		SnapshotMode:    fs.String("vercel-sandbox-snapshot-mode", defaults.SnapshotMode, "snapshot/checkpoint mode for future lifecycle use"),
		NetworkPolicy:   fs.String("vercel-sandbox-network-policy", defaults.NetworkPolicy, "sandbox network policy: default, public, private, restricted, or none"),
		NetworkAllow:    fs.String("vercel-sandbox-network-allow", strings.Join(defaults.NetworkAllow, ","), "comma-separated outbound CIDR/domain allow list"),
		NetworkDeny:     fs.String("vercel-sandbox-network-deny", strings.Join(defaults.NetworkDeny, ","), "comma-separated outbound IP/CIDR deny list"),
		Ports:           fs.String("vercel-sandbox-ports", strings.Join(defaults.Ports, ","), "comma-separated ports or ranges to expose later"),
		ForgetMissing:   fs.Bool("vercel-sandbox-forget-missing", defaults.ForgetMissing, "remove the local claim when stop gets 404 (explicit stale-claim cleanup)"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VercelSandboxConfigFlagValues) Apply(cfg *VercelSandboxConfig, fs *flag.FlagSet) {
	if flagWasSet(fs, "vercel-sandbox-runtime") {
		cfg.Runtime = *values.Runtime
	}
	if flagWasSet(fs, "vercel-sandbox-workdir") {
		cfg.Workdir = *values.Workdir
	}
	if flagWasSet(fs, "vercel-sandbox-project-id") {
		cfg.ProjectID = *values.ProjectID
	}
	if flagWasSet(fs, "vercel-sandbox-team-id") {
		cfg.TeamID = *values.TeamID
	}
	if flagWasSet(fs, "vercel-sandbox-scope") {
		cfg.Scope = *values.Scope
	}
	if flagWasSet(fs, "vercel-sandbox-vcpus") {
		cfg.VCPUs = *values.VCPUs
	}
	if flagWasSet(fs, "vercel-sandbox-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
	}
	if flagWasSet(fs, "vercel-sandbox-exec-timeout-secs") {
		cfg.ExecTimeoutSecs = *values.ExecTimeoutSecs
	}
	if flagWasSet(fs, "vercel-sandbox-persistent") {
		cfg.Persistent = *values.Persistent
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot") {
		cfg.Snapshot = *values.Snapshot
	}
	if flagWasSet(fs, "vercel-sandbox-snapshot-mode") {
		cfg.SnapshotMode = *values.SnapshotMode
	}
	if flagWasSet(fs, "vercel-sandbox-network-policy") {
		cfg.NetworkPolicy = *values.NetworkPolicy
	}
	if flagWasSet(fs, "vercel-sandbox-network-allow") {
		cfg.NetworkAllow = splitCommaList(*values.NetworkAllow)
	}
	if flagWasSet(fs, "vercel-sandbox-network-deny") {
		cfg.NetworkDeny = splitCommaList(*values.NetworkDeny)
	}
	if flagWasSet(fs, "vercel-sandbox-ports") {
		cfg.Ports = splitCommaList(*values.Ports)
	}
	if flagWasSet(fs, "vercel-sandbox-forget-missing") {
		cfg.ForgetMissing = *values.ForgetMissing
	}
}
