// Code generated by scripts/generate-linux-readiness.mjs; DO NOT EDIT.

package cli

const linuxReadinessManifestPath = "/var/lib/crabbox/readiness/linux.json"
const linuxMinimalRecipeDigest = "sha256:80ea099bb12e3c925240137dedf0b537ec75d32ba3d1a0818ef4a7f6dc0b9c25"
const linuxBuilderRecipeDigest = "sha256:a22a8951a217250ffc59f43d17f2a5eda12c4e062deb4844f22ca755a1c1f51a"
const linuxMinimalReadinessBootstrap = `crabbox_readiness_manifest_path='/var/lib/crabbox/readiness/linux.json'
crabbox_legacy_image_marker_path='/var/lib/crabbox/image-ready'
crabbox_readiness_schema='crabbox-linux-readiness/v1'
crabbox_minimal_profile='linux-minimal'
crabbox_minimal_recipe_digest='sha256:80ea099bb12e3c925240137dedf0b537ec75d32ba3d1a0818ef4a7f6dc0b9c25'
crabbox_builder_profile='linux-builder'
crabbox_builder_recipe_digest='sha256:a22a8951a217250ffc59f43d17f2a5eda12c4e062deb4844f22ca755a1c1f51a'
crabbox_readiness_packages='ca-certificates curl git jq openssh-server rsync tmux util-linux'
crabbox_readiness_sshd_path='/usr/sbin/sshd'
crabbox_readiness_ca_path='/etc/ssl/certs/ca-certificates.crt'
crabbox_minimal_readiness_probes() {
  test -x '/usr/sbin/sshd' &&
  test -s '/etc/ssl/certs/ca-certificates.crt' &&
  curl --version >/dev/null &&
  git --version >/dev/null &&
  rsync --version >/dev/null &&
  jq --version >/dev/null &&
  tmux -V >/dev/null &&
  flock --version >/dev/null
}
crabbox_readiness_manifest_matches() {
  test -f "$crabbox_readiness_manifest_path" &&
  test ! -L "$crabbox_readiness_manifest_path" &&
  test "$(stat -c '%u:%a' "$crabbox_readiness_manifest_path" 2>/dev/null)" = "0:644" &&
  command -v jq >/dev/null &&
  jq -e     --arg schema "$crabbox_readiness_schema"     --arg minimalProfile "$crabbox_minimal_profile"     --arg minimalDigest "$crabbox_minimal_recipe_digest"     --arg builderProfile "$crabbox_builder_profile"     --arg builderDigest "$crabbox_builder_recipe_digest"     'type == "object" and
      .schema == $schema and
      (.inventoryDigest | type == "string" and test("^sha256:[0-9a-f]{64}$")) and
      (
        (.profile == $minimalProfile and .recipeDigest == $minimalDigest) or
        (.profile == $builderProfile and .recipeDigest == $builderDigest)
      ) and
      (keys | sort) == ["inventoryDigest", "profile", "recipeDigest", "schema"]'     "$crabbox_readiness_manifest_path" >/dev/null &&
  crabbox_minimal_readiness_probes
}
crabbox_probe_inventory_digest() {
  local command_name command_path
  {
    printf '%s\n' "$crabbox_minimal_recipe_digest"
    sha256sum "$crabbox_readiness_sshd_path" "$crabbox_readiness_ca_path"
    for command_name in curl git rsync jq tmux flock; do
      command_path="$(command -v "$command_name")"
      printf '%s\n' "$command_path"
      sha256sum "$command_path"
    done
  } | LC_ALL=C sort | sha256sum | awk '{print "sha256:" $1}'
}
crabbox_package_inventory_digest() {
  dpkg-query -W -f='${binary:Package}=${Version}\n' 'ca-certificates' 'curl' 'git' 'jq' 'openssh-server' 'rsync' 'tmux' 'util-linux' |
    LC_ALL=C sort |
    sha256sum |
    awk '{print "sha256:" $1}'
}
crabbox_write_readiness_manifest() {
  local profile="$1" recipe_digest="$2" inventory_digest="$3"
  local manifest_dir manifest_tmp
  manifest_dir="$(dirname "$crabbox_readiness_manifest_path")"
  install -d -m 0755 -o root -g root "$manifest_dir"
  manifest_tmp="$(mktemp "$manifest_dir/.linux.json.XXXXXX")"
  printf '{"inventoryDigest":"%s","profile":"%s","recipeDigest":"%s","schema":"%s"}\n'     "$inventory_digest"     "$profile"     "$recipe_digest"     "$crabbox_readiness_schema" >"$manifest_tmp"
  chown 'root:root' "$manifest_tmp"
  chmod 0644 "$manifest_tmp"
  mv -f "$manifest_tmp" "$crabbox_readiness_manifest_path"
}
if crabbox_readiness_manifest_matches; then
  echo 'crabbox Linux readiness manifest verified; skipping apt bootstrap'
elif test -f "$crabbox_legacy_image_marker_path" &&
  test ! -L "$crabbox_legacy_image_marker_path" &&
  crabbox_minimal_readiness_probes; then
  crabbox_write_readiness_manifest     "$crabbox_minimal_profile"     "$crabbox_minimal_recipe_digest"     "$(crabbox_probe_inventory_digest)"
  echo 'crabbox legacy image readiness migrated without package-manager work'
else
  cat >'/etc/apt/apt.conf.d/80-crabbox-retries' <<'APT'
Acquire::Retries "8";
Acquire::http::Timeout "30";
Acquire::https::Timeout "30";
APT
  retry apt-get update
  retry apt-get install -y --no-install-recommends $crabbox_readiness_packages
  crabbox_minimal_readiness_probes
  crabbox_write_readiness_manifest     "$crabbox_minimal_profile"     "$crabbox_minimal_recipe_digest"     "$(crabbox_package_inventory_digest)"
fi`
