// Code generated by scripts/generate-bootstrap.mjs from recipes/bootstrap/v1; DO NOT EDIT.

package cli

const defaultOSImage = "ubuntu:26.04"
const supportedOSImages = "ubuntu:26.04, ubuntu:24.04"

type osImageSpec struct {
	Selector        string
	AWSName         string
	AWSArm64Name    string
	AWSLabel        string
	AzureImage      string
	AzureArm64Image string
	GCPImage        string
	HetznerImage    string
	LinodeImage     string
	DockerImage     string
	ContainerName   string
	AppleVMImage    string
	AppleVMSHA256   string
}

var osImageAliases = map[string]string{
	"ubuntu2404":  "ubuntu:24.04",
	"ubuntu:2404": "ubuntu:24.04",
	"ubuntu2604":  "ubuntu:26.04",
	"ubuntu:2604": "ubuntu:26.04",
}

var osImageSpecs = map[string]osImageSpec{
	"ubuntu:24.04": {
		Selector:        "ubuntu:24.04",
		AWSName:         "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*",
		AWSArm64Name:    "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-*",
		AWSLabel:        "Ubuntu 24.04",
		AzureImage:      "Canonical:ubuntu-24_04-lts:server:latest",
		AzureArm64Image: "Canonical:ubuntu-24_04-lts:server-arm64:latest",
		GCPImage:        "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64",
		HetznerImage:    "ubuntu-24.04",
		LinodeImage:     "linode/ubuntu24.04",
		DockerImage:     "docker.io/library/ubuntu:24.04",
		ContainerName:   "docker.io/library/ubuntu@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517",
		AppleVMImage:    "https://cloud-images.ubuntu.com/releases/noble/release-20260518/ubuntu-24.04-server-cloudimg-arm64.img",
		AppleVMSHA256:   "6a61b967ba4a27dd1966f835a67643073ed55c2860ce3dc1cb0517282e6b8bec",
	},
	"ubuntu:26.04": {
		Selector:        "ubuntu:26.04",
		AWSName:         "ubuntu/images/hvm-ssd-gp3/ubuntu-resolute-26.04-amd64-server-*",
		AWSArm64Name:    "ubuntu/images/hvm-ssd-gp3/ubuntu-resolute-26.04-arm64-server-*",
		AWSLabel:        "Ubuntu 26.04",
		AzureImage:      "Canonical:ubuntu-26_04-lts:server:latest",
		AzureArm64Image: "Canonical:ubuntu-26_04-lts:server-arm64:latest",
		GCPImage:        "projects/ubuntu-os-cloud/global/images/family/ubuntu-2604-lts-amd64",
		HetznerImage:    "ubuntu-24.04",
		LinodeImage:     "",
		DockerImage:     "docker.io/library/ubuntu:26.04",
		ContainerName:   "docker.io/library/ubuntu@sha256:2260313b31c8c011cd2eebe728008efac1b3982be73eb71348ea2648d2c0e09b",
		AppleVMImage:    "https://cloud-images.ubuntu.com/releases/resolute/release-20260731/ubuntu-26.04-server-cloudimg-arm64.img",
		AppleVMSHA256:   "3e113fdd41f39e13729375173bb2ae793f87dc6db4294e5251ff2476971788ba",
	},
}
