package main

import (
	"bytes"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sample = "package cli\ntype PilotConfig struct {\n" +
	" Name string `config:\"name\" env:\"PILOT_NAME\" flag:\"pilot-name\" sources:\"user,repo,env,flag\" help:\"Name\" default:\"test\"`\n" +
	" Count int `config:\"count\" env:\"PILOT_COUNT\" flag:\"pilot-count\" sources:\"user,repo,env,flag\" help:\"Count\" default:\"7\" nonnegative:\"true\"`\n" +
	" CPUs float64 `config:\"cpus\" env:\"PILOT_CPUS\" flag:\"pilot-cpus\" sources:\"user,repo,env,flag\" help:\"CPUs\" default:\"0.5\"`\n" +
	" Enabled bool `config:\"enabled\" env:\"PILOT_ENABLED\" flag:\"pilot-enabled\" sources:\"user,repo,env,flag\" help:\"Enabled\" default:\"true\"`\n" +
	" Ports []string `config:\"ports\" env:\"PILOT_PORTS\" flag:\"pilot-ports\" sources:\"user,repo,env,flag\" help:\"Ports\"`\n}"

func TestGenerateDeterministicTypedBindings(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	first, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	typecheckGenerated(t, sample, first)
	second, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("nondeterministic output")
	}
	for _, want := range []string{
		"Code generated by scripts/configgen from pilot.go; DO NOT EDIT.",
		"const PilotConfigDefaultCount int = 7",
		"const PilotConfigDefaultCPUs float64 = 0.5",
		"const PilotConfigDefaultEnabled bool = true",
		"func (cfg *PilotConfig) applyFile(file *filePilotConfig) error",
		"if file.Enabled != nil", "cfg.Ports = normalizeList(*file.Ports)",
		`getenvFloat("PILOT_CPUS", cfg.CPUs)`,
		`getenvNonNegativeInt("PILOT_COUNT", cfg.Count)`,
		`getenvBool("PILOT_ENABLED")`,
		`if value := os.Getenv("PILOT_PORTS"); value != ""`,
		`fs.String("pilot-ports", strings.Join(defaults.Ports, ","), "Ports")`,
		`if flagWasSet(fs, "pilot-enabled")`,
	} {
		if !strings.Contains(string(first), want) {
			t.Fatalf("missing generated binding %q", want)
		}
	}
}

func TestSchemaFailsClosed(t *testing.T) {
	for _, tc := range []struct{ name, old, new, want string }{
		{"source permission", `sources:"user,repo,env,flag"`, `sources:"user,env"`, "explicit sources"},
		{"reordered source permission", `sources:"user,repo,env,flag"`, `sources:"env,user,flag"`, "explicit sources"},
		{"extra source permission", `sources:"user,repo,env,flag"`, `sources:"user,env,flag,secret"`, "explicit sources"},
		{"repo-only source permission", `sources:"user,repo,env,flag"`, `sources:"repo"`, "explicit sources"},
		{"missing source permission", `sources:"user,repo,env,flag"`, "", "explicit sources"},
		{"missing environment", `env:"PILOT_NAME"`, "", "invalid env binding"},
		{"duplicate flag", `flag:"pilot-count"`, `flag:"pilot-name"`, "duplicate flag"},
		{"duplicate key", `config:"count"`, `config:"name"`, "duplicate config"},
		{"duplicate env", `env:"PILOT_COUNT"`, `env:"PILOT_NAME"`, "duplicate env"},
		{"missing help", `help:"Name"`, "", "needs flag help"},
		{"unsupported type", "Name string", "Name map[string]string", "unsupported config type"},
		{"bad default", `default:"7"`, `default:"bad"`, "default:"},
		{"negative default", `default:"7"`, `default:"-1"`, "must be non-negative"},
		{"nonfinite default", `default:"0.5"`, `default:"NaN"`, "default must be finite"},
		{"missing integer policy", `nonnegative:"true"`, "", "require nonnegative policy"},
		{"invalid integer policy", `nonnegative:"true"`, `nonnegative:"false"`, "supported only as true"},
		{"private field", "Name string", "name string", "exported"},
		{"multiple names", "Name string", "Name, Other string", "singly named"},
		{"missing type", "PilotConfig", "OtherConfig", "not found"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(sample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
}

func TestCheckMissingFreshAndStaleOutput(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "pilot.go")
	output := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(source, []byte(sample), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("missing output accepted")
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatal("check created missing output")
	}
	if err := run(source, output, "PilotConfig", "pilot", false); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err != nil {
		t.Fatal(err)
	}
	original, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte(strings.Replace(sample, `default:"7"`, `default:"8"`, 1)), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("stale output accepted")
	}
	current, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(original, current) {
		t.Fatal("check changed output")
	}
}

// Part of ordinary go test ./...: no separate CI registration is required.
func TestVercelSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_vercel_sandbox.go", "../../internal/cli/config_vercel_sandbox_generated.go", "VercelSandboxConfig", "vercel-sandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestCodeSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_codesandbox.go", "../../internal/cli/config_codesandbox_generated.go", "CodeSandboxConfig", "codesandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateScalarOnlyImports(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	s.fields = s.fields[:1]
	// Help text must not influence which Go packages are imported.
	s.fields[0].help = "Use os.Getenv( or strings.Join( in your application"
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	typecheckGenerated(t, sample, output)
	if strings.Contains(string(output), `"os"`) || strings.Contains(string(output), `"strings"`) {
		t.Fatal("scalar-only schema has unused list imports")
	}
}

func TestGenerateTrustedFileBindings(t *testing.T) {
	// Keep a restricted integer between ordinary fields to preserve validation order.
	source := strings.Replace(sample, `sources:"user,repo,env,flag" help:"Count"`, `sources:"user,env,flag" help:"Count"`, 1)
	source = strings.Replace(source, `sources:"user,repo,env,flag" help:"Ports"`, `sources:"user,env,flag" help:"Ports"`, 1)
	s, err := parseSchema([]byte(source), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	for i, f := range s.fields {
		if f.trustedFileOnly != (i == 1 || i == 4) {
			t.Fatalf("%s trusted-file fact = %v", f.name, f.trustedFileOnly)
		}
	}
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	again, err := generate(s, "pilot.go")
	if err != nil || !bytes.Equal(output, again) {
		t.Fatalf("nondeterministic trusted output: %v", err)
	}
	text := string(output)
	previous := -1
	for _, want := range []string{
		"func (cfg *PilotConfig) applyFile(file *filePilotConfig, trusted bool) error",
		"if file.Name != nil {",
		"if trusted && file.Count != nil {\n\t\tif *file.Count < 0 {",
		"cfg.Count = *file.Count",
		"if file.CPUs != nil {",
		"if file.Enabled != nil {",
		"if trusted && file.Ports != nil {\n\t\tcfg.Ports = normalizeList(*file.Ports)",
	} {
		index := strings.Index(text, want)
		if index <= previous {
			t.Fatalf("missing or reordered binding %q", want)
		}
		previous = index
	}
	if strings.Count(text, "trusted &&") != 2 {
		t.Fatal("unexpected file trust guards")
	}
	typecheckGenerated(t, source, output)
}

func typecheckGenerated(t *testing.T, source string, output []byte) {
	t.Helper()
	// Signatures match the handwritten helpers; only generated wiring is checked here.
	const helpers = `package cli
import "flag"
func flagWasSet(*flag.FlagSet, string) bool { panic("stub") }
func exit(int, string) error { panic("stub") }
func getenv(string, string) string { panic("stub") }
func getenvFloat(string, float64) float64 { panic("stub") }
func getenvNonNegativeInt(string, int) (int, error) { panic("stub") }
func getenvBool(string) (bool, bool) { panic("stub") }
func normalizeList([]string) []string { panic("stub") }
func splitCommaList(string) []string { panic("stub") }
`
	fset := token.NewFileSet()
	var files []*ast.File
	for _, input := range []struct{ name, source string }{{"source.go", source}, {"generated.go", string(output)}, {"helpers.go", helpers}} {
		file, err := parser.ParseFile(fset, input.name, input.source, 0)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, file)
	}
	config := types.Config{Importer: importer.Default()}
	if _, err := config.Check("cli", fset, files, nil); err != nil {
		t.Fatal(err)
	}
}
