package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sample = "package cli\ntype PilotConfig struct {\n" +
	" Name string `config:\"name\" env:\"PILOT_NAME\" flag:\"pilot-name\" sources:\"user,repo,env,flag\" help:\"Name\" default:\"test\"`\n" +
	" Count int `config:\"count\" env:\"PILOT_COUNT\" flag:\"pilot-count\" sources:\"user,repo,env,flag\" help:\"Count\" default:\"7\" nonnegative:\"true\"`\n" +
	" CPUs float64 `config:\"cpus\" env:\"PILOT_CPUS\" flag:\"pilot-cpus\" sources:\"user,repo,env,flag\" help:\"CPUs\" default:\"0.5\"`\n" +
	" Enabled bool `config:\"enabled\" env:\"PILOT_ENABLED\" flag:\"pilot-enabled\" sources:\"user,repo,env,flag\" help:\"Enabled\" default:\"true\"`\n" +
	" Ports []string `config:\"ports\" env:\"PILOT_PORTS\" flag:\"pilot-ports\" sources:\"user,repo,env,flag\" help:\"Ports\"`\n}"

func TestGenerateDeterministicTypedBindings(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	first, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	second, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("nondeterministic output")
	}
	for _, want := range []string{
		"Code generated by scripts/configgen from pilot.go; DO NOT EDIT.",
		"const PilotConfigDefaultCount int = 7",
		"const PilotConfigDefaultCPUs float64 = 0.5",
		"const PilotConfigDefaultEnabled bool = true",
		"if file.Enabled != nil", "cfg.Ports = normalizeList(*file.Ports)",
		`getenvFloat("PILOT_CPUS", cfg.CPUs)`,
		`getenvNonNegativeInt("PILOT_COUNT", cfg.Count)`,
		`getenvBool("PILOT_ENABLED")`,
		`if value := os.Getenv("PILOT_PORTS"); value != ""`,
		`fs.String("pilot-ports", strings.Join(defaults.Ports, ","), "Ports")`,
		`if flagWasSet(fs, "pilot-enabled")`,
	} {
		if !strings.Contains(string(first), want) {
			t.Fatalf("missing generated binding %q", want)
		}
	}
}

func TestSchemaFailsClosed(t *testing.T) {
	for _, tc := range []struct{ name, old, new, want string }{
		{"source permission", `sources:"user,repo,env,flag"`, `sources:"user,env"`, "explicit repo-safe sources"},
		{"missing source permission", `sources:"user,repo,env,flag"`, "", "explicit repo-safe sources"},
		{"missing environment", `env:"PILOT_NAME"`, "", "invalid env binding"},
		{"duplicate flag", `flag:"pilot-count"`, `flag:"pilot-name"`, "duplicate flag"},
		{"duplicate key", `config:"count"`, `config:"name"`, "duplicate config"},
		{"duplicate env", `env:"PILOT_COUNT"`, `env:"PILOT_NAME"`, "duplicate env"},
		{"missing help", `help:"Name"`, "", "needs flag help"},
		{"unsupported type", "Name string", "Name map[string]string", "unsupported config type"},
		{"bad default", `default:"7"`, `default:"bad"`, "default:"},
		{"negative default", `default:"7"`, `default:"-1"`, "must be non-negative"},
		{"nonfinite default", `default:"0.5"`, `default:"NaN"`, "default must be finite"},
		{"missing integer policy", `nonnegative:"true"`, "", "require nonnegative policy"},
		{"invalid integer policy", `nonnegative:"true"`, `nonnegative:"false"`, "supported only as true"},
		{"private field", "Name string", "name string", "exported"},
		{"multiple names", "Name string", "Name, Other string", "singly named"},
		{"missing type", "PilotConfig", "OtherConfig", "not found"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(sample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
}

func TestCheckMissingFreshAndStaleOutput(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "pilot.go")
	output := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(source, []byte(sample), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("missing output accepted")
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatal("check created missing output")
	}
	if err := run(source, output, "PilotConfig", "pilot", false); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err != nil {
		t.Fatal(err)
	}
	original, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte(strings.Replace(sample, `default:"7"`, `default:"8"`, 1)), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("stale output accepted")
	}
	current, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(original, current) {
		t.Fatal("check changed output")
	}
}

// Part of ordinary go test ./...: no separate CI registration is required.
func TestVercelSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_vercel_sandbox.go", "../../internal/cli/config_vercel_sandbox_generated.go", "VercelSandboxConfig", "vercel-sandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateScalarOnlyImports(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	s.fields = s.fields[:1]
	// Help text must not influence which Go packages are imported.
	s.fields[0].help = "Use os.Getenv( or strings.Join( in your application"
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(output), `"os"`) || strings.Contains(string(output), `"strings"`) {
		t.Fatal("scalar-only schema has unused list imports")
	}
}
