package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const sample = "package cli\ntype PilotConfig struct {\n" +
	" Name string `config:\"name\" env:\"PILOT_NAME\" flag:\"pilot-name\" sources:\"user,repo,env,flag\" help:\"Name\" default:\"test\"`\n" +
	" Count int `config:\"count\" env:\"PILOT_COUNT\" flag:\"pilot-count\" sources:\"user,repo,env,flag\" help:\"Count\" default:\"7\" nonnegative:\"true\"`\n" +
	" CPUs float64 `config:\"cpus\" env:\"PILOT_CPUS\" flag:\"pilot-cpus\" sources:\"user,repo,env,flag\" help:\"CPUs\" default:\"0.5\"`\n" +
	" Enabled bool `config:\"enabled\" env:\"PILOT_ENABLED\" flag:\"pilot-enabled\" sources:\"user,repo,env,flag\" help:\"Enabled\" default:\"true\"`\n" +
	" Ports []string `config:\"ports\" env:\"PILOT_PORTS\" flag:\"pilot-ports\" sources:\"user,repo,env,flag\" help:\"Ports\"`\n}"

func TestGenerateDeterministicTypedBindings(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	first, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	typecheckGenerated(t, sample, first)
	second, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("nondeterministic output")
	}
	for _, want := range []string{
		"Code generated by scripts/configgen from pilot.go; DO NOT EDIT.",
		"const PilotConfigDefaultCount int = 7",
		"const PilotConfigDefaultCPUs float64 = 0.5",
		"const PilotConfigDefaultEnabled bool = true",
		"func (cfg *PilotConfig) applyFile(file *filePilotConfig) error",
		"if file.Enabled != nil", "cfg.Ports = normalizeList(*file.Ports)",
		`getenvFloat("PILOT_CPUS", cfg.CPUs)`,
		`getenvNonNegativeInt("PILOT_COUNT", cfg.Count)`,
		`getenvBool("PILOT_ENABLED")`,
		`if value := os.Getenv("PILOT_PORTS"); value != ""`,
		`fs.String("pilot-ports", strings.Join(defaults.Ports, ","), "Ports")`,
		`if flagWasSet(fs, "pilot-enabled")`,
	} {
		if !strings.Contains(string(first), want) {
			t.Fatalf("missing generated binding %q", want)
		}
	}
}

func TestSchemaFailsClosed(t *testing.T) {
	for _, tc := range []struct{ name, old, new, want string }{
		{"source permission", `sources:"user,repo,env,flag"`, `sources:"user,env"`, "explicit sources"},
		{"reordered source permission", `sources:"user,repo,env,flag"`, `sources:"env,user,flag"`, "explicit sources"},
		{"extra source permission", `sources:"user,repo,env,flag"`, `sources:"user,env,flag,secret"`, "explicit sources"},
		{"repo-only source permission", `sources:"user,repo,env,flag"`, `sources:"repo"`, "explicit sources"},
		{"missing source permission", `sources:"user,repo,env,flag"`, "", "explicit sources"},
		{"missing environment", `env:"PILOT_NAME"`, "", "invalid env binding"},
		{"duplicate flag", `flag:"pilot-count"`, `flag:"pilot-name"`, "duplicate flag"},
		{"duplicate key", `config:"count"`, `config:"name"`, "duplicate config"},
		{"duplicate env", `env:"PILOT_COUNT"`, `env:"PILOT_NAME"`, "duplicate env"},
		{"missing help", `help:"Name"`, "", "needs flag help"},
		{"unsupported type", "Name string", "Name map[string]string", "unsupported config type"},
		{"bad default", `default:"7"`, `default:"bad"`, "default:"},
		{"negative default", `default:"7"`, `default:"-1"`, "must be non-negative"},
		{"nonfinite default", `default:"0.5"`, `default:"NaN"`, "default must be finite"},
		{"missing integer policy", `nonnegative:"true"`, "", "require nonnegative policy"},
		{"invalid integer policy", `nonnegative:"true"`, `nonnegative:"false"`, "supported only as true"},
		{"private field", "Name string", "name string", "exported"},
		{"multiple names", "Name string", "Name, Other string", "singly named"},
		{"missing type", "PilotConfig", "OtherConfig", "not found"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(sample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
}

func TestSchemaEnvironmentOnlyAndAliasFailsClosed(t *testing.T) {
	for _, tc := range []struct{ name, old, new, want string }{
		{"environment-only config", `sources:"user,repo,env,flag"`, `sources:"env,flag"`, "absent config tag"},
		{"empty config", `config:"name"`, `config:""`, "absent config tag"},
		{"reordered grant", `sources:"user,repo,env,flag"`, `sources:"flag,env"`, "explicit sources"},
		{"empty alias", `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:""`, "invalid env binding"},
		{"multiple aliases", `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:"FIRST,SECOND"`, "invalid env binding"},
		{"whitespace alias", `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:" ALIAS"`, "invalid env binding"},
		{"integer alias", `env:"PILOT_COUNT"`, `env:"PILOT_COUNT" envAlias:"COUNT_ALIAS"`, "only for string fields"},
		{"float alias", `env:"PILOT_CPUS"`, `env:"PILOT_CPUS" envAlias:"CPU_ALIAS"`, "only for string fields"},
		{"boolean alias", `env:"PILOT_ENABLED"`, `env:"PILOT_ENABLED" envAlias:"BOOL_ALIAS"`, "only for string fields"},
		{"list alias", `env:"PILOT_PORTS"`, `env:"PILOT_PORTS" envAlias:"LIST_ALIAS"`, "only for string fields"},
		{"own primary collision", `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:"PILOT_NAME"`, "duplicate env binding"},
		{"later primary collision", `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:"PILOT_COUNT"`, "duplicate env binding"},
		{"earlier primary collision", `env:"PILOT_COUNT"`, `env:"PILOT_COUNT" envAlias:"PILOT_NAME"`, "duplicate env binding"},
		{"alias collision", `env:"PILOT_COUNT"`, `env:"PILOT_COUNT" envAlias:"NAME_ALIAS"`, "duplicate env binding"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			source := sample
			if tc.name == "empty config" {
				source = strings.Replace(source, `sources:"user,repo,env,flag"`, `sources:"env,flag"`, 1)
			}
			if tc.name == "alias collision" {
				source = strings.Replace(source, `env:"PILOT_NAME"`, `env:"PILOT_NAME" envAlias:"NAME_ALIAS"`, 1)
			}
			_, err := parseSchema([]byte(strings.Replace(source, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
}

func TestGenerateEnvironmentOnlyAliasBindings(t *testing.T) {
	source := strings.Replace(sample, `config:"name" `, "", 1)
	source = strings.Replace(source, `sources:"user,repo,env,flag"`, `sources:"env,flag" envAlias:"PILOT_NAME_ALIAS"`, 1)
	for _, trusted := range []bool{false, true} {
		t.Run(map[bool]string{false: "ordinary files", true: "trusted files"}[trusted], func(t *testing.T) {
			input := source
			if trusted {
				input = strings.Replace(input, `sources:"user,repo,env,flag"`, `sources:"user,env,flag"`, 1)
			}
			s, err := parseSchema([]byte(input), "PilotConfig", "pilot")
			if err != nil {
				t.Fatal(err)
			}
			if !s.fields[0].noFile || s.fields[0].trustedFileOnly || s.fields[0].envAlias != "PILOT_NAME_ALIAS" {
				t.Fatalf("unexpected environment-only field: %+v", s.fields[0])
			}
			output, err := generate(s, "pilot.go")
			if err != nil {
				t.Fatal(err)
			}
			again, err := generate(s, "pilot.go")
			if err != nil || !bytes.Equal(output, again) {
				t.Fatalf("nondeterministic output: %v", err)
			}
			text := string(output)
			fileType := strings.SplitN(strings.SplitN(text, "type filePilotConfig struct {", 2)[1], "}", 2)[0]
			if strings.Contains(fileType, "Name") || strings.Contains(text, "file.Name") {
				t.Fatal("environment-only field admitted to file input")
			}
			if strings.Contains(text, ", trusted bool") != trusted {
				t.Fatal("environment-only field changed trusted parameter policy")
			}
			for _, want := range []string{
				`const PilotConfigDefaultName string = "test"`,
				`cfg.Name = getenv("PILOT_NAME", getenv("PILOT_NAME_ALIAS", cfg.Name))`,
				`fs.String("pilot-name", defaults.Name, "Name")`,
				`cfg.Name = *values.Name`,
			} {
				if !strings.Contains(text, want) {
					t.Fatalf("missing environment/flag binding %q", want)
				}
			}
			typecheckGenerated(t, input, output)
		})
	}
}

const flagOnlySample = "package cli\ntype PilotConfig struct {\n" +
	" Name string `sources:\"flag\" flag:\"pilot-name\" help:\"Name\" default:\"test\"`\n" +
	" Count int `sources:\"flag\" flag:\"pilot-count\" help:\"Count\" default:\"7\" nonnegative:\"true\"`\n" +
	" CPUs float64 `sources:\"flag\" flag:\"pilot-cpus\" help:\"CPUs\" default:\"0.5\"`\n" +
	" Enabled bool `sources:\"flag\" flag:\"pilot-enabled\" help:\"Enabled\" default:\"true\"`\n" +
	" Ports []string `sources:\"flag\" flag:\"pilot-ports\" help:\"Ports\"`\n}"

func TestSchemaFlagOnlyFailsClosed(t *testing.T) {
	for _, tag := range []string{"config", "env", "envAlias"} {
		for _, value := range []string{"", "binding"} {
			t.Run(tag+"/"+value, func(t *testing.T) {
				source := strings.Replace(flagOnlySample, `sources:"flag"`, `sources:"flag" `+tag+`:"`+value+`"`, 1)
				_, err := parseSchema([]byte(source), "PilotConfig", "pilot")
				if err == nil || !strings.Contains(err.Error(), "absent "+tag+" tag") {
					t.Fatalf("contradictory %s tag: %v", tag, err)
				}
			})
		}
	}
	for _, tc := range []struct{ name, old, new, want string }{
		{"missing flag", `flag:"pilot-name"`, "", "invalid flag binding"},
		{"missing help", `help:"Name"`, "", "needs flag help"},
		{"duplicate flag", `flag:"pilot-count"`, `flag:"pilot-name"`, "duplicate flag binding"},
		{"integer policy", `nonnegative:"true"`, "", "require nonnegative policy"},
		{"list default", `help:"Ports"`, `help:"Ports" default:"one"`, "defaults for []string are not supported"},
		{"unsupported type", "Name string", "Name map[string]string", "unsupported config type"},
		{"unsupported grant", `sources:"flag"`, `sources:"user,flag"`, "explicit sources"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(flagOnlySample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
}

func TestGenerateFlagOnlyBindings(t *testing.T) {
	for _, mixed := range []bool{false, true} {
		t.Run(map[bool]string{false: "flag-only lists", true: "later environment list"}[mixed], func(t *testing.T) {
			source := flagOnlySample
			if mixed {
				source = strings.TrimSuffix(source, "}") + " Later []string `config:\"later\" env:\"PILOT_LATER\" flag:\"pilot-later\" sources:\"user,repo,env,flag\" help:\"Later\"`\n}"
			}
			s, err := parseSchema([]byte(source), "PilotConfig", "pilot")
			if err != nil {
				t.Fatal(err)
			}
			output, err := generate(s, "pilot.go")
			if err != nil {
				t.Fatal(err)
			}
			again, err := generate(s, "pilot.go")
			if err != nil || !bytes.Equal(output, again) {
				t.Fatalf("nondeterministic output: %v", err)
			}
			text := string(output)
			if strings.Contains(text, `"os"`) != mixed || !strings.Contains(text, `"strings"`) {
				t.Fatal("imports do not match list source grants")
			}
			fileType := strings.SplitN(strings.SplitN(text, "type filePilotConfig struct {", 2)[1], "}", 2)[0]
			envBody := strings.SplitN(strings.SplitN(text, "func (cfg *PilotConfig) applyEnv() error {", 2)[1], "// PilotConfigFlagValues", 2)[0]
			for _, f := range s.fields[:5] {
				if !f.noFile || !f.noEnv || f.trustedFileOnly {
					t.Fatalf("unexpected flag-only source facts for %s", f.name)
				}
				if strings.Contains(fileType, f.name) || strings.Contains(text, "file."+f.name) || strings.Contains(envBody, "cfg."+f.name) {
					t.Fatalf("flag-only field %s admitted to file/environment", f.name)
				}
				if !strings.Contains(text, `if flagWasSet(fs, "`+f.flag+`")`) {
					t.Fatalf("missing explicit flag application for %s", f.name)
				}
			}
			for _, want := range []string{
				`const PilotConfigDefaultName string = "test"`,
				`const PilotConfigDefaultCount int = 7`,
				`const PilotConfigDefaultCPUs float64 = 0.5`,
				`const PilotConfigDefaultEnabled bool = true`,
				`fs.String("pilot-ports", strings.Join(defaults.Ports, ","), "Ports")`,
				`cfg.Ports = splitCommaList(*values.Ports)`,
			} {
				if !strings.Contains(text, want) {
					t.Fatalf("missing flag/default binding %q", want)
				}
			}
			if mixed && !strings.Contains(envBody, `os.Getenv("PILOT_LATER")`) {
				t.Fatal("later list lost environment binding")
			}
			typecheckGenerated(t, source, output)
		})
	}
}

func TestSchemaFileIgnoreEmptyFailsClosed(t *testing.T) {
	for _, tc := range []struct{ name, old, new string }{
		{"false", `help:"Name"`, `help:"Name" fileIgnoreEmpty:"false"`},
		{"empty", `help:"Name"`, `help:"Name" fileIgnoreEmpty:""`},
		{"integer", `help:"Count"`, `help:"Count" fileIgnoreEmpty:"true"`},
		{"float", `help:"CPUs"`, `help:"CPUs" fileIgnoreEmpty:"true"`},
		{"boolean", `help:"Enabled"`, `help:"Enabled" fileIgnoreEmpty:"true"`},
		{"list", `help:"Ports"`, `help:"Ports" fileIgnoreEmpty:"true"`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(sample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), "fileIgnoreEmpty is supported only as true for string fields with a file source") {
				t.Fatalf("invalid file-only policy: %v", err)
			}
		})
	}
	for _, grant := range []string{"env,flag", "flag"} {
		t.Run(grant, func(t *testing.T) {
			source := strings.Replace(flagOnlySample, `sources:"flag"`, `sources:"`+grant+`" fileIgnoreEmpty:"true"`, 1)
			if grant == "env,flag" {
				source = strings.Replace(source, `help:"Name"`, `help:"Name" env:"PILOT_NAME"`, 1)
			}
			_, err := parseSchema([]byte(source), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), "fileIgnoreEmpty is supported only as true for string fields with a file source") {
				t.Fatalf("file-only policy without file source: %v", err)
			}
		})
	}
}

func TestGenerateFileIgnoreEmpty(t *testing.T) {
	for _, grant := range []string{"user,repo,env,flag", "user,env,flag"} {
		t.Run(grant, func(t *testing.T) {
			source := strings.Replace(sample, `sources:"user,repo,env,flag"`, `sources:"`+grant+`"`, 1)
			s, err := parseSchema([]byte(source), "PilotConfig", "pilot")
			if err != nil {
				t.Fatal(err)
			}
			before, err := generate(s, "pilot.go")
			if err != nil {
				t.Fatal(err)
			}
			source = strings.Replace(source, `help:"Name"`, `help:"Name" fileIgnoreEmpty:"true"`, 1)
			s, err = parseSchema([]byte(source), "PilotConfig", "pilot")
			if err != nil {
				t.Fatal(err)
			}
			if !s.fields[0].fileIgnoreEmpty {
				t.Fatal("missing explicit empty-file policy")
			}
			output, err := generate(s, "pilot.go")
			if err != nil {
				t.Fatal(err)
			}
			again, err := generate(s, "pilot.go")
			if err != nil || !bytes.Equal(output, again) {
				t.Fatalf("nondeterministic output: %v", err)
			}
			// The declaration changes only the file predicate, not env/flags or other fields.
			want := strings.Replace(string(before), "file.Name != nil {", `file.Name != nil && *file.Name != "" {`, 1)
			if string(output) != want {
				t.Fatalf("unexpected change beyond empty-string file predicate:\n%s", output)
			}
			typecheckGenerated(t, source, output)
		})
	}
}

func TestCheckMissingFreshAndStaleOutput(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "pilot.go")
	output := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(source, []byte(sample), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("missing output accepted")
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatal("check created missing output")
	}
	if err := run(source, output, "PilotConfig", "pilot", false); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err != nil {
		t.Fatal(err)
	}
	original, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte(strings.Replace(sample, `default:"7"`, `default:"8"`, 1)), 0600); err != nil {
		t.Fatal(err)
	}
	if err := run(source, output, "PilotConfig", "pilot", true); err == nil {
		t.Fatal("stale output accepted")
	}
	current, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(original, current) {
		t.Fatal("check changed output")
	}
}

// Part of ordinary go test ./...: no separate CI registration is required.
func TestVercelSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_vercel_sandbox.go", "../../internal/cli/config_vercel_sandbox_generated.go", "VercelSandboxConfig", "vercel-sandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestCodeSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_codesandbox.go", "../../internal/cli/config_codesandbox_generated.go", "CodeSandboxConfig", "codesandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestCuaGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_cua.go", "../../internal/cli/config_cua_generated.go", "CuaConfig", "cua", true); err != nil {
		t.Fatal(err)
	}
}

func TestOpenSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_opensandbox.go", "../../internal/cli/config_opensandbox_generated.go", "OpenSandboxConfig", "opensandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestAnthropicSandboxRuntimeGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_anthropic_sandbox_runtime.go", "../../internal/cli/config_anthropic_sandbox_runtime_generated.go", "AnthropicSRTConfig", "anthropic-sandbox-runtime", true); err != nil {
		t.Fatal(err)
	}
}

func TestCloudRunSandboxGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_cloud_run_sandbox.go", "../../internal/cli/config_cloud_run_sandbox_generated.go", "CloudRunSandboxConfig", "cloud-run-sandbox", true); err != nil {
		t.Fatal(err)
	}
}

func TestFastAPICloudGeneratedConfigIsCurrent(t *testing.T) {
	if err := run("../../internal/cli/config_fastapi_cloud.go", "../../internal/cli/config_fastapi_cloud_generated.go", "FastAPICloudConfig", "fastapi-cloud", true); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateScalarOnlyImports(t *testing.T) {
	s, err := parseSchema([]byte(sample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	s.fields = s.fields[:1]
	// Help text must not influence which Go packages are imported.
	s.fields[0].help = "Use os.Getenv( or strings.Join( in your application"
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	typecheckGenerated(t, sample, output)
	if strings.Contains(string(output), `"os"`) || strings.Contains(string(output), `"strings"`) {
		t.Fatal("scalar-only schema has unused list imports")
	}
}

func TestGenerateTrustedFileBindings(t *testing.T) {
	// Keep a restricted integer between ordinary fields to preserve validation order.
	source := strings.Replace(sample, `sources:"user,repo,env,flag" help:"Count"`, `sources:"user,env,flag" help:"Count"`, 1)
	source = strings.Replace(source, `sources:"user,repo,env,flag" help:"Ports"`, `sources:"user,env,flag" help:"Ports"`, 1)
	s, err := parseSchema([]byte(source), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	for i, f := range s.fields {
		if f.trustedFileOnly != (i == 1 || i == 4) {
			t.Fatalf("%s trusted-file fact = %v", f.name, f.trustedFileOnly)
		}
	}
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	again, err := generate(s, "pilot.go")
	if err != nil || !bytes.Equal(output, again) {
		t.Fatalf("nondeterministic trusted output: %v", err)
	}
	text := string(output)
	previous := -1
	for _, want := range []string{
		"func (cfg *PilotConfig) applyFile(file *filePilotConfig, trusted bool) error",
		"if file.Name != nil {",
		"if trusted && file.Count != nil {\n\t\tif *file.Count < 0 {",
		"cfg.Count = *file.Count",
		"if file.CPUs != nil {",
		"if file.Enabled != nil {",
		"if trusted && file.Ports != nil {\n\t\tcfg.Ports = normalizeList(*file.Ports)",
	} {
		index := strings.Index(text, want)
		if index <= previous {
			t.Fatalf("missing or reordered binding %q", want)
		}
		previous = index
	}
	if strings.Count(text, "trusted &&") != 2 {
		t.Fatal("unexpected file trust guards")
	}
	typecheckGenerated(t, source, output)
}

func typecheckGenerated(t *testing.T, source string, output []byte) {
	t.Helper()
	// Signatures match the handwritten helpers; only generated wiring is checked here.
	const helpers = `package cli
import "flag"
func flagWasSet(*flag.FlagSet, string) bool { panic("stub") }
func exit(int, string) error { panic("stub") }
func getenv(string, string) string { panic("stub") }
func getenvFloat(string, float64) float64 { panic("stub") }
func getenvNonNegativeInt(string, int) (int, error) { panic("stub") }
func getenvBool(string) (bool, bool) { panic("stub") }
func normalizeList([]string) []string { panic("stub") }
func splitCommaList(string) []string { panic("stub") }
`
	dir := t.TempDir()
	for _, input := range []struct{ name, source string }{{"source.go", source}, {"generated.go", string(output)}, {"helpers.go", helpers}} {
		if err := os.WriteFile(filepath.Join(dir, input.name), []byte(input.source), 0600); err != nil {
			t.Fatal(err)
		}
	}
	// A trimpath test binary may have no GOROOT for an in-process importer.
	// The Go command discovers its own standard library; compile, never run, the fixture.
	command := exec.Command("go", "build", "source.go", "generated.go", "helpers.go")
	command.Dir = dir
	command.Env = []string{"GOTOOLCHAIN=local", "GOWORK=off", "GOPROXY=off", "GOSUMDB=off", "GOENV=off"}
	for _, name := range []string{"PATH", "HOME", "USERPROFILE", "LOCALAPPDATA", "SystemRoot", "WINDIR", "TMPDIR", "TEMP", "TMP", "GOCACHE", "GOROOT", "GOFLAGS"} {
		if value, ok := os.LookupEnv(name); ok {
			command.Env = append(command.Env, name+"="+value)
		}
	}
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("compile generated config: %v\n%s", err, output)
	}
}

const appliedSample = "package cli\ntype PilotConfig struct {\n" +
	" Input string `sources:\"env\" env:\"PILOT_INPUT\" envAlias:\"PILOT_INPUT_ALIAS\" reportApplied:\"true\"`\n" +
	" Name string `sources:\"user,env,flag\" config:\"name\" env:\"PILOT_NAME\" flag:\"pilot-name\" help:\"Name\" fileIgnoreEmpty:\"true\" reportApplied:\"true\" default:\"same\"`\n" +
	" Enabled bool `sources:\"user,repo,env,flag\" config:\"enabled\" env:\"PILOT_ENABLED\" flag:\"pilot-enabled\" help:\"Enabled\" reportApplied:\"true\"`\n" +
	" Count int `sources:\"user,repo,env,flag\" config:\"count\" env:\"PILOT_COUNT\" flag:\"pilot-count\" help:\"Count\" nonnegative:\"true\"`\n" +
	" Tail string `sources:\"user,repo,env,flag\" config:\"tail\" env:\"PILOT_TAIL\" flag:\"pilot-tail\" help:\"Tail\" reportApplied:\"true\"`\n}"

func TestSchemaEnvironmentOnlyAndReportingFailsClosed(t *testing.T) {
	for _, tag := range []string{"config", "flag", "help", "default"} {
		for _, value := range []string{"", "binding"} {
			t.Run(tag+"/"+value, func(t *testing.T) {
				source := strings.Replace(appliedSample, `sources:"env"`, `sources:"env" `+tag+`:"`+value+`"`, 1)
				_, err := parseSchema([]byte(source), "PilotConfig", "pilot")
				if err == nil || !strings.Contains(err.Error(), "absent "+tag+" tag") {
					t.Fatalf("contradictory env-only tag: %v", err)
				}
			})
		}
	}
	for _, tc := range []struct{ name, old, new, want string }{
		{"missing env", `env:"PILOT_INPUT"`, "", "invalid env binding"},
		{"empty alias", `envAlias:"PILOT_INPUT_ALIAS"`, `envAlias:""`, "invalid env binding"},
		{"alias collision", `envAlias:"PILOT_INPUT_ALIAS"`, `envAlias:"PILOT_NAME"`, "duplicate env binding"},
		{"env bool", "Input string", "Input bool", "env sources support only string"},
		{"report false", `reportApplied:"true"`, `reportApplied:"false"`, "reportApplied is supported only as true"},
		{"report empty", `reportApplied:"true"`, `reportApplied:""`, "reportApplied is supported only as true"},
		{"report int", `help:"Count"`, `help:"Count" reportApplied:"true"`, "reportApplied is supported only as true"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseSchema([]byte(strings.Replace(appliedSample, tc.old, tc.new, 1)), "PilotConfig", "pilot")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err=%v, want %q", err, tc.want)
			}
		})
	}
	for _, kind := range []string{"float64", "[]string"} {
		source := strings.Replace(appliedSample, "Enabled bool", "Enabled "+kind, 1)
		if _, err := parseSchema([]byte(source), "PilotConfig", "pilot"); err == nil || !strings.Contains(err.Error(), "reportApplied is supported only as true") {
			t.Fatalf("unsupported reporting kind %s: %v", kind, err)
		}
	}
}

func TestGenerateAppliedAndVisitedBindings(t *testing.T) {
	s, err := parseSchema([]byte(appliedSample), "PilotConfig", "pilot")
	if err != nil {
		t.Fatal(err)
	}
	output, err := generate(s, "pilot.go")
	if err != nil {
		t.Fatal(err)
	}
	again, err := generate(s, "pilot.go")
	if err != nil || !bytes.Equal(output, again) {
		t.Fatalf("nondeterministic reporting output: %v", err)
	}
	text := string(output)
	for _, name := range []string{"filePilotConfig", "PilotConfigFlagValues", "PilotConfigVisitedFlags"} {
		body := strings.SplitN(strings.SplitN(text, "type "+name+" struct {", 2)[1], "}", 2)[0]
		if strings.Contains(body, "Input") {
			t.Fatalf("env-only field exposed in %s", name)
		}
	}
	if !strings.Contains(text, `firstNonEmptyEnv("PILOT_INPUT", "PILOT_INPUT_ALIAS")`) || !strings.Contains(text, "visited := PilotConfigFlagPresence(fs)") {
		t.Fatal("missing shared input/flag presence queries")
	}
	if strings.Count(text, `flagWasSet(fs, "pilot-name")`) != 1 || strings.Count(text, `getenvBool("PILOT_ENABLED")`) != 1 {
		t.Fatal("tracked acceptance predicate duplicated")
	}
	// Keep the existing compile-only helper intact; this fixture supplies its new helper signature.
	typecheckGenerated(t, appliedSample+"\nfunc firstNonEmptyEnv(...string) (string, bool) { panic(\"stub\") }\n", output)
	runAppliedFixture(t, output)
}

func runAppliedFixture(t *testing.T, generated []byte) {
	t.Helper()
	// Benign in-memory inputs control helper acceptance; no provider or host environment is read.
	const behavior = `package cli
import ("flag"; "fmt"; "testing")
var input map[string]string
var selections map[string]int
var boolValue, boolAccepted bool
var boolCalls int
var intError bool
func firstNonEmptyEnv(names ...string) (string, bool) {
 selections[names[0]]++
 for _, name := range names { if value := input[name]; value != "" { return value, true } }
 return "", false
}
func getenvBool(string) (bool, bool) { boolCalls++; return boolValue, boolAccepted }
func getenvNonNegativeInt(_ string, prior int) (int, error) { if intError { return 0, fmt.Errorf("bad integer") }; return prior, nil }
func flagWasSet(fs *flag.FlagSet, name string) bool { found := false; fs.Visit(func(f *flag.Flag) { if f.Name == name { found = true } }); return found }
func exit(_ int, message string) error { return fmt.Errorf("%s", message) }
func TestAcceptedAssignments(t *testing.T) {
 name, empty, tail, enabled, bad := "same", "", "later", false, -1
 cfg := defaultPilotConfig(); cfg.Input = "prior"; cfg.Enabled = true; cfg.Count = 8; cfg.Tail = "prior"
 if got, err := cfg.applyFile(nil, true); err != nil || got != (PilotConfigApplied{}) { t.Fatalf("nil file: %+v %v", got, err) }
 got, err := cfg.applyFile(&filePilotConfig{Name:&name, Enabled:&enabled, Count:&bad, Tail:&tail}, true)
 if err == nil || !got.Name || !got.Enabled || got.Input || got.Tail || cfg.Count != 8 || cfg.Tail != "prior" { t.Fatalf("partial file: %+v %+v %v", got, cfg, err) }
 got, err = cfg.applyFile(&filePilotConfig{Name:&name, Tail:&empty}, false)
 if err != nil || got.Name || !got.Tail || cfg.Tail != "" { t.Fatalf("trust/empty: %+v %+v %v", got, cfg, err) }
 got, _ = cfg.applyFile(&filePilotConfig{Name:&empty}, true)
 if got.Name || cfg.Name != name { t.Fatal("ignored empty marked") }
 for _, tc := range []struct{ primary, alias, want string; applied bool }{{"", "", "prior", false}, {"", "alias", "alias", true}, {"same", "alias", "same", true}, {" ", "alias", " ", true}} {
  cfg.Input = "prior"; input = map[string]string{"PILOT_INPUT":tc.primary,"PILOT_INPUT_ALIAS":tc.alias}; selections = map[string]int{}; boolCalls = 0; boolAccepted = false; intError = false
  got, err = cfg.applyEnv()
  if err != nil || got.Input != tc.applied || cfg.Input != tc.want || got.Enabled || selections["PILOT_INPUT"] != 1 || boolCalls != 1 { t.Fatalf("env selection: %+v %+v %v", got, cfg, err) }
 }
 cfg.Name = "same"; cfg.Count = 8; cfg.Tail = "prior"; input = map[string]string{"PILOT_NAME":"same","PILOT_TAIL":"later"}; selections = map[string]int{}; boolAccepted = true; boolValue = false; intError = true
 got, err = cfg.applyEnv()
 if err == nil || !got.Name || !got.Enabled || got.Tail || cfg.Count != 0 || cfg.Tail != "prior" { t.Fatalf("partial env: %+v %+v %v", got, cfg, err) }
 fs := flag.NewFlagSet("fixture", flag.ContinueOnError); values := RegisterPilotConfigFlags(fs, cfg)
 if got := values.Apply(&cfg, fs); got != (PilotConfigApplied{}) { t.Fatalf("registration applied: %+v", got) }
 if err := fs.Parse([]string{"--pilot-name=", "--pilot-enabled=false"}); err != nil { t.Fatal(err) }
 visited := PilotConfigFlagPresence(fs)
 if !visited.Name || !visited.Enabled || visited.Tail || cfg.Name != "same" { t.Fatalf("visits changed config: %+v %+v", visited, cfg) }
 got = values.Apply(&cfg, fs)
 if !got.Name || !got.Enabled || got.Input || got.Tail || cfg.Name != "" || cfg.Enabled { t.Fatalf("flag application: %+v %+v", got, cfg) }
}
`
	dir := t.TempDir()
	for _, file := range []struct{ name, content string }{{"source.go", appliedSample}, {"generated.go", string(generated)}, {"behavior_test.go", behavior}} {
		if err := os.WriteFile(filepath.Join(dir, file.name), []byte(file.content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	command := exec.Command("go", "test", "source.go", "generated.go", "behavior_test.go")
	command.Dir = dir
	command.Env = []string{"GOTOOLCHAIN=local", "GOWORK=off", "GOPROXY=off", "GOSUMDB=off", "GOENV=off"}
	for _, name := range []string{"PATH", "HOME", "USERPROFILE", "LOCALAPPDATA", "SystemRoot", "WINDIR", "TMPDIR", "TEMP", "TMP", "GOCACHE", "GOROOT", "GOFLAGS"} {
		if value, ok := os.LookupEnv(name); ok {
			command.Env = append(command.Env, name+"="+value)
		}
	}
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("applied scalar fixture: %v\n%s", err, output)
	}
}

func TestGenerateOnlyEnvironmentField(t *testing.T) {
	for _, tracked := range []bool{false, true} {
		source := "package cli\ntype PilotConfig struct { Input string `sources:\"env\" env:\"PILOT_INPUT\" envAlias:\"PILOT_ALIAS\"` }"
		if tracked {
			source = strings.Replace(source, `sources:"env"`, `sources:"env" reportApplied:"true"`, 1)
		}
		s, err := parseSchema([]byte(source), "PilotConfig", "pilot")
		if err != nil {
			t.Fatal(err)
		}
		output, err := generate(s, "pilot.go")
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(output), "VisitedFlags") || strings.Contains(string(output), "FlagPresence") {
			t.Fatal("env-only schema emitted unused flag presence surface")
		}
		if !tracked && !strings.Contains(string(output), `cfg.Input = getenv("PILOT_INPUT", getenv("PILOT_ALIAS", cfg.Input))`) {
			t.Fatal("untracked env-only fallback changed")
		}
		typecheckGenerated(t, source+"\nfunc firstNonEmptyEnv(...string) (string, bool) { panic(\"stub\") }\n", output)
	}
}
