import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..");
const verifier = path.join(repoRoot, "scripts", "verify-homebrew-release.sh");
const source = fs.readFileSync(verifier, "utf8");
const credentialGuards = `${source}\n${fs.readFileSync(
  path.join(repoRoot, "scripts", "release-config.sh"),
  "utf8",
)}`;

const hashes = {
  darwinAmd64: "a".repeat(64),
  darwinArm64: "b".repeat(64),
  linuxAmd64: "c".repeat(64),
  linuxArm64: "d".repeat(64),
};
const forbiddenCredentials = [
  "GH_TOKEN",
  "GITHUB_TOKEN",
  "GH_ENTERPRISE_TOKEN",
  "GITHUB_ENTERPRISE_TOKEN",
  "HOMEBREW_GITHUB_API_TOKEN",
  "HOMEBREW_GITHUB_PACKAGES_TOKEN",
  "HOMEBREW_TAP_GITHUB_TOKEN",
  "HOMEBREW_TAP_TOKEN",
  "ACTIONS_RUNTIME_TOKEN",
  "ACTIONS_ID_TOKEN_REQUEST_TOKEN",
  "CODESIGN_IDENTITY",
  "CODESIGN_KEYCHAIN",
  "MACOS_CODESIGN_IDENTITY",
  "MACOS_SIGNING_CERT_BASE64",
  "MACOS_SIGNING_CERT_PASSWORD",
  "MAC_RELEASE_OP_ACCOUNT",
  "MAC_RELEASE_OP_FIELDS",
  "MAC_RELEASE_OP_ITEM",
  "MAC_RELEASE_OP_VAULT",
  "MAC_RELEASE_CODESIGN_IDENTITY",
  "MAC_RELEASE_CODESIGN_KEYCHAIN",
  "MAC_RELEASE_CODESIGN_KEYCHAIN_PASSWORD",
  "MAC_RELEASE_CODESIGN_OP_ACCOUNT",
  "MAC_RELEASE_CODESIGN_OP_ITEM",
  "MAC_RELEASE_CODESIGN_OP_VAULT",
  "NOTARYTOOL_KEYCHAIN_PROFILE",
  "NOTARYTOOL_APPLE_ID",
  "NOTARYTOOL_PASSWORD",
  "NOTARYTOOL_TEAM_ID",
  "APPLE_ID",
  "APPLE_API_ISSUER",
  "APPLE_API_KEY",
  "APPLE_APP_SPECIFIC_PASSWORD",
  "APPLE_TEAM_ID",
  "AC_USERNAME",
  "AC_PASSWORD",
  "AC_PROVIDER",
  "ASC_KEY_ID",
  "ASC_ISSUER_ID",
  "ASC_PRIVATE_KEY",
  "OP_SERVICE_ACCOUNT_TOKEN",
];

function formula(overrides = {}, { literalUrls = true } = {}) {
  const values = { ...hashes, ...overrides };
  const releaseUrl = (platform, arch) =>
    literalUrls
      ? `https://github.com/openclaw/crabbox/releases/download/v1.2.3/crabbox_1.2.3_${platform}_${arch}.tar.gz`
      : `https://github.com/openclaw/crabbox/releases/download/v#{version}/crabbox_#{version}_${platform}_${arch}.tar.gz`;
  return `# typed: false
# frozen_string_literal: true

# Generated by the protected Crabbox release tooling. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote software testing and execution"
  homepage "https://github.com/openclaw/crabbox"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${releaseUrl("darwin", "amd64")}"
      sha256 "${values.darwinAmd64}"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm?
      url "${releaseUrl("darwin", "arm64")}"
      sha256 "${values.darwinArm64}"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${releaseUrl("linux", "amd64")}"
      sha256 "${values.linuxAmd64}"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${releaseUrl("linux", "arm64")}"
      sha256 "${values.linuxArm64}"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
`;
}

function verifyFormula(contents) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-formula-"));
  const formulaPath = path.join(root, "crabbox.rb");
  fs.writeFileSync(formulaPath, contents);
  try {
    return spawnSync(
      "/bin/bash",
      [
        "-c",
        'source "$1"; verify_homebrew_formula "$2" "$3" v1.2.3 "$4" "$5" "$6" "$7"',
        "homebrew-formula-test",
        verifier,
        process.execPath,
        formulaPath,
        hashes.darwinAmd64,
        hashes.darwinArm64,
        hashes.linuxAmd64,
        hashes.linuxArm64,
      ],
      { encoding: "utf8" },
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

function sha256(file) {
  return createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

function shellQuote(value) {
  return `'${String(value).replaceAll("'", `'"'"'`)}'`;
}

function writeExecutable(file, contents) {
  fs.writeFileSync(file, contents);
  fs.chmodSync(file, 0o755);
}

function runMockedHomebrewPhase({
  fetchFailure = false,
  installedByteMismatch = false,
  macosVerifierFailure = false,
  releaseTrust = true,
  versionOutput = "1.2.3",
} = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-phase-"));
  const assets = path.join(root, "assets");
  const payload = path.join(root, "payload");
  const fakeRoot = path.join(root, "repo");
  const fakeScripts = path.join(fakeRoot, "scripts");
  const mockBin = path.join(root, "bin");
  const prefix = path.join(root, "prefix");
  const work = path.join(root, "work");
  const home = path.join(work, "home");
  const cache = path.join(work, "cache");
  const log = path.join(root, "calls.log");
  for (const directory of [
    assets,
    payload,
    fakeScripts,
    mockBin,
    prefix,
    work,
    home,
    cache,
  ]) {
    fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
  }

  const cli = path.join(payload, "crabbox");
  const helper = path.join(payload, "crabbox-apple-vm-helper");
  writeExecutable(
    cli,
    `#!/bin/sh\n[ "\${1:-}" = --version ] || exit 64\nprintf '%s\\n' ${shellQuote(versionOutput)}\n`,
  );
  writeExecutable(
    helper,
    `#!/bin/sh\n[ "\${1:-}" = vmd-info ] || exit 64\nprintf '%s\\n' ${shellQuote(
      JSON.stringify({
        embedded: true,
        releaseTrust,
        trustPolicyVersion: 1,
        sha256: "e".repeat(64),
      }),
    )}\n`,
  );

  const archivePaths = {
    darwinAmd64: path.join(assets, "crabbox_1.2.3_darwin_amd64.tar.gz"),
    darwinArm64: path.join(assets, "crabbox_1.2.3_darwin_arm64.tar.gz"),
    linuxAmd64: path.join(assets, "crabbox_1.2.3_linux_amd64.tar.gz"),
    linuxArm64: path.join(assets, "crabbox_1.2.3_linux_arm64.tar.gz"),
  };
  fs.writeFileSync(archivePaths.darwinAmd64, "mock darwin amd64 archive\n");
  execFileSync("tar", [
    "-czf",
    archivePaths.darwinArm64,
    "-C",
    payload,
    "crabbox",
    "crabbox-apple-vm-helper",
  ]);
  fs.writeFileSync(archivePaths.linuxAmd64, "mock linux amd64 archive\n");
  fs.writeFileSync(archivePaths.linuxArm64, "mock linux arm64 archive\n");
  const archiveHashes = Object.fromEntries(
    Object.entries(archivePaths).map(([key, file]) => [key, sha256(file)]),
  );
  const formulaPath = path.join(root, "crabbox.rb");
  fs.writeFileSync(formulaPath, formula(archiveHashes));
  fs.writeFileSync(
    path.join(assets, "provenance.json"),
    JSON.stringify({
      payloads: [
        {
          binaries: [
            {
              name: "crabbox-apple-vm-helper",
              embeddedVmd: { sha256: "e".repeat(64) },
            },
          ],
        },
      ],
    }),
  );
  fs.copyFileSync(
    path.join(repoRoot, "scripts", "render-homebrew-formula.mjs"),
    path.join(fakeScripts, "render-homebrew-formula.mjs"),
  );

  writeExecutable(
    path.join(fakeScripts, "verify-release.sh"),
    `#!/bin/sh\nprintf 'verify-release:%s\\n' "$*" >>${shellQuote(log)}\n`,
  );
  writeExecutable(
    path.join(fakeScripts, "verify-macos-binary.sh"),
    `#!/bin/sh\nprintf 'verify-macos:%s\\n' "$*" >>${shellQuote(log)}\n${
      macosVerifierFailure ? "exit 73\n" : ""
    }`,
  );
  writeExecutable(
    path.join(mockBin, "uname"),
    `#!/bin/sh\ncase "\${1:-}" in\n  -s) printf 'Darwin\\n' ;;\n  -m) printf 'arm64\\n' ;;\n  *) exit 64 ;;\nesac\n`,
  );
  writeExecutable(path.join(mockBin, "lipo"), "#!/bin/sh\nprintf 'arm64\\n'\n");

  const installedCli = path.join(prefix, "bin", "crabbox");
  const installedHelper = path.join(prefix, "bin", "crabbox-apple-vm-helper");
  const corruptInstall = installedByteMismatch
    ? `printf '# changed\\n' >>${shellQuote(installedCli)}\n`
    : "";
  writeExecutable(
    path.join(mockBin, "brew"),
    `#!/bin/sh
printf 'brew:%s\\n' "$*" >>${shellQuote(log)}
case "\${1:-}" in
  update)
    [ "\${2:-}" = --force ] || exit 81
    ;;
  cat)
    [ "\${2:-}" = openclaw/tap/crabbox ] || exit 82
    /bin/cat ${shellQuote(formulaPath)}
    ;;
  fetch)
    [ "\${2:-}" = --force ] || exit 83
    [ "\${3:-}" = --formula ] || exit 84
    [ "\${4:-}" = openclaw/tap/crabbox ] || exit 85
    [ "$HOME" = ${shellQuote(home)} ] || exit 86
    [ "$HOMEBREW_CACHE" = ${shellQuote(cache)} ] || exit 87
    [ -z "$(/usr/bin/find "$HOMEBREW_CACHE" -mindepth 1 -print -quit)" ] || exit 88
    ${fetchFailure ? "exit 74" : ""}
    /usr/bin/touch "$HOMEBREW_CACHE/fetched"
    ;;
  list)
    exit 1
    ;;
  install)
    [ -f "$HOMEBREW_CACHE/fetched" ] || exit 89
    /bin/mkdir -p ${shellQuote(path.join(prefix, "bin"))}
    /bin/cp ${shellQuote(cli)} ${shellQuote(installedCli)}
    /bin/cp ${shellQuote(helper)} ${shellQuote(installedHelper)}
    ${corruptInstall};;
  --prefix)
    printf '%s\\n' ${shellQuote(prefix)}
    ;;
  test)
    ;;
  *)
    exit 90
    ;;
esac
`,
  );

  const command = `
source "$1"
ROOT=$2
MOCK_LOG=$3
require_publishable_source() {
  printf 'verify-source:%s\\n' "$*" >>"$MOCK_LOG"
}
homebrew_phase v1.2.3 "$4" "${"a".repeat(40)}" "${"b".repeat(40)}" "${"c".repeat(
    40,
  )}" arm64 "$5" "$6" "$7"
`;
  const pathValue = `${mockBin}:${path.dirname(process.execPath)}:/usr/bin:/bin:/usr/sbin:/sbin`;
  let result;
  try {
    result = spawnSync(
      "/usr/bin/env",
      [
        "-i",
        `HOME=${home}`,
        `HOMEBREW_CACHE=${cache}`,
        "USER=crabbox-test",
        "LOGNAME=crabbox-test",
        `PATH=${pathValue}`,
        `TMPDIR=${os.tmpdir()}`,
        "LC_ALL=C",
        "HOMEBREW_NO_ANALYTICS=1",
        "HOMEBREW_NO_AUTO_UPDATE=1",
        "HOMEBREW_NO_ENV_HINTS=1",
        "HOMEBREW_NO_INSTALL_CLEANUP=1",
        "NONINTERACTIVE=1",
        "CRABBOX_HOMEBREW_CLEAN_CHILD=1",
        "/bin/bash",
        "-c",
        command,
        "mock-homebrew-phase",
        verifier,
        fakeRoot,
        log,
        assets,
        path.join(mockBin, "brew"),
        process.execPath,
        work,
      ],
      { cwd: repoRoot, encoding: "utf8" },
    );
    return {
      ...result,
      calls: fs.existsSync(log) ? fs.readFileSync(log, "utf8") : "",
    };
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

test("Homebrew verifier is publishability-gated, native, token-free, and read-only", () => {
  const main = source.slice(source.indexOf("main() {"));
  const phase = source.slice(source.indexOf("homebrew_phase() {"), source.indexOf("main() {"));

  assert.match(source, /^FORMULA=openclaw\/tap\/crabbox$/m);
  assert.match(source, /REQUIRE_PUBLISHABLE=1/);
  assert.match(source, /validate-release-publication\.mjs" public-proof/);
  assert.match(source, /public-verifier-run-id/);
  assert.match(source, /artifact\.digest|\.digest \| select/);
  assert.match(
    source,
    /CRABBOX_VERIFY_EXEC_ARCH="\$native_arch"[\s\S]*scripts\/verify-release\.sh/,
  );
  assert.match(source, /\/usr\/bin\/env -i/);
  assert.match(source, /homebrew_home="\$work\/home"/);
  assert.match(source, /homebrew_cache="\$work\/cache"/);
  assert.match(source, /HOME="\$homebrew_home"/);
  assert.match(source, /HOMEBREW_CACHE="\$homebrew_cache"/);
  assert.doesNotMatch(source, /^\s*HOME="\$HOME"/m);
  for (const credential of forbiddenCredentials) {
    assert.match(credentialGuards, new RegExp(`\\b${credential}\\b`));
  }
  assert.doesNotMatch(source, /\bgh(?:\s|$)|brew tap|workflow run|update-formula|git push/);
  assert.doesNotMatch(source, /== --homebrew-phase/);

  assert.ok(main.indexOf("require_publishable_source") < main.indexOf("/usr/bin/env -i"));
  assert.ok(phase.indexOf("require_publishable_source") < phase.indexOf('"$brew_bin" update'));
  assert.ok(phase.indexOf("scripts/verify-release.sh") < phase.indexOf('"$brew_bin" update'));
  assert.ok(phase.indexOf('"$brew_bin" update --force') < phase.indexOf('"$brew_bin" cat'));
  assert.ok(phase.indexOf("verify_homebrew_formula") < phase.indexOf('"$brew_bin" reinstall'));
  assert.ok(phase.indexOf("verify_homebrew_formula") < phase.indexOf('"$brew_bin" fetch'));
  assert.ok(phase.indexOf('"$brew_bin" fetch --force --formula') < phase.indexOf('"$brew_bin" install'));
  assert.ok(phase.indexOf("verify-macos-binary.sh") < phase.indexOf('"$brew_bin" test'));
  assert.ok(phase.indexOf('"$brew_bin" test') < phase.indexOf('"$installed_cli" --version'));
});

test("Homebrew verifier cleanup survives main function scope", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-cleanup-"));
  const result = spawnSync(
    "/bin/bash",
    [
      "-c",
      'source "$1"; CRABBOX_HOMEBREW_VERIFY_WORK=$2; cleanup_homebrew_work',
      "homebrew-cleanup-test",
      verifier,
      root,
    ],
    { encoding: "utf8" },
  );
  assert.equal(result.status, 0, result.stderr);
  assert.equal(fs.existsSync(root), false);
});

test("public Homebrew proof binds the current release, successful run, both native proofs, and local bytes", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-public-proof-"));
  const assetDirectory = path.join(root, "assets");
  fs.mkdirSync(assetDirectory);
  const names = execFileSync(path.join(repoRoot, "scripts", "release-config.sh"), [
    "assets",
    "1.2.3",
  ], { encoding: "utf8" }).trim().split("\n").sort();
  const files = Object.fromEntries(
    names.map((name, index) => {
      const bytes = Buffer.from(`public asset ${index} ${name}\n`);
      fs.writeFileSync(path.join(assetDirectory, name), bytes);
      return [name, bytes];
    }),
  );
  const notes = "exact notes\n";
  fs.writeFileSync(path.join(root, "names.txt"), `${names.join("\n")}\n`);
  fs.writeFileSync(path.join(root, "notes.md"), notes);
  const assets = names.map((name, index) => ({
    id: 1000 + index,
    name,
    size: files[name].length,
    state: "uploaded",
    digest: `sha256:${createHash("sha256").update(files[name]).digest("hex")}`,
    updated_at: "2026-07-10T10:00:00Z",
    url: `https://api.github.com/repos/openclaw/crabbox/releases/assets/${1000 + index}`,
  }));
  const release = {
    id: 123,
    tag_name: "v1.2.3",
    target_commitish: "main",
    name: "v1.2.3",
    body: notes,
    draft: false,
    prerelease: false,
    created_at: "2026-07-10T09:00:00Z",
    updated_at: "2026-07-10T10:05:00Z",
    published_at: "2026-07-10T10:05:00Z",
    assets,
  };
  const run = {
    id: 9002,
    name: "Verify Release Assets",
    display_title: `Verify published 123 for v1.2.3 at ${"c".repeat(40)}`,
    path: ".github/workflows/release-assets.yml",
    workflow_id: 77,
    workflow_url: "https://api.github.com/repos/openclaw/crabbox/actions/workflows/77",
    event: "workflow_dispatch",
    status: "completed",
    conclusion: "success",
    head_branch: "main",
    head_sha: "c".repeat(40),
    repository: { full_name: "openclaw/crabbox" },
    head_repository: { full_name: "openclaw/crabbox" },
    head_commit: { id: "c".repeat(40) },
    run_attempt: 1,
    created_at: "2026-07-10T10:10:00Z",
    run_started_at: "2026-07-10T10:10:01Z",
  };
  const workflow = {
    id: 77,
    name: "Verify Release Assets",
    path: ".github/workflows/release-assets.yml",
    state: "active",
    url: run.workflow_url,
  };
  const artifacts = {
    total_count: 3,
    artifacts: ["release-input", "verified-assets-arm64", "verified-assets-x86_64"].map(
      (name, index) => ({
        id: 500 + index,
        name,
        size_in_bytes: 100 + index,
        digest: `sha256:${String(index).repeat(64)}`,
        expired: false,
        created_at: "2026-07-10T10:11:00Z",
        updated_at: "2026-07-10T10:11:00Z",
        workflow_run: { id: 9002, head_branch: "main", head_sha: "c".repeat(40) },
      }),
    ),
  };
  const proof = (arch) => {
    const value = {
      schemaVersion: 1,
      state: "published",
      repository: "openclaw/crabbox",
      releaseId: 123,
      tag: "v1.2.3",
      tagObject: "a".repeat(40),
      sourceCommit: "b".repeat(40),
      verifierCommit: "c".repeat(40),
      verifierArch: arch,
      title: "v1.2.3",
      targetCommitish: "main",
      notesBytes: Buffer.byteLength(notes),
      notesSha256: createHash("sha256").update(notes).digest("hex"),
      publishedAt: release.published_at,
      releaseUpdatedAt: release.updated_at,
      assets: assets.map((asset) => ({
        id: asset.id,
        name: asset.name,
        size: asset.size,
        sha256: asset.digest.slice(7),
        updatedAt: asset.updated_at,
      })),
    };
    value.manifestSha256 = createHash("sha256")
      .update(JSON.stringify(value))
      .digest("hex");
    return value;
  };
  const writeJson = (name, value) =>
    fs.writeFileSync(path.join(root, name), `${JSON.stringify(value)}\n`);
  writeJson("release.json", release);
  writeJson("run.json", run);
  writeJson("workflow.json", workflow);
  writeJson("artifacts.json", artifacts);
  writeJson("arm.json", proof("arm64"));
  writeJson("x86.json", proof("x86_64"));
  const args = [
    path.join(repoRoot, "scripts", "validate-release-publication.mjs"),
    "public-proof",
    ...["release.json", "run.json", "workflow.json", "artifacts.json", "arm.json", "x86.json", "names.txt", "notes.md"].map((name) => path.join(root, name)),
    assetDirectory,
  ];
  const env = {
    CRABBOX_PUBLISH_REPOSITORY: "openclaw/crabbox",
    CRABBOX_PUBLISH_RELEASE_ID: "123",
    CRABBOX_PUBLISH_TAG: "v1.2.3",
    CRABBOX_PUBLISH_TAG_OBJECT: "a".repeat(40),
    CRABBOX_PUBLISH_SOURCE_COMMIT: "b".repeat(40),
    CRABBOX_PUBLISH_VERIFIER_COMMIT: "c".repeat(40),
    CRABBOX_PUBLISH_VERIFIER_RUN_ID: "9002",
    CRABBOX_PUBLISH_DEFAULT_BRANCH: "main",
    CRABBOX_PUBLISH_WORKFLOW_PATH: ".github/workflows/release-assets.yml",
  };
  try {
    const valid = spawnSync(process.execPath, args, { encoding: "utf8", env });
    assert.equal(valid.status, 0, valid.stderr);

    run.created_at = "2026-07-10T10:03:00Z";
    run.run_started_at = "2026-07-10T10:04:00Z";
    writeJson("run.json", run);
    const stale = spawnSync(process.execPath, args, { encoding: "utf8", env });
    assert.notEqual(stale.status, 0);
    assert.match(stale.stderr, /not newer than release updated_at/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("mocked Homebrew phase proves fresh fetch, frozen bytes, trust, and final execution", () => {
  const result = runMockedHomebrewPhase();
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Verified Homebrew v1\.2\.3 on arm64/);
  assert.match(result.calls, /^verify-source:v1\.2\.3 /m);
  assert.match(result.calls, /^verify-release:v1\.2\.3 /m);
  assert.match(result.calls, /^brew:update --force$/m);
  assert.match(result.calls, /^brew:fetch --force --formula openclaw\/tap\/crabbox$/m);
  assert.match(result.calls, /^brew:install openclaw\/tap\/crabbox$/m);
  assert.match(result.calls, /^verify-macos:org\.openclaw\.crabbox arm64 /m);
  assert.match(
    result.calls,
    /^verify-macos:org\.openclaw\.crabbox\.apple-vm-helper arm64 /m,
  );
  assert.match(result.calls, /^brew:test openclaw\/tap\/crabbox$/m);
  assert.ok(result.calls.indexOf("brew:fetch") < result.calls.indexOf("brew:install"));
  assert.ok(result.calls.indexOf("verify-macos:") < result.calls.indexOf("brew:test"));
});

test("mocked Homebrew phase rejects installed bytes that differ from the release", () => {
  const result = runMockedHomebrewPhase({ installedByteMismatch: true });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /CLI differs from the frozen release archive/);
  assert.doesNotMatch(result.calls, /^verify-macos:/m);
  assert.doesNotMatch(result.calls, /^brew:test /m);
});

test("mocked Homebrew phase stops when the forced public fetch fails", () => {
  const result = runMockedHomebrewPhase({ fetchFailure: true });
  assert.notEqual(result.status, 0);
  assert.match(result.calls, /^brew:fetch --force --formula openclaw\/tap\/crabbox$/m);
  assert.doesNotMatch(result.calls, /^brew:install /m);
  assert.doesNotMatch(result.calls, /^verify-macos:/m);
});

test("mocked Homebrew phase propagates native signature verifier failure", () => {
  const result = runMockedHomebrewPhase({ macosVerifierFailure: true });
  assert.notEqual(result.status, 0);
  assert.match(result.calls, /^verify-macos:org\.openclaw\.crabbox arm64 /m);
  assert.doesNotMatch(
    result.calls,
    /^verify-macos:org\.openclaw\.crabbox\.apple-vm-helper arm64 /m,
  );
  assert.doesNotMatch(result.calls, /^brew:test /m);
});

test("mocked Homebrew phase rejects helper embedded-VMD trust mismatch", () => {
  const result = runMockedHomebrewPhase({ releaseTrust: false });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /wrong embedded VMD trust policy/);
  assert.match(result.calls, /^verify-macos:org\.openclaw\.crabbox arm64 /m);
  assert.match(
    result.calls,
    /^verify-macos:org\.openclaw\.crabbox\.apple-vm-helper arm64 /m,
  );
  assert.match(result.calls, /^brew:test openclaw\/tap\/crabbox$/m);
});

test("mocked Homebrew phase rejects the installed CLI version last", () => {
  const result = runMockedHomebrewPhase({ versionOutput: "1.2.4" });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /version mismatch: 1\.2\.4/);
  assert.match(result.calls, /^brew:test openclaw\/tap\/crabbox$/m);
});

test("formula verifier accepts only the exact four frozen archive mappings", () => {
  const exactCanonical = verifyFormula(formula());
  assert.equal(exactCanonical.status, 0, exactCanonical.stderr);

  const interpolationTemplate = verifyFormula(formula({}, { literalUrls: false }));
  assert.notEqual(interpolationTemplate.status, 0);
  assert.match(interpolationTemplate.stderr, /exact protected canonical program/);

  const wrongHash = verifyFormula(formula({ darwinArm64: "e".repeat(64) }));
  assert.notEqual(wrongHash.status, 0);
  assert.match(wrongHash.stderr, /exact protected canonical program/);

  const wrongContext = verifyFormula(
    formula().replace(
      "crabbox_1.2.3_darwin_amd64.tar.gz",
      "crabbox_1.2.3_linux_amd64.tar.gz",
    ),
  );
  assert.notEqual(wrongContext.status, 0);
  assert.match(wrongContext.stderr, /exact protected canonical program/);

  const extraTarget = verifyFormula(
    formula().replace(
      "  test do",
      `  on_macos do
    if Hardware::CPU.intel?
      url "https://example.test/extra.tar.gz"
      sha256 "${"f".repeat(64)}"
    end
  end

  test do`,
    ),
  );
  assert.notEqual(extraTarget.status, 0);
  assert.match(extraTarget.stderr, /exact protected canonical program/);

  const arbitraryRuby = verifyFormula(
    formula().replace(
      '  homepage "https://github.com/openclaw/crabbox"',
      '  homepage "https://github.com/openclaw/crabbox"\n  system "/usr/bin/touch", "/tmp/should-not-run"',
    ),
  );
  assert.notEqual(arbitraryRuby.status, 0);
  assert.match(arbitraryRuby.stderr, /exact protected canonical program/);

  const unexpectedInterpolation = verifyFormula(
    formula().replace("/download/v1.2.3/", "/download/v#{version}/"),
  );
  assert.notEqual(unexpectedInterpolation.status, 0);
  assert.match(unexpectedInterpolation.stderr, /exact protected canonical program/);

  const rubyExpression = verifyFormula(
    formula().replace(
      'url "https://github.com/openclaw/crabbox/releases/download/v1.2.3/crabbox_1.2.3_darwin_amd64.tar.gz"',
      'url "https://github.com/openclaw/crabbox/releases/download/v" + version',
    ),
  );
  assert.notEqual(rubyExpression.status, 0);
  assert.match(rubyExpression.stderr, /exact protected canonical program/);
});

test("formula verifier rejects any helper install not restricted to macOS arm64", () => {
  const unconditional = verifyFormula(
    formula().replace(
      'bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?',
      'bin.install "crabbox-apple-vm-helper"',
    ),
  );
  assert.notEqual(unconditional.status, 0);
  assert.match(unconditional.stderr, /exact protected canonical program/);
});

test("blocked v0.37.0 record stops before the mocked brew executable", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-blocked-"));
  const assets = path.join(root, "assets");
  const proofs = path.join(root, "proofs");
  const mockBin = path.join(root, "bin");
  const marker = path.join(root, "brew-ran");
  fs.mkdirSync(assets);
  fs.mkdirSync(proofs);
  fs.mkdirSync(mockBin);
  const mockBrew = path.join(mockBin, "brew");
  fs.writeFileSync(mockBrew, `#!/bin/sh\nprintf ran >"${marker}"\nexit 99\n`);
  fs.chmodSync(mockBrew, 0o755);
  writeExecutable(
    path.join(mockBin, "uname"),
    `#!/bin/sh\ncase "\${1:-}" in\n  -s) printf 'Darwin\\n' ;;\n  -m) printf 'arm64\\n' ;;\n  *) exit 64 ;;\nesac\n`,
  );
  try {
    const tagObject = execFileSync("git", ["rev-parse", "refs/tags/v0.37.0"], {
      cwd: repoRoot,
      encoding: "utf8",
    }).trim();
    const sourceCommit = execFileSync("git", ["rev-parse", "refs/tags/v0.37.0^{}"], {
      cwd: repoRoot,
      encoding: "utf8",
    }).trim();
    const verifierCommit = execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: repoRoot,
      encoding: "utf8",
    }).trim();
    const result = spawnSync(
      verifier,
      ["v0.37.0", assets, tagObject, sourceCommit, verifierCommit, "1", "1", proofs],
      {
        cwd: repoRoot,
        encoding: "utf8",
        env: {
          HOME: process.env.HOME,
          PATH: `${mockBin}:${process.env.PATH}`,
          TMPDIR: os.tmpdir(),
        },
      },
    );
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /release v0\.37\.0 is blocked|protected downstream verifier tooling is dirty/);
    assert.equal(fs.existsSync(marker), false, "brew ran despite the protected blocked record");
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("credential presence fails before source or Homebrew execution", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-token-"));
  const assets = path.join(root, "assets");
  const proofs = path.join(root, "proofs");
  const mockBin = path.join(root, "bin");
  const marker = path.join(root, "brew-ran");
  fs.mkdirSync(assets);
  fs.mkdirSync(proofs);
  fs.mkdirSync(mockBin);
  const mockBrew = path.join(mockBin, "brew");
  fs.writeFileSync(mockBrew, `#!/bin/sh\nprintf ran >"${marker}"\nexit 99\n`);
  fs.chmodSync(mockBrew, 0o755);
  try {
    for (const credential of forbiddenCredentials) {
      fs.rmSync(marker, { force: true });
      const result = spawnSync(
        verifier,
        [
          "v1.2.3",
          assets,
          "a".repeat(40),
          "b".repeat(40),
          "c".repeat(40),
          "1",
          "1",
          proofs,
        ],
        {
          cwd: repoRoot,
          encoding: "utf8",
          env: {
            HOME: process.env.HOME,
            PATH: `${mockBin}:${process.env.PATH}`,
            [credential]: "",
          },
        },
      );
      assert.notEqual(result.status, 0, `${credential} was accepted`);
      assert.match(result.stderr, new RegExp(`${credential} must be unset`));
      assert.equal(fs.existsSync(marker), false, `brew ran with ${credential} present`);
    }
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("internal Homebrew phase refuses an unsanitized direct call", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "crabbox-homebrew-direct-"));
  const marker = path.join(root, "brew-ran");
  const mockBrew = path.join(root, "brew");
  fs.writeFileSync(mockBrew, `#!/bin/sh\nprintf ran >"${marker}"\nexit 99\n`);
  fs.chmodSync(mockBrew, 0o755);
  try {
    const result = spawnSync(
      "/bin/bash",
      [
        "-c",
        'source "$1"; homebrew_phase v1.2.3 "$2" "$3" "$4" "$5" "$(uname -m)" "$6" "$7" "$2"',
        "homebrew-direct-test",
        verifier,
        root,
        "a".repeat(40),
        "b".repeat(40),
        "c".repeat(40),
        mockBrew,
        process.execPath,
      ],
      { cwd: repoRoot, encoding: "utf8" },
    );
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /must run through the credential-free launcher/);
    assert.equal(fs.existsSync(marker), false);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
