#!/usr/bin/env bash
# Code generated by scripts/generate-linux-readiness.mjs; DO NOT EDIT.
set -euo pipefail

if test "${1:-}" = '--print-packages'; then
  test "$#" -eq 2 || { echo 'usage: linux-readiness.generated.sh --print-packages PROFILE' >&2; exit 2; }
  case "$2" in
    linux-minimal) printf '%s\n' 'ca-certificates curl git jq openssh-server rsync tmux util-linux' ;;
    linux-builder) printf '%s\n' 'build-essential ca-certificates curl git git-lfs jq openssh-server pkg-config python3 python3-venv rsync tmux util-linux' ;;
    *) echo 'unknown Linux readiness profile' >&2; exit 2 ;;
  esac
  exit 0
fi

if test "$(id -u)" -ne 0; then
  command -v sudo >/dev/null 2>&1 || { echo 'Linux readiness producer requires root' >&2; exit 1; }
  exec sudo -H bash "$0" "$@"
fi

if test "${1:-}" = '--install'; then
  install -d -m 0755 -o root -g root /usr/local/libexec/crabbox
  install -m 0755 -o root -g root "$0" /usr/local/libexec/crabbox/linux-readiness.generated.sh
  exit 0
fi
test "$#" -eq 0 || { echo 'usage: linux-readiness.generated.sh [--install|--print-packages PROFILE]' >&2; exit 2; }

crabbox_readiness_manifest_path='/var/lib/crabbox-readiness/linux.json'
crabbox_legacy_image_marker_path='/var/lib/crabbox/image-ready'
crabbox_readiness_trust_root='/'
crabbox_readiness_owner_uid='0'
crabbox_readiness_owner_gid='0'
crabbox_readiness_system_path='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
crabbox_minimal_manifest_payload='{"profile":"linux-minimal","recipeDigest":"sha256:e53fe3347f8b16609af41f4a6766d74771359d37f25389eca9d656fece47a6df","schema":"crabbox-linux-readiness/v1"}'
crabbox_minimal_manifest_sha256='43f732626f4aabdc47b504044d6e444354315c7e65047ffc16ebf49d2a3d885a'
crabbox_builder_manifest_payload='{"profile":"linux-builder","recipeDigest":"sha256:7cf72f7c26e07f695206af1838d12ed4585fef852224cb91da23a2d37d722e2e","schema":"crabbox-linux-readiness/v1"}'
crabbox_builder_manifest_sha256='9d122b7499ecb989a2dec75db16a6424f16a73902490d79cce62fea765198fc9'

crabbox_minimal_readiness_probes() (
  PATH="$crabbox_readiness_system_path"
  export PATH
  test -s '/etc/ssl/certs/ca-certificates.crt' &&
  command curl --version >/dev/null 2>&1 &&
  command flock --version >/dev/null 2>&1 &&
  command git --version >/dev/null 2>&1 &&
  command jq --version >/dev/null 2>&1 &&
  command rsync --version >/dev/null 2>&1 &&
  test -x '/usr/sbin/sshd' &&
  command tmux -V >/dev/null 2>&1
)

crabbox_builder_additional_readiness_probes() (
  PATH="$crabbox_readiness_system_path"
  export PATH
  command cc --version >/dev/null 2>&1 &&
  command git lfs version >/dev/null 2>&1 &&
  command make --version >/dev/null 2>&1 &&
  command pkg-config --version >/dev/null 2>&1 &&
  command python3 --version >/dev/null 2>&1 &&
  command python3 -c 'with __import__("tempfile").TemporaryDirectory() as directory: __import__("venv").EnvBuilder(with_pip=True).create(directory + "/venv"); __import__("subprocess").run([directory + "/venv/bin/python", "-m", "pip", "--version"], check=True)' >/dev/null 2>&1
)

crabbox_builder_readiness_probes() {
  crabbox_minimal_readiness_probes && crabbox_builder_additional_readiness_probes
}

crabbox_readiness_stat() {
  command -v stat >/dev/null 2>&1 || return 1
  crabbox_stat_result="$(LC_ALL=C LANG=C stat -c '%F:%u:%g:%a:%s' -- "$1" 2>/dev/null)" || return 1
  IFS=: read -r crabbox_stat_type crabbox_stat_uid crabbox_stat_gid crabbox_stat_mode crabbox_stat_size crabbox_stat_extra <<CRABBOX_READINESS_STAT
$crabbox_stat_result
CRABBOX_READINESS_STAT
  test -z "$crabbox_stat_extra" || return 1
  case "$crabbox_stat_uid:$crabbox_stat_gid:$crabbox_stat_mode:$crabbox_stat_size" in
    *[!0-9:]*|*::*|:) return 1 ;;
  esac
}

crabbox_trusted_directory() {
  test -d "$1" && test ! -L "$1" || return 1
  crabbox_readiness_stat "$1" || return 1
  test "$crabbox_stat_type" = 'directory' || return 1
  test "$crabbox_stat_uid" = "$crabbox_readiness_owner_uid" || return 1
  test "$crabbox_stat_gid" = "$crabbox_readiness_owner_gid" || return 1
  case "$crabbox_stat_mode" in
    *[2367][0-7]|*[0-7][2367]) return 1 ;;
  esac
}

crabbox_trusted_parents() {
  crabbox_parent_path="$1"
  crabbox_parent_root="$crabbox_readiness_trust_root"
  test "$crabbox_parent_root" = '/' || crabbox_parent_root="${crabbox_parent_root%/}"
  case "$crabbox_parent_path" in
    "$crabbox_parent_root") crabbox_parent_rest='' ;;
    "$crabbox_parent_root"/*) crabbox_parent_rest="${crabbox_parent_path#"$crabbox_parent_root"/}" ;;
    *) test "$crabbox_parent_root" = '/' || return 1; crabbox_parent_rest="${crabbox_parent_path#/}" ;;
  esac
  crabbox_parent_current="$crabbox_parent_root"
  crabbox_trusted_directory "$crabbox_parent_current" || return 1
  while test -n "$crabbox_parent_rest"; do
    case "$crabbox_parent_rest" in
      */*) crabbox_parent_part="${crabbox_parent_rest%%/*}"; crabbox_parent_rest="${crabbox_parent_rest#*/}" ;;
      *) crabbox_parent_part="$crabbox_parent_rest"; crabbox_parent_rest='' ;;
    esac
    test -n "$crabbox_parent_part" && test "$crabbox_parent_part" != '.' && test "$crabbox_parent_part" != '..' || return 1
    if test "$crabbox_parent_current" = '/'; then
      crabbox_parent_current="/$crabbox_parent_part"
    else
      crabbox_parent_current="$crabbox_parent_current/$crabbox_parent_part"
    fi
    crabbox_trusted_directory "$crabbox_parent_current" || return 1
  done
}

crabbox_trusted_file() {
  crabbox_file_path="$1"
  crabbox_file_mode="$2"
  crabbox_file_parent="${crabbox_file_path%/*}"
  test -n "$crabbox_file_parent" || crabbox_file_parent='/'
  crabbox_trusted_parents "$crabbox_file_parent" || return 1
  test -f "$crabbox_file_path" && test ! -L "$crabbox_file_path" || return 1
  crabbox_readiness_stat "$crabbox_file_path" || return 1
  case "$crabbox_stat_type" in
    'regular file'|'regular empty file') ;;
    *) return 1 ;;
  esac
  test "$crabbox_stat_uid" = "$crabbox_readiness_owner_uid" || return 1
  test "$crabbox_stat_gid" = "$crabbox_readiness_owner_gid" || return 1
  test "$crabbox_stat_mode" = "$crabbox_file_mode" || return 1
  test "$crabbox_stat_size" -le 4096 || return 1
}

crabbox_readiness_file_sha256() {
  command -v sha256sum >/dev/null 2>&1 || return 1
  crabbox_sha_result="$(sha256sum -- "$1" 2>/dev/null)" || return 1
  crabbox_file_sha256="${crabbox_sha_result%% *}"
  test "${#crabbox_file_sha256}" -eq 64 || return 1
  case "$crabbox_file_sha256" in *[!0-9a-f]*) return 1 ;; esac
}

crabbox_readiness_manifest_metadata_matches() {
  crabbox_trusted_file "$crabbox_readiness_manifest_path" 644 || return 1
  crabbox_readiness_file_sha256 "$crabbox_readiness_manifest_path" || return 1
  test "$crabbox_file_sha256" = "$crabbox_minimal_manifest_sha256" ||
    test "$crabbox_file_sha256" = "$crabbox_builder_manifest_sha256"
}

crabbox_readiness_manifest_matches() {
  crabbox_readiness_manifest_metadata_matches || return 1
  if test "$crabbox_file_sha256" = "$crabbox_minimal_manifest_sha256"; then
    crabbox_minimal_readiness_probes
  elif test "$crabbox_file_sha256" = "$crabbox_builder_manifest_sha256"; then
    crabbox_builder_readiness_probes
  else
    return 1
  fi
}

crabbox_ensure_directory() {
  crabbox_directory="$1"
  crabbox_directory_parent="${crabbox_directory%/*}"
  test -n "$crabbox_directory_parent" || crabbox_directory_parent='/'
  crabbox_trusted_parents "$crabbox_directory_parent" || return 1
  if test -e "$crabbox_directory" || test -L "$crabbox_directory"; then
    crabbox_trusted_directory "$crabbox_directory" || return 1
  else
    mkdir -m 0755 -- "$crabbox_directory" || return 1
    chown '0:0' "$crabbox_directory" || return 1
    crabbox_trusted_directory "$crabbox_directory" || return 1
  fi
}

crabbox_atomic_write() (
  crabbox_destination="$1"
  crabbox_contents="$2"
  crabbox_destination_parent="${crabbox_destination%/*}"
  test -n "$crabbox_destination_parent" || crabbox_destination_parent='/'
  crabbox_trusted_parents "$crabbox_destination_parent" || return 1
  if test -L "$crabbox_destination" || { test -e "$crabbox_destination" && test ! -f "$crabbox_destination"; }; then
    return 1
  fi
  crabbox_temp_path=''
  trap 'if test -n "$crabbox_temp_path"; then rm -f -- "$crabbox_temp_path"; fi' EXIT HUP INT TERM
  crabbox_temp_path="$(mktemp "$crabbox_destination_parent/.linux-readiness.XXXXXXXXXX")" || return 1
  chown '0:0' "$crabbox_temp_path" || return 1
  crabbox_trusted_file "$crabbox_temp_path" 600 || return 1
  printf '%s\n' "$crabbox_contents" >"$crabbox_temp_path" || return 1
  sync "$crabbox_temp_path" 2>/dev/null || sync -f "$crabbox_temp_path" 2>/dev/null || sync || return 1
  chmod 0644 "$crabbox_temp_path" || return 1
  crabbox_trusted_file "$crabbox_temp_path" 644 || return 1
  crabbox_trusted_parents "$crabbox_destination_parent" || return 1
  test ! -L "$crabbox_destination" || return 1
  mv -f -- "$crabbox_temp_path" "$crabbox_destination" || return 1
  crabbox_temp_path=''
  crabbox_trusted_file "$crabbox_destination" 644 || return 1
  sync "$crabbox_destination_parent" 2>/dev/null || sync -f "$crabbox_destination_parent" 2>/dev/null || sync || return 1
)

crabbox_write_readiness_manifest() {
  crabbox_manifest_directory="${crabbox_readiness_manifest_path%/*}"
  crabbox_ensure_directory "$crabbox_manifest_directory" || return 1
  crabbox_atomic_write "$crabbox_readiness_manifest_path" "$1" || return 1
  crabbox_readiness_manifest_metadata_matches || return 1
}

crabbox_legacy_image_marker_parent_safe() {
  crabbox_marker_parent="${crabbox_legacy_image_marker_path%/*}"
  crabbox_marker_ancestor="${crabbox_marker_parent%/*}"
  test -n "$crabbox_marker_ancestor" || crabbox_marker_ancestor='/'
  crabbox_trusted_parents "$crabbox_marker_ancestor" || return 1
  test -d "$crabbox_marker_parent" && test ! -L "$crabbox_marker_parent" || return 1
  crabbox_readiness_stat "$crabbox_marker_parent" || return 1
  test "$crabbox_stat_type" = 'directory' || return 1
  case "$crabbox_stat_mode" in
    *[2367][0-7]|*[0-7][2367]) return 1 ;;
  esac
}

crabbox_ensure_legacy_image_marker_parent() {
  crabbox_marker_parent="${crabbox_legacy_image_marker_path%/*}"
  crabbox_marker_ancestor="${crabbox_marker_parent%/*}"
  test -n "$crabbox_marker_ancestor" || crabbox_marker_ancestor='/'
  crabbox_trusted_parents "$crabbox_marker_ancestor" || return 1
  if test ! -e "$crabbox_marker_parent" && test ! -L "$crabbox_marker_parent"; then
    mkdir -m 0755 -- "$crabbox_marker_parent" || return 1
    chown '0:0' "$crabbox_marker_parent" || return 1
    crabbox_trusted_directory "$crabbox_marker_parent" || return 1
    test "$crabbox_stat_mode" = 755 || return 1
  fi
  crabbox_legacy_image_marker_parent_safe || return 1
}

crabbox_legacy_image_marker_trusted() {
  # The runtime user may own this parent; the marker is only a compatibility hint.
  crabbox_legacy_image_marker_parent_safe || return 1
  test -f "$crabbox_legacy_image_marker_path" && test ! -L "$crabbox_legacy_image_marker_path" || return 1
  crabbox_readiness_stat "$crabbox_legacy_image_marker_path" || return 1
  case "$crabbox_stat_type" in
    'regular file'|'regular empty file') ;;
    *) return 1 ;;
  esac
  test "$crabbox_stat_uid" = "$crabbox_readiness_owner_uid" || return 1
  test "$crabbox_stat_gid" = "$crabbox_readiness_owner_gid" || return 1
  test "$crabbox_stat_mode" = 644 || return 1
  test "$crabbox_stat_size" -le 4096 || return 1
  crabbox_readiness_file_sha256 "$crabbox_legacy_image_marker_path" || return 1
  test "$crabbox_file_sha256" = '709d026dd65ec24ac15c7c8bca310da2d2346e236b50028d2625d76d39f39fea'
}

crabbox_write_legacy_image_marker() (
  crabbox_ensure_legacy_image_marker_parent || return 1
  crabbox_marker_parent="${crabbox_legacy_image_marker_path%/*}"
  crabbox_manifest_directory="${crabbox_readiness_manifest_path%/*}"
  crabbox_trusted_parents "$crabbox_manifest_directory" || return 1
  crabbox_manifest_device="$(stat -c '%d' -- "$crabbox_manifest_directory" 2>/dev/null)" || return 1
  crabbox_marker_device="$(stat -c '%d' -- "$crabbox_marker_parent" 2>/dev/null)" || return 1
  case "$crabbox_manifest_device:$crabbox_marker_device" in *[!0-9:]*|*::*|:) return 1 ;; esac
  test "$crabbox_manifest_device" = "$crabbox_marker_device" || return 1
  if test -L "$crabbox_legacy_image_marker_path" || { test -e "$crabbox_legacy_image_marker_path" && test ! -f "$crabbox_legacy_image_marker_path"; }; then
    return 1
  fi
  crabbox_temp_path=''
  trap 'if test -n "$crabbox_temp_path"; then rm -f -- "$crabbox_temp_path"; fi' EXIT HUP INT TERM
  # Build bytes only in the root-controlled namespace; same-device rename never follows the marker destination.
  crabbox_temp_path="$(mktemp "$crabbox_manifest_directory/.linux-readiness-marker.XXXXXXXXXX")" || return 1
  chown '0:0' "$crabbox_temp_path" || return 1
  crabbox_trusted_file "$crabbox_temp_path" 600 || return 1
  printf '%s\n' 'crabbox-devtools-v1' >"$crabbox_temp_path" || return 1
  sync "$crabbox_temp_path" 2>/dev/null || sync -f "$crabbox_temp_path" 2>/dev/null || sync || return 1
  chmod 0644 "$crabbox_temp_path" || return 1
  crabbox_trusted_file "$crabbox_temp_path" 644 || return 1
  crabbox_legacy_image_marker_parent_safe || return 1
  test ! -L "$crabbox_legacy_image_marker_path" || return 1
  mv -fT -- "$crabbox_temp_path" "$crabbox_legacy_image_marker_path" || return 1
  crabbox_temp_path=''
  crabbox_legacy_image_marker_trusted || return 1
  sync "$crabbox_marker_parent" 2>/dev/null || sync -f "$crabbox_marker_parent" 2>/dev/null || sync || return 1
)

if ! crabbox_minimal_readiness_probes; then
  echo 'Linux readiness producer: minimal capability proof failed' >&2
  exit 1
fi
if crabbox_builder_additional_readiness_probes; then
  crabbox_write_readiness_manifest "$crabbox_builder_manifest_payload"
else
  crabbox_write_readiness_manifest "$crabbox_minimal_manifest_payload"
fi
crabbox_write_legacy_image_marker
crabbox_readiness_manifest_matches
echo 'crabbox Linux readiness manifest and compatibility marker verified'
